### ISSUE TITLE
Create a UI for creating and editing projects

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#106]
**Acceptance criteria**
* The interface allows a user to create a new project. Backend data implementation is #109.
* The interface allows a user to edit a project already created.
* The interface conforms to UX design. See [@gabsie mockup](https://chanzuckerberg.invisionapp.com/share/9VNGMIMATUK#/screens/281752377), though she may need to change this mockup to meet phase 1 objectives (e.g. adding publications, remove 'generate a unique link' link[not phase 1 objective]).
* A new project is considered in draft until a user hits a submit button, at which point it is in submitted state (this is UX so need @gabsie input).
* If a user edits an existing project then it moves back to draft until the user hits the submit button again (this is UX so need @gabsie input).
* For submitter experience phase 1 we do not need to validate project information entered through the UI at this stage, unless we get this validation for free through the dynamic form generation.
* @gabsie accepts the design and implementation.

**Implementation**
* Can involve generating the UI dynamically from the project schema, though some work may be needed to include satellite schemas (e.g. contributors, funders) into a single big project schema for 3rd party dynamic form generation to work.
* If doing this dynamically will take too long then can consider doing it manually. However, let's avoid this if reasonable.
* Strongly connected with #113 since notification requirements may drive some aspects of project creation design (e.g. are there explicit draft and submitted states?)

**Feedback**
Please use [this document](https://docs.google.com/document/d/1h3WAOG3a0E-ML-TnADoskyIFoPK8tcCz3geC9H_8Un8)

**Comment by tburdett** [comment]
> Can involve generating the UI dynamically from the project schema, though some work may be needed to include satellite schemas (e.g. contributors, funders) into a single big project schema for 3rd party dynamic form generation to work.

Assuming additional system-level metadata is added to the `Project.json` class (see my comment [on #109](https://github.com/ebi-ait/hca-ebi-dev-team/issues/109#issuecomment-599746911)), there _should_ be enough information in the [ALPS descriptor](https://api.ingest.archive.data.humancellatlas.org/profile/projects) that is auto-generated by Spring to allow for dynamic UI generation.

**Comment by gabsie** [comment]
Hi, I am entering here some initial comments from myself and @mshadbolt re: the current fields from the Project schema:

1. The Contributor roles need to be multiple options, i.e. not dropdowns, but multiple selects
2. No ontology fields should pop up for the users, i.e the Contributor ontology values should be the options in the dropdowns.
3. Suggestion is to only ask for one field for accession, and we understand which archive it is
4. Authors for Publication - can we skip the Authors, but just have the Publication field.
3. We do need to introduce a couple of new fields around:
when is data going to be available?
what kind of technology? select from multiple technologies
is it going to be open/managed access?

Gabs/Marion

**Comment by aaclan-ebi** [comment]
All changes to project creation/registration form were released to production last 26th May. 

https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#26-may-2020

The feedbacks/suggestions from testing are currently being tracked here: https://docs.google.com/document/d/1h3WAOG3a0E-ML-TnADoskyIFoPK8tcCz3geC9H_8Un8/edit#heading=h.r3h23qtra53s

I'm moving this to Done/In Production as all changes are released to production. 

Future tasks regarding to project registration can be put in a new ticket in future sprints.
