### ISSUE TITLE
[Spike]: Investigate how to maintain wrangler and user groups for authz

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#107]
**Acceptance criteria**
* The available options have been investigated.
* An option has been recommended and agreed upon by the team.

Options include:
* Using the groups facility in AAI. How well is this documented? How well is it working?
* Maintaining our own record of groups in ingest
* Using a groups facility in AAP. Would probably require wider rebasing of authn/z on AAP rather than AAI.
* Using a groups facility in Auth0. Would require rebasing authn/z.

**Comment by tburdett** [comment]
If you plan to make use of AAP, can you let me know? There is an [AAP requirements document](https://docs.google.com/document/d/15TzPrbIa50QFAbjWeerAuKCJjqW6ErC4XJ1H9rj0bb8/edit#heading=h.xmmy70sav36) that identifies quite a lot of required functionality that I expect you will need
