### ISSUE TITLE
Store project registrations

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#109]
We need to store all information associated with a project registration. This is:

* The project metadata itself. Trivially, this is our existing project and associated schemas.
* Metadata connected with the submission process. For example, expected release date of the project, user who can crud it.

**Acceptance criteria**
* Both types of data are stored.

**Implementation**
Expecting both types of metadata to be stored in Mongo. The question will be whether the extra metadata can/should be part of a private schema that includes the public project schema or stored outside the schema (e.g. as part of the Mongo project JSON document without being a schema property).

**Comment by tburdett** [comment]
> The question will be whether the extra metadata can/should be part of a private schema that includes the public project schema or stored outside the schema (e.g. as part of the Mongo project JSON document without being a schema property).

I think I can answer this question; it would be consistent with the (maybe "my") original intent to add "metadata connected with the submission process" to the `Project.java` code that captures the object model. This is analogous to how `File.java` extends the base `MetadataDocument` to add e.g. [file names and cloud URLs](https://github.com/HumanCellAtlas/ingest-core/blob/master/src/main/java/org/humancellatlas/ingest/file/File.java#L36) to the user supplied `content`. The intention was that metadata that aren't part of the user supplied content lives in this java code.

Incidentally, a nice potential refinement would be to define a higher order schema to combine this sort of "system-level" metadata with user-supplied content.

**Comment by aaclan-ebi** [comment]
Discussion on the scope of this is found in the project feedback doc https://docs.google.com/document/d/1h3WAOG3a0E-ML-TnADoskyIFoPK8tcCz3geC9H_8Un8/edit#

All fields outside metadata schema which were agreed in the doc above are already added to project registration form. Changes are released to prod last 26 May. 
https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#26-may-2020

![Screenshot 2020-06-02 at 15.02.47.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/84ec3e96-dc19-4b5d-8a27-dd3aa35ccbda)

Ongoing feedback session with Gabs is ongoing. If there are issues found please create a new ticket for prioritization.
