### ISSUE TITLE
Create HCA projects page

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#110]
We need a UI where users can manage their projects and start registering new ones. This ticket concerns the UI - it can be marked as complete even if the backend functionality isn't done yet (e.g. for deleting projects).

**Acceptance criteria**
* There is a page where the user can see the projects they have registered.
* The user can navigate to a page where they can read a selected project's details (for implementation of this page see #106).
* The user can navigate to a page where they can edit a selected project's details (implemented separately, possibly #106).
* The user can delete a selected project. This ticket covers all UI needs, such as checking whether a user really wants to do this. Actually deleting from storage is implemented in #111.
* The user can start a new project creation (see #106 for implementation of this).
* The projects page is the landing page for the user.
* Wranglers can still reach the submissions dashboard or possibly still have that as their home page rather than the projects page.
* When a wrangler goes to the project page they must be able to see all projects and edit or delete them.
* @gabsie has approved the projects page design and implementation.

**Implementation**
See [@gabsie mockup](https://chanzuckerberg.invisionapp.com/share/9VNGMIMATUK#/screens/281752376). @gabsie will adapt this for phase 1 of the submitter experience (remove dataset concept since we don't have it [yet], remove HCA id since we don't have those in phase 1, remove team link (same reason), possibly add delete link depending on what makes sense UX wise).

**Comment by aaclan-ebi** [comment]
A contributor will be redirected to the home page showing the list of their created projects.

Changes were released to prod last 26th May. https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#26-may-2020
