### ISSUE TITLE
Delete a project registration

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#111]
**Acceptance criteria**
* A user can delete their project registrations.
* A wrangler can delete any project registration.
* On deletion the project is entirely removed from the Mongo database, including any registration-oriented project data that isn't in the schema

**Implementaton issue**
Should it be possible for a user to delete a project registration that is in the EBI archives? For phase 1, I (justincc) don't think we need to answer the question - we just hope that our users aren't dumbasses or make mistakes too often. Happy to see counterarguments.

**Comment by tburdett** [comment]
It's definitely a requirement to be able to remove project data (ref e.g. GDPR) but manual processes (e.g. wrangler emails appropriate archive) would be entirely sufficient in an MVP. As stated in the definition, this should be rare-ish
