### ISSUE TITLE
Alter spreadsheet import to use existing project metadata

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#112]
Project metadata will now be coming from existing entries via the UI (or API calls) rather than via the spreadsheet.

**Acceptance criteria**
* The template generator is altered so that it no longer produces spreadsheets with project tabs. Need to consult with the wranglers about this (cc @clairerye). We've agreed that no project information needs to be in this spreadsheets, not even for user reference purposes. Instead, we will associate spreadsheets with projects through the specific project endpoint that receives the submission. We will rely on users naming spreadsheets correctly to track. Personally I (justincc) suspect this won't be enough but that's what people want to go with so let's suck it and see.
* Any project information that is in the spreadsheet is now ignored.
* The metadata from an imported spreadsheet is associated with the correct existing project metadata entered via project registration.

Notes from @MightyAx (via doc)
* Short term we will still have the one “Draft” submission per project rule
* Medium term I think we can remove this restriction provided we move the submit button from the submission to the project. - Alexie

**Comment by aaclan-ebi** [comment]
I believe Item 1 in the acceptance criteria is not implemented and is out of scope of the importer. A different ticket is needed. I'm moving this ticket to Done. It should be possible to upload spreadsheet with entities linked the created project in the UI.

New ticket for template generation changes: https://app.zenhub.com/workspaces/ingest-dev-5cfe1cb26482e537cf35e8d1/issues/ebi-ait/hca-ebi-dev-team/145
