### ISSUE TITLE
[Submitter-UI] Convert "My Projects" and "Project Core" Pages to EBI Visual Framework

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#115]
- Without using the [Json Schema Library](https://github.com/hamzahamidi/ajsf)
- Make just these two pages use the [EBI Visual Framework](https://visual-framework.github.io/vf-core/) to match [gabs' designs](https://chanzuckerberg.invisionapp.com/share/DMWL3W8FG42#/screens/410935127)
- If this splits the project creation into two-steps (project core and all other) this is fine.

**Comment by aaclan-ebi** [comment]
Ingest UI and the create & edit project form are now updated to use Visual Framework and now implemented without the external library (@ajsf/material). 

Changes were released to production last 26th May.
https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#26-may-2020

Moving this ticket to Done/In production.
