### ISSUE TITLE
[Submitter-UI] Make Visual Framework Extension to Json Schema Form Library

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#116]
- Extend Json Schema Form Library to add 'Visual Framework' option.
- Implement this to serve Project Form using Visual Framework design.
- Prove that new widgets can be created by:
  - creating an "contributor" type dropdown
  - creating an ontology picker widget

**Comment by justincc** [comment]
I'm closing since we decided not to take this path.
