### ISSUE TITLE
Address metadata errors for ingest EBI archiver

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-dev-team#118]
Currently, the EBI archiver outputs metadata errors, making the wrangling process manual on that step. As I go through manual curation of the errors for a submission, I will collect and post them here.

Then we will address ~~ @justincc

**Comment by ESapenaVentura** [comment]
Here we go!

I have not filtered by what errors are already addressed (I know some, e.g. the linking problem between submittables was adressed, but I haven't been following on the fixes), so feel free to cross out/point already fixed errors:

- Archiver should use the metadata in the spreadsheets to link to already archived entities. We have fields for biosamples accession, etc that should be used to link the entities instead of creating new ones.

- Archiver doesn't extract files from DCP1 (Likely to not be important, however I want to point it out)

- There is no validation for ontology terms without defining ontology, thus metadata has to be manually corrected if that happens: e.g. `human adult stage` (`HsapDv:0000087`)

- Conversion jobs should only be triggered when the data is 10x and has 3 files in a sequencingRun. Conversion jobs are not needed for:
   - 10x without indexes (only R1 and R2)
   - SS2 and other sc Technologies
   - Non-single cell RNA technologies (e.g. bulk RNA sequencing) (This info can be extracted from field `library_preparation_protocol.library_construction_method.text`)
   - Non-RNA technologies (e.g. Whole Genome Sequencing)

- Archiver needs to use the original IDs as aliases for the submittables created. An alias with a format `HCA_sample_<uuid> is not human friendly and the UUID and sample type is already collected in the other fields.
   - A question that derives from here is how would we name generated bam files and sequencingExperiments (As they have metadata from library prep/sequencing). We should involve all wranglers in this decision.

- Project metadata fields missing:
  - Project - Funders metadata is not being picked up at all
  - Project - Publications:
     - We don't have the fields `journalTitle`, `journalIssn`, `issue`, `year` and `volume` in our metadata, but BioStudies does, so this can be extracted easily in a programmatic way by the pubmedId, using eFetch (And probably the PMCEurope API). An example of a complete project['publications'][0] is:
```
{'pubmedId': '31892341', 'doi': '10.1186/s13059-019-1906-x', 'articleTitle': 'scRNA-seq assessment of the human lung, spleen, and esophagus tissue stability after cold preservation', 'journalTitle': 'Genome Biology', 'authors': 'Madissoon E , Wilbrey-Clark  A , Miragaia RJ , Saeb-Parsy K , Mahbubani K , Georgakopoulos N , Harding P , Polanski K , Nowicki-Osuch K , Fitzgerald RC , Loudon KW , Ferdinand JR , Clatworthy M , Tsingene  A , Van Dongen S , Dabrowska M , Patel M , Stubbington MJT , Teichmann S , Stegle O , Meyer KB', 'journalIssn': '1474-760X', 'issue': '1', 'year': '2020', 'volume': '21'}
```

Sorry for mixing metadata and non-metadata issues here, if you feel like some of the requirements don't belong here please let me know and I'll create a new ticket for archiver improvements

**Comment by ESapenaVentura** [comment]
@justincc pinging to let you know the update to this ticket

**Comment by justincc** [comment]
Input into #67

**Comment by rdgoite** [comment]
@ESapenaVentura can you please confirm that the changes expected here are consistent with the [mapping document](https://docs.google.com/document/d/1DvF0S9rL0IxnMdsi9P3qUVRt-IOT25KWqjwwIU7C9_s/edit?usp=sharing). The work done for #67 is based on the mapping document.

**Comment by ESapenaVentura** [comment]
I think we can close this ticket now
