### ISSUE TITLE
Recreate in EBI AWS the HCA EC2 instance that the wranglers use to manage submissions

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#12]
**Acceptance Criteria**
* [x] We have an EBI AWS EC2 instance with the same specs as the HCA instance that the wranglers use.
* [x] The wranglers have access to this instance. This includes the UCSC wranglers.
* [x] The wranglers have the tools there that they need to perform pre-submission validation.
* [x] The data stored in the EBI AWS instance (on the filesystem, not the S3 buckets) is preserved according to https://github.com/HumanCellAtlas/hca-data-wrangling/issues/399
* [x] The server is accessible via ssh at tool.archive.data.humancellatlas.org

There may be some more details in https://app.zenhub.com/workspaces/ingest-dev-5cfe1cb26482e537cf35e8d1/issues/ebi-ait/hca-ebi-dev-team/8

**Comment by MightyAx** [comment]
### Notes: tool.staging.data.humancellatlas.org
Instance ID: **i-0c647ba1e46c3f12a**
*Canonical, Ubuntu, 16.04 LTS, amd64 xenial image build on 2019-02-12*
Instance Type: **m5.xlarge**
Security groups: **inbound-ssh-from-anywhere**, view inbound rules, view outbound rules

Root Drive: [vol-0dc8802c7391fe092](https://console.aws.amazon.com/ec2/home?region=us-east-1#Volumes:search=vol-0dc8802c7391fe092;sort=desc:createTime)
Volume Type: **gp2** / marketplace: **csv6h7oyg29b7epjzg7qdr7no**

**Comment by MightyAx** [comment]
ec2-3-227-241-69.compute-1.amazonaws.com
i-065bebaccc57c81f7
