### ISSUE TITLE
Implement project registration (phase 1) authz requirements

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#120]
See [Ingest Authz Technical Design](https://docs.google.com/document/d/1uho-3whg2EnUMxK1SU0ZArZU4JZUA4VTCihLC9Z3Ntc)

**Comment by rdgoite** [comment]
Please refer to the Implementation section of the [Ingest Authz](https://docs.google.com/document/d/1uho-3whg2EnUMxK1SU0ZArZU4JZUA4VTCihLC9Z3Ntc/edit?usp=sharing) document for more details on the ongoing implementation.

**Comment by aaclan-ebi** [comment]
Current Authz rules implemented in Ingest.

Ingest Authorisation rules currently implemented:

*CONTRIBUTOR*
* GET list of projects created
* GET , PATCH, PUT any entities if you have link to it
* POST entities
 
*WRANGLER*
* GET a list of all projects
* GET , POST, PATCH, PUT any entities if you have link to it
* POST entities
 
*EVERYONE*
* can login and be a CONTRIBUTOR

*EVERYONE*
* DELETE anything if you have link to it

All Authz changes were released to production last 26th May https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#26-may-2020
