### ISSUE TITLE
Support Account Registration in the UI

### ISSUE THREAD

**Issue by rdgoite** [ebi-ait/hca-ebi-dev-team#123]
The Ingest UI needs to be modified to ensure that Users who are signing-in have registered in the system. If not, the UI should automatically create the Account for them (for now).

See more under the Registration: Phase 1 in the Implementation section of the [Ingest Authz documentation](https://docs.google.com/document/d/1uho-3whg2EnUMxK1SU0ZArZU4JZUA4VTCihLC9Z3Ntc/edit?usp=sharing).

**Comment by aaclan-ebi** [comment]
Changes were released to prod last 26th May. https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#26-may-2020
