### ISSUE TITLE
[UI] Wrangler Spreadsheet Upload With Project Info 

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#124]
### Acceptance Criteria.
Wranglers can use the UI to upload a spreadsheet with project info to create a project and the project's first submission.

**Comment by MightyAx** [comment]
Resolved with [PR #6](https://github.com/ebi-ait/ingest-ui/pull/6)

**Comment by aaclan-ebi** [comment]
Changes were released to prod last 26th May. https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#26-may-2020
