### ISSUE TITLE
[Core] Secure /projects endpoint

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#125]
Currently the `/projects` returns all projects and is accessible with no security restrictions.
### Acceptance Criteria
Change the `/projects` endpoint to return a 403 if the user is not a wrangler (or admin user?).

Speak to @rdgoite for details how to inspect details of the user's token in core.

**Comment by aaclan-ebi** [comment]
Changes were released to prod last 26th May:

https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#26-may-2020
