### ISSUE TITLE
[Core] Primary Wrangler Support

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#126]
### Acceptance Criteria
- Store a Primary Wrangler user against a project.
- If the user is a wrangler, when they inspect the `/user/projects` endpoint:
  - Include projects for which they are the Primary Wrangler.
  - Include projects they created (the current functionality).
- Ensure that non-wrangler users can still use the `/user/projects` endpoint to retrieve projects that they created.

Speak to @rdgoite for how to inspect details of the user's token in core, to check if they are a wrangler.

**Comment by aaclan-ebi** [comment]
I believe not this is not implemented yet. 


`/user/projects` would only return the list of projects that the user has created. I'm moving this to Product backlog for prioritization.

**Comment by aaclan-ebi** [comment]
Changes were released to production last 15th July.
https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#15-july-2020
