### ISSUE TITLE
Deleting any data/metadata associated with HDCA project: single-cell transcriptomics from ingest

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-dev-team#136]
We have been informed that the data and metadata submitted for the project should not be publicly accessible and asked to clean up the data from ingest

This is the project https://data.humancellatlas.org/explore/projects/008e40e8-66ae-43bb-951c-c073a2fa6774

**Comment by lauraclarke** [comment]
@justincc @rolando-ebi can I get an update on this task?

**Comment by rolando-ebi** [comment]
This project needs to be deleted from DCP1 and DCP2 ingest

**Comment by justincc** [comment]
@rolando-ebi At this stage I'm going to vote for taking DCP/1 down entirely (all DCP/1 integration tests are failing now anyway) and only remove it from DCP/1 if it's easy to do.

**Comment by rolando-ebi** [comment]
@lauraclarke Do you know if this project was archived? If so, it'll have to be removed from ENA, BioSamples, etc. @aaclan-ebi and @MightyAx might know this, and a wrangler likely will know

@justincc I think this will be easy to remove from DCP1 ingest

**Comment by lauraclarke** [comment]
My understanding was that it didn't make it to an archive @zperova can you confirm?

**Comment by zperova** [comment]
@lauraclarke as far as I know, we did not archive it (although it is in SCEA according to the tracker). It might have been archived by the authors.

**Comment by lauraclarke** [comment]
I informed SCEA about the redaction request. They are in the process of making an EGA data access request so they can continue to host the publicly releasable information about the study

**Comment by zperova** [comment]
great, thanks @lauraclarke

**Comment by MightyAx** [comment]
I've checked the 20 DSP submissions made by the HCA user, none of them have a project with uuid: 008e40e8-66ae-43bb-951c-c073a2fa6774

**Comment by MightyAx** [comment]
When redacting from ingest we should ensure to redact these projects as well.
- [c46778ed-0c4d-4dbc-a9b6-cab11aee9b0b](https://ui.ingest.archive.data.humancellatlas.org/projects/detail?uuid=c46778ed-0c4d-4dbc-a9b6-cab11aee9b0b) Draft
- [4a825ff7-1290-4c46-9f79-2610225aed67](https://ui.ingest.archive.data.humancellatlas.org/projects/detail?uuid=4a825ff7-1290-4c46-9f79-2610225aed67) Validating
- [008e40e8-66ae-43bb-951c-c073a2fa6774](https://ui.ingest.archive.data.humancellatlas.org/projects/detail?uuid=008e40e8-66ae-43bb-951c-c073a2fa6774) Complete

**Comment by lauraclarke** [comment]
@rolando-ebi any updates here. It would be great for me to be able to say that everything is clean-out of the EBI systems

thanks

Laura

**Comment by rolando-ebi** [comment]
@lauraclarke All done, @MightyAx thanks for discovering the other untracked instances of this projects
