### ISSUE TITLE
Remove all entities for unneeded projects from the production ingest database.

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-dev-team#139]
The current production ingest database contains 268 projects the majority of which are not active and need to be removed.

This database needs to be cleaned up so the database only contains projects which are finished, in progress or stalled and likely to be restarted.

Any test projects or project submissions which were superseded need to be removed

Before removing a project, any Submission that references that project should be deleted.
Using the API to delete submissions will cleanup the other entities, this is not the case for deleting projects.

When performing this delete process, we should ensure that entities linked to the canonical list of projects (contained in the comments below) are not removed.

[Dataset Tracking Sheet](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/edit#gid=0)
[Project Review Spreadsheet](https://docs.google.com/spreadsheets/d/1bE9fbMw0Ujgjag3odL1bnbtqKCw_43T_AHz5mebrzyc/edit?disco=AAAAJ1fTQpo)

### Acceptance criteria

- [ ] The production ingest database only contains projects which are finished, in progress or stalled and likely to be restarted

**Comment by lauraclarke** [comment]
@ebi-ait/hca-wranglers Have I missed any classes of the project which need to be retained?

@MightyAx you had a suggestion for staging to make the cleanup process easier, can you mind me and maybe add appropriate acceptance criteria for the staging instance which reflects that

**Comment by MightyAx** [comment]
Total projects in the system actually approximately 1082 when you remove the filter that hides integration tests. We should ensure that this is a clearout of all projects, not just visible projects.

My suggestion would be that the cleanup is mostly run programatically, rather than having users click in the UI. Once we have our proposed algorithm for deletion we should load staging with a copy of the production database and run our cleanup routine. We can then spot check that we're not removing any crucial data before promoting the change to production, and running there.

It would be very useful to start this process with a list of the 28 canonical project UUIDs, as well as other projects that should be saved. This can be used to provide extra assurance that our removal routine doesn't affect any of this crucial data.

**Comment by lauraclarke** [comment]
thanks @MightyAx do the integration tests not clean up after themselves

@ebi-ait/hca-wranglers do you have a way to get the canonical project UUIDS to start this process?

**Comment by MightyAx** [comment]
Integration tests **do not clean up** after themselves. They should, but they currently don't.

**Comment by justincc** [comment]
It seems to me then that the first step is to make those tests clean up, then deal with what's in the system? If so, I can start looking at that next week.

**Comment by justincc** [comment]
[Dataset Tracking Sheet](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/edit#gid=0)

**Comment by justincc** [comment]
@MightyAx @aaclan-ebi @rolando-ebi When removing these projects is it worth trying to remove all the other entities associated with that project as well? What about the submission envelopes?

**Comment by justincc** [comment]
I propose not to worry about test cleanup but instead regularly wipe the dev and staging databases.

**Comment by justincc** [comment]
@ESapenaVentura today gave me the following list of project UUIDs that need to be preserved from DCP/1. In conversation with @mshadbolt and @ESapenaVentura. in a copy of the production database I am going to 

1. Wipe all projects that aren't in the list *before* the CZI -> EBI AWS switchover happened.
2. Wipe all invalid projects

Then we can assess with the wranglers what's left and whether more needs to be removed.

**Comment by justincc** [comment]
List is

```
c4077b3c-5c98-4d26-a614-246d12c2e5d7
abe1a013-af7a-45ed-8c26-f3793c24a1f4
4e6f083b-5b9a-4393-9890-2a83da8188f1
88ec040b-8705-4f77-8f41-f81e57632f7d
f8aa201c-4ff1-45a4-890e-840d63459ca2
116965f3-f094-4769-9d28-ae675c1b569c
1defdada-a365-44ad-9b29-443b06bd11d6
9c20a245-f2c0-43ae-82c9-2232ec6b594f
4d6f6c96-2a83-43d8-8fe1-0f53bffd4674
8185730f-4113-40d3-9cc3-929271784c2b
4a95101c-9ffc-4f30-a809-f04518a23803
577c946d-6de5-4b55-a854-cd3fde40bff2
091cf39b-01bc-42e5-9437-f419a66c8a45
e0009214-c0a0-4a7b-96e2-d6a83e966ce0
f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc
cc95ff89-2e68-4a08-a234-480eca21ce79
f81efc03-9f56-4354-aabb-6ce819c3d414
027c51c6-0719-469f-a7f5-640fe57cbece
a29952d9-925e-40f4-8a1c-274f118f1f51
74b6d569-3b11-42ef-b6b1-a0454522b4a0
90bd6933-40c0-48d4-8d76-778c103bf545
005d611a-14d5-4fbf-846e-571a1f874f70
a9c022b4-c771-4468-b769-cabcf9738de3
f83165c5-e2ea-4d15-a5cf-33f3550bffde
8c3c290d-dfff-4553-8868-54ce45f4ba7f
ae71be1d-ddd8-4feb-9bed-24c3ddb6e1ad
2043c65a-1cf8-4828-a656-9e247d4e64f1
cddab57b-6868-4be4-806f-395ed9dd635a
```

**Comment by MightyAx** [comment]
Just checking, does your plan for this include deleting any submissions for a project before you delete the project?

**Comment by justincc** [comment]
I hadn't got that far. Should it?

**Comment by MightyAx** [comment]
Absolutely.
It is crucial that we not be delete a project without first deleting the submissions that belong to it. Otherwise the submissions will be orphaned and we will have no identifying details to know whether we should keep or delete them later.

**Comment by aaclan-ebi** [comment]
the project count is 28 from that list. i got 29 from the https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/edit#gid=0&fvid=316687253

```
027c51c6-0719-469f-a7f5-640fe57cbece
008e40e8-66ae-43bb-951c-c073a2fa6774
f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc
1defdada-a365-44ad-9b29-443b06bd11d6
f81efc03-9f56-4354-aabb-6ce819c3d414
a9c022b4-c771-4468-b769-cabcf9738de3
9c20a245-f2c0-43ae-82c9-2232ec6b594f
091cf39b-01bc-42e5-9437-f419a66c8a45
90bd6933-40c0-48d4-8d76-778c103bf545
f83165c5-e2ea-4d15-a5cf-33f3550bffde
4d6f6c96-2a83-43d8-8fe1-0f53bffd4674
cddab57b-6868-4be4-806f-395ed9dd635a
2043c65a-1cf8-4828-a656-9e247d4e64f1
8c3c290d-dfff-4553-8868-54ce45f4ba7f
ae71be1d-ddd8-4feb-9bed-24c3ddb6e1ad
4a95101c-9ffc-4f30-a809-f04518a23803
f8aa201c-4ff1-45a4-890e-840d63459ca2
88ec040b-8705-4f77-8f41-f81e57632f7d
4e6f083b-5b9a-4393-9890-2a83da8188f1
577c946d-6de5-4b55-a854-cd3fde40bff2
74b6d569-3b11-42ef-b6b1-a0454522b4a0
e0009214-c0a0-4a7b-96e2-d6a83e966ce0
a29952d9-925e-40f4-8a1c-274f118f1f51
cc95ff89-2e68-4a08-a234-480eca21ce79
abe1a013-af7a-45ed-8c26-f3793c24a1f4
116965f3-f094-4769-9d28-ae675c1b569c
005d611a-14d5-4fbf-846e-571a1f874f70
c4077b3c-5c98-4d26-a614-246d12c2e5d7
8185730f-4113-40d3-9cc3-929271784c2b
```

Just want to note that we shouldn't delete the analysis submissions and update submissions linked to those projects. They don't have a direct link to the project document so it might be a challenge to find that.

**Comment by lauraclarke** [comment]
This dataset was recent deleted from all of the DCP due to GDPR violations so this should already be gone

HDCA-Sweden-10x 008e40e8-66ae-43bb-951c-c073a2fa6774

**Comment by aaclan-ebi** [comment]
i see, thanks!!!

**Comment by MightyAx** [comment]
I've updated the title and description of this ticket to add some required clarification about projects, submissions, and submission entities.

Any further questions, please let me know.

**Comment by aaclan-ebi** [comment]
I ran the @rolando-ebi 's script that queries the submissions to whitelist last friday in Wrangler EC2. However, it crashed and I got a segmentation fault error. I'm rerunning it again. This may take time even if everything goes well.

In the meantime, I'll try to look into improving the script of find a quicker way to get the submissions whitelist from the projects.

**Comment by aaclan-ebi** [comment]
Unfortunately, the script crashed again after 40min~

I was able to find a way to get a whitelist by doing a query against bundle manifests collection. Cross-checking the submissions count with bundles count from https://tracker.data.humancellatlas.org/, the list seems correct.

```
"summary" : {
		"c4077b3c-5c98-4d26-a614-246d12c2e5d7" : 68,
		"abe1a013-af7a-45ed-8c26-f3793c24a1f4" : 23,
		"4e6f083b-5b9a-4393-9890-2a83da8188f1" : 1,
		"88ec040b-8705-4f77-8f41-f81e57632f7d" : 2310,
		"f8aa201c-4ff1-45a4-890e-840d63459ca2" : 19,
		"116965f3-f094-4769-9d28-ae675c1b569c" : 5,
		"1defdada-a365-44ad-9b29-443b06bd11d6" : 1,
		"9c20a245-f2c0-43ae-82c9-2232ec6b594f" : 1,
		"4d6f6c96-2a83-43d8-8fe1-0f53bffd4674" : 7,
		"8185730f-4113-40d3-9cc3-929271784c2b" : 6,
		"4a95101c-9ffc-4f30-a809-f04518a23803" : 18,
		"577c946d-6de5-4b55-a854-cd3fde40bff2" : 1,
		"091cf39b-01bc-42e5-9437-f419a66c8a45" : 10,
		"e0009214-c0a0-4a7b-96e2-d6a83e966ce0" : 1,
		"f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc" : 1,
		"cc95ff89-2e68-4a08-a234-480eca21ce79" : 128,
		"f81efc03-9f56-4354-aabb-6ce819c3d414" : 1,
		"027c51c6-0719-469f-a7f5-640fe57cbece" : 1,
		"a29952d9-925e-40f4-8a1c-274f118f1f51" : 1,
		"74b6d569-3b11-42ef-b6b1-a0454522b4a0" : 1,
		"90bd6933-40c0-48d4-8d76-778c103bf545" : 1,
		"005d611a-14d5-4fbf-846e-571a1f874f70" : 13,
		"a9c022b4-c771-4468-b769-cabcf9738de3" : 1,
		"f83165c5-e2ea-4d15-a5cf-33f3550bffde" : 7656,
		"8c3c290d-dfff-4553-8868-54ce45f4ba7f" : 1,
		"ae71be1d-ddd8-4feb-9bed-24c3ddb6e1ad" : 1,
		"2043c65a-1cf8-4828-a656-9e247d4e64f1" : 1734,
		"cddab57b-6868-4be4-806f-395ed9dd635a" : 2545
```

14556 submissions are in the whitelist: :
[https://app.zenhub.com/files/232300832/e8595187-024c-49c1-8606-c4eb6f9e860f/download](https://app.zenhub.com/files/232300832/e8595187-024c-49c1-8606-c4eb6f9e860f/download)

Running the delete script https://github.com/ebi-ait/hca-ebi-dev-team/blob/a8b4633c356c2fa7edbcac7fcc17c6589aa783ba/scripts/project_cleanup/delete_submissions.py

The script is currently ignoring the following:
1. update submissions - needs to create a whitelist and wranglers should double check those
2. submissions created this year - to keep submissions done after DCPv1 maintenance mode.

**Comment by aaclan-ebi** [comment]
The following error is now being encountered: 

```
 504 Server Error: GATEWAY_TIMEOUT for url: https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/5abb9ebf8dcbb50007af60f5?force=True
```

Deleting a submission is very expensive at the moment because of checking of links. https://github.com/ebi-ait/ingest-core/blob/master/src/main/java/org/humancellatlas/ingest/submission/SubmissionEnvelopeService.java#L190

Deletion takes so long for big submissions. 

It might make more sense to just delete all entities linked to the submission and bypass checking of links. The checking of links is only needed if an entity is referenced in a different submission. It's very unlikely atm for entities to be referenced in multiple submissions and multiple projects. Since we're deleting the projects not in the whitelist, it should be safe to bypass the checking of links. 

There is no way in the API to bypass the checking of links. 

Will try to create a script to delete each submissions directly in the database.

**Comment by lauraclarke** [comment]
What are the consequences of deleting the projects to the UI is cleaner but not all the downstream entities?

@clairerye do we have a ticket for making sure the integration tests cleanup after themselves?

**Comment by aaclan-ebi** [comment]
> What are the consequences of deleting the projects to the UI is cleaner but not all the downstream entities?
Keeping those entities might slow down queries and other database operations as the data grows. It's also occupying unneeded space. It's better that we remove everything when deleting projects and submissions. 

Bypassing the links check in the API should be straightforward. https://github.com/ebi-ait/ingest-core/commit/de16af9421b7dce406d96a7b35dc1127151c7d60, I can deploy this temporarily in prod tomorrow to proceed with the cleanup.

Please also note that it's not just integration tests that needs to be deleted, wranglers have a lot of abandoned huge submissions before because there is no way for them to fix invalid submissions.

**Comment by aaclan-ebi** [comment]
Prod cleanup is ongoing now.

**Comment by aaclan-ebi** [comment]
Cleanup of projects which were created before year 2020 is done. Only projects in the whitelist were kept. However, there is no whitelist for the recently created projects and submissions yet.

**Comment by aaclan-ebi** [comment]
There are 40 recently (2020) created projects in the UI which needs to be cross checked with the datasets tracker. 


I'll create an issue to fix the project list in the UI to not display the update documents for projects.

**Comment by MightyAx** [comment]
This is great!
There are still 15 thousand submissions in the submission list 🤔

**Comment by aaclan-ebi** [comment]
Yeah, if we can hide the analysis submissions in the UI that would be great. We do have a lot of analysis submissions because there is 1 analysis submission for 1 bundle.

**Comment by MightyAx** [comment]
I've created a [project review spreadsheet](https://docs.google.com/spreadsheets/d/1bE9fbMw0Ujgjag3odL1bnbtqKCw_43T_AHz5mebrzyc/edit?disco=AAAAJ1fTQpo) to help identify out projects and submissions that are eligible for deletion.
