### ISSUE TITLE
Create a plan on how to handle authn/authz for the EBI version of ingest

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#15]
**Acceptance criteria**
 * [x] We have an a proposal

Strawman options, not mutually exclusive in the long term.
1) Instantiate Fusillade. Not a popular option because of difficulties in using it. More heavyweight than what we want.
2) Minimal auth0 to get us up and running. Would need to be an account paid for by the EBI though in the short term we may be able to use a free 'developer' account again.
3) Integrate Elixir AAI/EBI AAP as done by DSP. Will probably take longer so not the immediate term option.

Whatever option we choose, we need to try and preserve ingest's capability of working with Fusillade in case we need to deploy updates to DCP v1. Option 2) may be the best to get things running as soon as possible in the short term, even if we do 3) or 1) in the longer term.

In the first instance we only need to give access to EBI users or limit this to EBI wranglers. We may also need to handle some service to service auth, chiefly between ingest and upload.

**Comment by aaclan-ebi** [comment]
https://docs.google.com/document/d/1KVYX4zI81P4UoB4eAysUUr5GcktGFhcGbRYJ92bjJ-g/edit#heading=h.1vzgmo8s41gj
