### ISSUE TITLE
[UI] Terra Flow Support Phase 1

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#154]
As a contributor I want to know where my dataset is in the overall flow of archiving and exporting to DCP2.

[Design Document](https://docs.google.com/document/d/11NAxNDQ5m-32aEgDkvkwYPWd4pjexspbbncDtpdpjk4/edit#)

1. Display New Submission States in UI
  _Elevate these to project level since only one submission be active at a time?_

1. Give user checkbox options when submitting
  **Submit to Archives and get Accessions**
  **Submit to HCA**
  **Delete Upload Area** (Unticked and disabled if **Submit to HCA** is unticked)
  
  The user must select at least one of **Submit to Archives** and **Submit to HCA**
  Checkboxes default to ticked

1. The submission will wait at the prior step when an option was unticked, (_Archived_ / _Exported_) until the action is triggered.
1. When waiting at _Archived_ the submit button should display **Export to HCA**
  When clicked show the checkbox option for delete upload area again as confirmation.
1. When waiting at _Exported_, the submit button should display **Delete Upload Area**
  _When clicked should this show a confirmation screen or actioned immediately?_

[![](https://mermaid.ink/img/eyJjb2RlIjoic3RhdGVEaWFncmFtXG5bKl0gLS0-IFBlbmRpbmdcblBlbmRpbmcgLS0-IERyYWZ0XG5EcmFmdCAtLT4gVmFsaWRhdGluZ1xuVmFsaWRhdGluZyAtLT4gVmFsaWRcblZhbGlkIC0tPiBEcmFmdFxuVmFsaWRhdGluZyAtLT4gSW52YWxpZFxuSW52YWxpZCAtLT4gRHJhZnRcblZhbGlkIC0tPiBTdWJtaXR0ZWQgOiBzdWJtaXQgdG8gaGNhP1xuVmFsaWQgLS0-IFN1Ym1pdHRlZCA6IHN1Ym1pdCB0byBhcmNoaXZlcyBhbmQgZ2V0IGFjY2Vzc2lvbnM_XG5TdWJtaXR0ZWQgLS0-IFByb2Nlc3NpbmdcblN1Ym1pdHRlZCAtLT4gRXhwb3J0aW5nXG5Qcm9jZXNzaW5nIC0tPiBBcmNoaXZpbmdcbkFyY2hpdmluZyAtLT4gQXJjaGl2ZWRcbkFyY2hpdmVkIC0tPiBFeHBvcnRpbmcgOiBzdWJtaXQgdG8gaGNhP1xuRXhwb3J0aW5nIC0tPiBFeHBvcnRlZFxuRXhwb3J0ZWQgLS0-IENsZWFudXAgOiBkZWxldGUgZGF0YSBmaWxlcz9cbkNsZWFudXAgLS0-IENvbXBsZXRlZFxuQ29tcGxldGVkIC0tPiBbKl1cbiBcbm5vdGUgcmlnaHQgb2YgUHJvY2Vzc2luZ1xuICAgIEdlbmVyYXRpbmcgbWFuaWZlc3RzXG4gICAgV2lsbCB0cnkgdG8gcmVtb3ZlIHRoaXMgaW4gdGhlIG5lYXIgZnV0dXJlXG5lbmQgbm90ZVxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic3RhdGVEaWFncmFtXG5bKl0gLS0-IFBlbmRpbmdcblBlbmRpbmcgLS0-IERyYWZ0XG5EcmFmdCAtLT4gVmFsaWRhdGluZ1xuVmFsaWRhdGluZyAtLT4gVmFsaWRcblZhbGlkIC0tPiBEcmFmdFxuVmFsaWRhdGluZyAtLT4gSW52YWxpZFxuSW52YWxpZCAtLT4gRHJhZnRcblZhbGlkIC0tPiBTdWJtaXR0ZWQgOiBzdWJtaXQgdG8gaGNhP1xuVmFsaWQgLS0-IFN1Ym1pdHRlZCA6IHN1Ym1pdCB0byBhcmNoaXZlcyBhbmQgZ2V0IGFjY2Vzc2lvbnM_XG5TdWJtaXR0ZWQgLS0-IFByb2Nlc3NpbmdcblN1Ym1pdHRlZCAtLT4gRXhwb3J0aW5nXG5Qcm9jZXNzaW5nIC0tPiBBcmNoaXZpbmdcbkFyY2hpdmluZyAtLT4gQXJjaGl2ZWRcbkFyY2hpdmVkIC0tPiBFeHBvcnRpbmcgOiBzdWJtaXQgdG8gaGNhP1xuRXhwb3J0aW5nIC0tPiBFeHBvcnRlZFxuRXhwb3J0ZWQgLS0-IENsZWFudXAgOiBkZWxldGUgZGF0YSBmaWxlcz9cbkNsZWFudXAgLS0-IENvbXBsZXRlZFxuQ29tcGxldGVkIC0tPiBbKl1cbiBcbm5vdGUgcmlnaHQgb2YgUHJvY2Vzc2luZ1xuICAgIEdlbmVyYXRpbmcgbWFuaWZlc3RzXG4gICAgV2lsbCB0cnkgdG8gcmVtb3ZlIHRoaXMgaW4gdGhlIG5lYXIgZnV0dXJlXG5lbmQgbm90ZVxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

**Comment by aaclan-ebi** [comment]
![Screenshot 2020-06-17 at 10.06.23.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/9e786a8e-5352-4f35-a149-608f5b47a1bb)
 will try to get this ready for testing in dev later today.

**Comment by aaclan-ebi** [comment]
After midsprint review meeting, it was agreed to put back the option to exclude the upload area deletion.![Screenshot 2020-06-17 at 14.03.12.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/e63fd108-8d3d-4926-91e1-b3e664ac099e)

**Comment by aaclan-ebi** [comment]
![Screenshot 2020-06-17 at 14.04.01.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/4d3150ab-45ea-4cb9-90a1-646146c8dbb0)

![Screenshot 2020-06-17 at 14.03.52.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/6c0cd53b-4d12-4a0f-999f-a304205e0751)

**Comment by aaclan-ebi** [comment]
Updated the texts/messages in the submit, i realised they are badly composed. @clairerye @gabsie @mshadbolt @rays22 please also review the messages, Thanks!


![Screenshot 2020-06-18 at 09.40.06.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/7a3c19b2-c32b-40a8-864c-65a3f6f842a0)

**Comment by aaclan-ebi** [comment]
Applied the following changes based on Marion's feedback:

![Screenshot 2020-06-22 at 12.25.12.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/55ad6fe7-86ff-435e-a409-9210d9a1e056)

![Screenshot 2020-06-22 at 12.25.27.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/6f601d83-1874-4e16-b5bd-1342524e3361)

![Screenshot 2020-06-22 at 12.25.36.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/940b5414-93f2-446a-98ca-6575ef7ec77f)

![Screenshot 2020-06-22 at 12.26.02.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/2e40e2e8-879f-43f7-803a-e0968063261f)

![Screenshot 2020-06-22 at 12.26.17.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/f9f5a0ee-2cb0-491c-99fb-076e2a8042b8)

![Screenshot 2020-06-22 at 12.26.12.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/1a631eff-86f6-4112-bbf2-8650c195c42b)

![Screenshot 2020-06-22 at 12.26.22.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/c7ee4593-1ca9-4e5e-b4b8-1951f69db24f)

![Screenshot 2020-06-22 at 12.26.37.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/74554521-59db-49c2-8e60-58b022d48edc)

**Comment by aaclan-ebi** [comment]
Added a new tab to show accessions obtained from DSP

![Screenshot 2020-06-22 at 16.32.32.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/65ab7028-ae6c-4ffe-81c8-5bdd312deadb)

**Comment by aaclan-ebi** [comment]
Released in prod last 25th June.
Changelog: https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#25-june-2020
