### ISSUE TITLE
[Archiver] Set Archived State (Submission Flow Phase 1)

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#155]
As a contributor I want to know where my dataset is in the overall flow of archiving and exporting to DCP2.
[Design Document](https://docs.google.com/document/d/11NAxNDQ5m-32aEgDkvkwYPWd4pjexspbbncDtpdpjk4/edit#)

When the archiver is successfully run in _Complete Submission Mode_ (returning accessions from DSP), Archiver should set the state of the submissions in the **Archiving** state to be **Archived**.

Archiver is run for projects and not submissions so should possibly change the state for a project also.

**Comment by aaclan-ebi** [comment]
Released in prod last 25th June.
Changelog: https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#25-june-2020
