### ISSUE TITLE
Tag AWS EBI resources consistently

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#17]
We need to tag these consistently for management and cost purposes.

**Acceptance criteria**
* [x] We have decided on a tagging strategy
* [x] It's documented in [this doc](https://docs.google.com/document/d/1R2ZrMNbZ5TqJz7_DGiZgNPN2KF-dfsN9ETNq7ofX5_E/edit#heading=h.an4gsz11wtin)

**Comment by rdgoite** [comment]
Added notes in the document about AWS resource tags.
