### ISSUE TITLE
Update ingest-file-archiver to use other schemas

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-dev-team#171]
https://github.com/ebi-ait/ingest-file-archiver/blob/master/src/util/fastq-2-bam-converter.ts#L56

Right now 10xv2 schema is assumed.

This needs to be changed to accept the [10xV3](https://github.com/nunofonseca/fastq_utils/blob/master/sh/fastq2bam#L140) schema option that the fastq2bam tool offers.

This is a blocker to archive dataset https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/47 which uses 10x v3

Also this bit of code will need to be updated https://github.com/ebi-ait/ingest-archiver/blob/master/utils/protocols.py#L4 to recognise other ontologies (Currently only checking for `10x v2 sequencing` and `10x 3' v2 sequencing`

**Comment by aaclan-ebi** [comment]
Dev notes:

I think it'll be best to add the schema info in the file upload plan from the archiver. It's already checking checking if the experiment is 10x here https://github.com/ebi-ait/ingest-archiver/blob/master/utils/protocols.py#L4 when it generates the file upload plan.


the file archiver needs to be updated to source the schema information from the file upload plan https://github.com/ebi-ait/ingest-file-archiver/blob/master/src/util/fastq-2-bam-converter.ts#L63
