### ISSUE TITLE
Move the hca-wrangler-backup upload areas to hca-util-upload-area bucket

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#172]
Wrangler data files can be either in s3 bucket `hca-wrangler-backup` or `hca-util-upload-area`. They could use HCA CLI to sync files from a source bucket to the Ingest submission upload areas. However, currently it's possible to only configure 1 source bucket for syncing. 

A ticket to configure multiple sources was created before to https://app.zenhub.com/workspaces/ingest-dev-5cfe1cb26482e537cf35e8d1/issues/ebi-ait/hca-ebi-dev-team/88 

This ticket is an alternative solution to that. This will avoid reconfiguring the upload service deployment to allow syncing from a specific bucket.

Ideally the hca-util should support the uploading of files to the submission upload areas which i think will be covered in this epic https://app.zenhub.com/workspaces/ingest-dev-5cfe1cb26482e537cf35e8d1/issues/ebi-ait/hca-ebi-dev-team/162

**Comment by mshadbolt** [comment]
@aaclan-ebi is there an easy way to do this in an automated way or will it be a matter of someone manually creating new folders in the `hca-util` area then transferring each folder from the backup area across?

**Comment by aaclan-ebi** [comment]
I think we the can simply copy all the folders from hca-wrangler-backup to the hca-util-upload-area. Please make sure not to override the existing content of hca-util-upload-area (I doubt this will happen because we're using uuids as top directory name for the data files).

**Comment by aaclan-ebi** [comment]
I ran the ff aws s3 sync command in a screen instance in Wrangler EC2

```
aws s3 sync s3://hca-wrangler-backup s3://hca-util-upload-area/hca-wrangler-backup
```

Process is still running, I will monitor.

**Comment by aaclan-ebi** [comment]
The sync is taking too long. After 18 hours only 4 of 22 directories are synced. I cancelled the process, and used the util script to do multithreading, https://github.com/ebi-ait/hca-ebi-dev-team/blob/master/scripts/hca-s3-sync/hca-s3-sync.py

Process is ongoing.

**Comment by aaclan-ebi** [comment]
@prabh-t i just got curious if i move the parent directory `hca-wrangler-backup` inside the s3://hca-util-upload-area, does it mean any users  will be able to select and see hca-wrangler-backup content?

If yes, i might have to move the subdirectories one level up. I'll perform that after the syncing is finished.

**Comment by prabh-t** [comment]
in principle i think it should be ok, though i'd be careful to manually copy into the bucket as upload areas and permissions assignment etc is done via the tool. I'd suggest that you create a new upload area using the `create` command. you can name it `hca-wrangler-backup` and give the perms it needs to have, then copy over the data in that area. I think there may be some logic around expecting top-level 'folders'/upload areas to be in the uuid format, so having other folder names may cause issues.

**Comment by aaclan-ebi** [comment]
Thanks @prabhat! I created a new upload area using hca-util and copied the data there.

Copying is done. The hca-wrangler-backup files are now inside hca-util-upload-area bucket. Marking this ticket as done.

![Screenshot 2020-07-14 at 09.51.34.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/80e30fb6-af53-4d61-9d53-5fc288bdd000)

**Comment by mshadbolt** [comment]
would you be able to document how wranglers can access these and move files around? I don't think hca-util has the functionality to access subfolders within a folder?

**Comment by aaclan-ebi** [comment]
Hi @mshadbolt how were you able to access the _hca-wrangler-backup_ files before? If you're doing it via aws cli in Wrangler EC2, i believe you can still use it for all directories and files inside s3://hca-util-upload-area/9b13cb1e-f4f4-44c2-967f-a888017d18a6/

**Comment by mshadbolt** [comment]
ok, is isn't it a bit of a security risk to be publishing the uuids above publicly?

**Comment by aaclan-ebi** [comment]
Removed.

**Comment by prabh-t** [comment]
@aaclan-ebi I don't think it's a good idea to ask wranglers to start manipulating upload areas and containing objects (and sub-directories) directly with the aws cli. The bucket was meant to be used and managed exclusively by the tool unless we're very careful otherwise we may run in all sort of issues. Also in answer to your slack comment on sub-directories, the tool does not expect to find sub-directories as it's disabled, thus is not viewing them as such but as objects. I can't be entirely sure this will not entail unexpected behaviour, so i'd strongly suggest to remove the dir hierarchy.

**Comment by prabh-t** [comment]
moving this back to review but please move back to done you disagree and/or have done appropriate tests to ensure this is not an issue.

**Comment by aaclan-ebi** [comment]
My recommendation only applies for manipulating files inside the `hca-wrangler-backup` directory. The files were moved to hca-util-upload-area is just a way for the wranglers to readily sync the data to the submission upload areas.

Do you have any recommendation how the wranglers would access the files ?

**Comment by aaclan-ebi** [comment]
>  I can't be entirely sure this will not entail unexpected behaviour, so i'd strongly suggest to remove the dir hierarchy.

@prabh-t could you elaborate on this?

Do you mean  structuring `s3://hca-util-upload-areas/hca-wrangler-backup/<dummy-uuid>/files*` to be 
`s3://hca-util-upload-areas/<dummy-uuid>/files*` ?

**Comment by aaclan-ebi** [comment]
@prabh-t Can i simply sync the dummy uuid directories to the s3://hca-util-upload-area ? do you think this would cause issues? or do I have to create new uuid directories via hca-util tool and then sync the files to those new directories?

**Comment by aaclan-ebi** [comment]
Hmm, i think i'll just go with creating new directories and the sync the files there.

After this, it looks like it's now possible via hca-util tool to do sync to submission upload areas.

**Comment by prabh-t** [comment]
Hi @aaclan-ebi sorry couldn't respond earlier I was away. Ok, i was just checking this and found 2 issues. Firstly, listing the upload areas is now returning an exception because manually created areas will not have the tagging (prev metadata) set. As this was expected the code omits a check there. Good idea I include a check now.
```
$ hca-util list -b
An exception of type NoSuchKey occurred in command list.
Detail: An error occurred (NoSuchKey) when calling the GetObjectTagging operation: The specified key does not exist.
```
Secondly, one of the manually created areas can't be selected. I'm not sure why.
```
$ hca-util select 9296c147-72e7-4100-a19a-51bf01314a13/
Upload area does not exist
```
I'd avoid manual manipulation on the bucket incl. creating upload areas outside the hca-util. The tool dynamically updates policies/tagging/metadata/etc and with manual intervention, we may be skipping some steps. Best we talk through this tomorrow on a call or slack chat.

**Comment by aaclan-ebi** [comment]
I see. Apologies for this. I'll try to revert everything i did and see if the issues are still there. 

Just to note the things i did, I created an upload area using hca-util. But i did an aws cli sync to transfer the files to the bucket. I think there's no way to sync buckets to hca-util. Is there other way to do this? Yes, i'll set up a call.

**Comment by aaclan-ebi** [comment]
Had a call with @prabh-t to discuss the issues and we came up with ff plan:
1. Create upload areas via hca-util for each dummy uuid directories in s3://hca-wrangler-backup/ 
2. Ask wranglers how to name those dummy uuid directories
3. Sync the files to each upload areas via (aws cli sync)
There's an issue that the files may not be assigned with correct content-type and when synced to the submission upload area , it will not notify the Ingest upload service. The hca (dcp) cli can be used temporarily but ideally it should be handled in the hca-util tool as well (to be discussed later).
4. Confirm with wranglers who has created the upload area s3://hca-util-upload-area/9296c147-72e7-4100-a19a-51bf01314a13

Thanks so much @prabh-t for the guidance!

**Comment by aaclan-ebi** [comment]
@ebi-ait/hca-wranglers I would like to ask for your help to assign names on the following hca-wrangler-backup directories . I will transfer these directories to the hca-util-upload area so it would be nice if you can suggest descriptive upload area names (e.g dataset name) than these dummy uuids https://docs.google.com/spreadsheets/d/10_e16kOmdJdpBlz5Gg4zqKOkV9zWAuy6V7_RPH0nG9c/edit#gid=0 (edited)

**Comment by aaclan-ebi** [comment]
@mshadbolt referred me to some files on slack where i can extract the names https://embl-ebi-ait.slack.com/archives/C014HMTV0FN/p1594999565039000?thread_ts=1594998948.038800&cid=C014HMTV0FN

**Comment by aaclan-ebi** [comment]
All files are now moved.

https://docs.google.com/spreadsheets/d/1WvS82XnALTWStvUocnHcQ747l2VXroqaX81S01LbjGU/edit#gid=0 (Access is restricted to the current wranglers)
