### ISSUE TITLE
Fix CI workflow on Github

### ISSUE THREAD

**Issue by rdgoite** [ebi-ait/hca-ebi-dev-team#173]
Verification step is failing when Github automatically runs the CI workflow. In particular, the `unknownGuest` test in the `AuthenticationControllerTest` is failing with `ClassCastException`.

This only seems to occur when running the test suite on Ubuntu.

**Comment by aaclan-ebi** [comment]
Released in prod last 25th June.
Changelog: https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#25-june-2020
