### ISSUE TITLE
[Ingest-UI] Contributor Project Registration form, also containing key info needed by Wranglers.

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#181]
## User story
As a contributor I want to submit project details so that I can initiate the submission process.
As a wrangler I want all contributor project information to be in ingest from the start of the wrangling process.

## Purpose
Allow contributors to create a project, while providing:
a) The minimum of information necessary
b) The information needed for the wranglers to prioritise the work by collecting the information usually collected by the HCA contact form.
[Design Mockup](https://chanzuckerberg.invisionapp.com/share/DMWL3W8FG42#/screens/422749376)

## Acceptance Criteria
 - [ ] When a contributor clicks a new project button, the page they are taken to matches the designs and purpose above.
 - [ ] When a wrangler clicks a new project button, they are taken to a page matching the existing new-project form.
 - [ ] The information collected by this simpler form is used to create a "project document" in the current schema
    - [ ] This project document should appear in the contributor's "My Project Page"
    - [ ] This project document should be editable by the contributor & wranglers using the existing form.
- [ ] The contributor's contact info from their user account should be added as the "corresponding contributor" in the "contacts" project element.

**Comment by gabsie** [comment]
Hi, everyone
I think I am happy now with the organisation and the fields.
It would be nice if the wranglers and Claire review the suggested tabs and fields. I have revised and addressed some usability issues from before, which I can speak to somebody doing the frontend to (selecting the multiple options, e.g.)
Please ask me questions. All the screens are here attached as well

![7 3 3 Contribute My Projects  - Contacts](https://user-images.githubusercontent.com/19713125/85837285-c2862900-b78f-11ea-97dd-44a3bc720804.png)
![7 3 3 Contribute My Projects  - Data summary](https://user-images.githubusercontent.com/19713125/85837303-c619b000-b78f-11ea-9779-8321bd5607b4.png)
![7 3 3 Contribute My Projects  - New project Copy](https://user-images.githubusercontent.com/19713125/85837304-c6b24680-b78f-11ea-82a2-2019f01a50bd.png)

**Comment by clairerye** [comment]
@aaclan-ebi. @ami-day and @gabsie just to confirm. As discussed in slack (https://embl-ebi-ait.slack.com/archives/C0103DEJ82C/p1593788788160900)
We will make the following changes to the above designs.
 - Change the copy of the data consent question to `Do the data or metadata for this project require any sort of controlled access?`

 - Change the date for release to be a required field and ensure the copy reflects this can be updated as required. suggested copy `Enter the date you would like the data and metadata for this project to be publicly released. At this stage, this date is indicative only, you will be able to change this and also be asked to confirm this before submission.`

**Comment by aaclan-ebi** [comment]
Hi, I'm on holiday today but changes are deployed in dev and can be tested. 

https://ui.ingest.dev.archive.data.humancellatlas.org/projects/new

@ami-day, it would be nice if you can test the changes!

Thanks
Alegria

**Comment by ami-day** [comment]
Yea @ESapenaVentura has been doing some testing and I plan to look through your changes to the code today.
Have a nice holiday :)

**Comment by ESapenaVentura** [comment]
@aaclan-ebi I have tested the changes. Overall is looking really good but I have found a couple of things:

**BUGS**:
- Clicking on next after filling the main "project" tab doesn’t take you to the “contacts” tab: it just tells you the form is invalid without showing any error on the project page
- After finishing the project, the contributor can still click on "edit" or "view" (Clicking the name) and they will be shown the whole project registration form. I thought we were moving away from showing it to the contributor for now?

**Validation errors**:
- "Technology" field should not be required if "other technologies" is filled.

**Aesthetic/User-pleasing changes** (@gabsie might want to correct me on these ones):
- When validating the errors clicking "Next", something should happen. Current behaviour is it just validates and stays on the same page if there are validation errors.
   - Maybe we can force the view to go to the top of the page, and inside the big red error box we can have clickable objects called "Error 1", "Error 2", etc that a contributor could click on to go to the field causing trouble?
- Errors should be more noticeable. Currently it is a little red text stating the error under the field description. In the mock-up, the border of the textbox was red, which is way more noticeable when scrolling.
- The overall error message still doesn't look completely user-friendly to me. It currently states `Please resolve the form validation errors first before proceeding.`. I think something like `Please fill in the required fields before registering your project:` (Coupled with my suggestion before of adding "links" to the errors) or `Please fill in the required fields before finishing project registration.`

I have been testing around and I have found this. Happy to hear if anyone else finds something else!

**Comment by aaclan-ebi** [comment]
Thanks Enrique for the very helpful feedback.

I have some more changes for this ticket to address the comments and I'll push and deploy those today.

**Comment by aaclan-ebi** [comment]
Changes were released to production last 15th Jul.
https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#15-july-2020
