### ISSUE TITLE
[Ingest UI] Landing Page

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#182]
## User Story
As a contributor, I expect to go to a webpage of the HCA, where I can read instructions on how to do my data submission to HCA. I expect to start this process by signing up and starting the process by giving details about my project.

## Purpose
Members of the public that visit https://ui.ingest.archive.data.humancellatlas.org/ are greeted with a landing page that matches the [design mockup](https://chanzuckerberg.invisionapp.com/share/DMWL3W8FG42#/screens/422749374).

Acceptance Criteria
 - [ ] Users visiting https://ui.ingest.archive.data.humancellatlas.org/ are no longer redirected to https://ui.ingest.archive.data.humancellatlas.org/login
 - [ ] The should be greeted instead by a page following this [design mockup](https://chanzuckerberg.invisionapp.com/share/DMWL3W8FG42#/screens/422749374)

Also an attachment here:
![7 3 1 Contribute My Projects not logged in](https://user-images.githubusercontent.com/19713125/85686113-9606da00-b6c7-11ea-9991-89760a961775.png)

**Comment by MightyAx** [comment]
@gabsie  Is there any way of getting the html source for these mockups designs?
Would be useful to have the layout and images rather than having to make them from scratch, and even having access to the fonts and sizes you have chosen.

**Comment by aaclan-ebi** [comment]
Changes were released to production last 15th July.
https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#15-july-2020
