### ISSUE TITLE
[Ingest UI] Design Changes for My Projects (Contributors) 

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-dev-team#183]
## User Story
As a contributor I want to have a summary page showing all the projects I have registered.

## Purpose
Allow contributors to see appropriate summary information in the My Projects table.

## Acceptance Criteria
 - [x] Remove Contributor and Status column
- [x] Remove Ingest UI link for contributors
- [x] Use the [visual framework Table styling](https://visual-framework.github.io/vf-core/components/detail/vf-table.html)
- [x] View / Edit of the "pre-project" is not available until a wrangler is assigned, at which point edits are available again on the full project form.
    - [x] Actions column displays Under Review until a wrangler is assigned
    - [x] After that the action column displays a "view" link.

**Changes to Project View**
- [ ] viewing project displays available actions at the top of the page
    - [ ] then validation error messages
    - [ ] then the view mode of the project
    - [ ] then the submissions.

**Comment by gabsie** [comment]
hey, everyone

I am suggesting this update on the Contributor dashboard.
The changes are:

- no search required for a contributor
- some formatting issues following the beta of the tables in the VF
- HCA project ids instead of Short names (I know this is still probably not possible, but as you know, I design this with the idea variant)

I am ready to discuss, so that we decide whether Edit is relevant for now. 

I will also upload the Wrangler dashboard so that we can compare why different versions will be required for these dashboards.

![7 3 3 Contribute My Projects - contributor dashboard](https://user-images.githubusercontent.com/19713125/86253683-c6111a00-bbac-11ea-8dae-e28e99a32f1e.png)

**Comment by clairerye** [comment]
Dashboard - Can we discuss PubMed IDs and accessions as well - putting this here as a reminder

**Comment by MightyAx** [comment]
Decisions from this morning's Design Meeting:
- Ingest UI link should only be on wranglers view (My Projects / All Projects)
- My Projects (Contributor) should not have the contributor column:
- Use the [visual framework Table styling](https://visual-framework.github.io/vf-core/components/detail/vf-table.html)
- View / Edit of the "pre-project" is not available until a wrangler is assigned, at which point edits are available again on the full project form.
- Short Name (HCA Project ID) should auto generate to: Organ-Technology-ContributrorName-01
- While waiting for wrangler assignment the project status should be under review,
    - Other changes to project status need some thought and will probably be a ticket for next sprint.
- No edit link, just link to view
- viewing project displays available actions at the top of the page
    - then validation error messages
    - then the view mode of the project
    - then the submissions.

**Comment by gabsie** [comment]
I AM UPDATING WITH the 'Under review' screen
![7 3 3 Contribute My Projects - contributor dashboard](https://user-images.githubusercontent.com/19713125/86351513-45115b80-bc5c-11ea-998e-f4856f1adfd8.png)

**Comment by MightyAx** [comment]
remove"Short Name (HCA Project ID) should auto generate to: Organ-Technology-ContributrorName-01" since it is being solved elsewhere.

**Comment by clairerye** [comment]
We don't capture `organ` - option to ask for the organ - this may be complicated in certain situations like developmental or immune projects. Can we get away with just technology and name? Or could add species too - although most will be `human` so is there much value in including it? @gabsie did you have any thoughts on this?

**Comment by lauraclarke** [comment]
You could make it organ or system?

**Comment by MightyAx** [comment]
Auto filling the short name is now part of ticket [#181](https://github.com/ebi-ait/hca-ebi-dev-team/issues/181) and implemented in [Ingest-UI PR#18](https://github.com/ebi-ait/ingest-ui/pull/18)
It's live on [dev](https://ui.ingest.dev.archive.data.humancellatlas.org) if you want to see how it works.

**Comment by aaclan-ebi** [comment]
Changes were released to production last 15th July.
https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#15-july-2020
