### ISSUE TITLE
Review and update SOP for giving contributor keys and UUID

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-dev-team#191]
## Purpose
Review the current SOP for giving contributors access keys for the hca-util and UUID for the upload area so they can contribute data to the DCP. 

Current SOP: https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/contributor_dataset_SOP.html#raw-data-upload-fastq

Propose changes as required to minimise the risk of exposure while bearing mind the ease and convenience of the current system to the contributor. If we choose to keep the current SOP, that may be ok, but I want that decision to be made having decided that the level of risk is acceptable.

## Acceptance Criteria
 - [ ] A brief written proposal outlining 3 possible solutions for how we transmit keys and UUID's to contributors.
- [ ] Pros and Cons of each of the possible solutions
- [ ] Favoured solution clearly highlighted
- [ ] Circulated to the team for comments and feedback
- [ ] final decision on new SOP
- [ ] SOP documentation updated to reflect any new processes

**Comment by clairerye** [comment]
sorry, I might have put this in the wrong repo!

**Comment by lauraclarke** [comment]
Issue moved to [ebi-ait/hca-ebi-wrangler-central #78](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/78) via [**ZenHub**](https://www.zenhub.com/)
