### ISSUE TITLE
[Ingest UI] Preserve user's original destination after login

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#195]
## User Story
As an existing ingest user, that is not signed in and has clicked a link to a specific project, or has a page in ingest bookmarked. After I have finished the login process, I expect to be taken to the project in link I clicked, or had bookmarked.

## Purpose
Preserve the original destination of a user that must sign in to see that page.

## Acceptance Criteria
 - [ ] If the login page is invoked because the user must be signed in to see the intended page, the user is navigated to the intended page after login is complete.
 - [ ] If the login page is invoked manually (without a destination) the user is navigated home.

## Stretch Criteria
 - [ ] If registration is required during the login, the user is *still* navigated to their original destination once registration in complete.

**Comment by aaclan-ebi** [comment]
Changes were released to production last 15th July.
https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#15-july-2020
