### ISSUE TITLE
See if DSP could handle HCA ingest directly

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#2]
See [doc](https://docs.google.com/document/d/14hoBSFwNEh4mYrlP8VfpU2sz4k6CxmsJVeA1IYpGwno/edit?folder=16H9fUJ9koNeBAyXRi8SL7BYKEc1bBjFV#heading=h.vvcgesahtbg)

**Comment by MightyAx** [comment]
https://docs.google.com/document/d/14hoBSFwNEh4mYrlP8VfpU2sz4k6CxmsJVeA1IYpGwno/edit?folder=16H9fUJ9koNeBAyXRi8SL7BYKEc1bBjFV#

**Comment by MightyAx** [comment]
Possible Further Actions (subject to talking with Tony):
- Ask TSC if any other large file upload technologies have become supported in the meantime?
- Could resume talks with TSC about including tus.io into unlimited upload area?

For further discussion (at later date):
- What are the differences in Data Model and Validation between DSP and HCA
  - For validation this question might be more ENA v HCA.
- How could the DSP or ENA use the MetaData Schema?

**Comment by mcourtot** [comment]
FYI DSP is switching to FTP + Aspera - we asked TSC about tus again recently and were told no/never.

@haseeb-gh investigated this and wrote a summary.

**Comment by justincc** [comment]
Thanks @mcourtot. Hey @haseeb-gh, could you like your summary?

**Comment by haseeb-gh** [comment]
@justincc please find it here:
https://docs.google.com/document/d/1MPoA0OlsF58oOZsW-OeMOdhr-VrA9VdA/
