### ISSUE TITLE
Bug - remove the restriction on allowing only EBI Elixir accounts to login to the UI

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-dev-team#202]
Following the slack conversation here: https://embl-ebi-ait.slack.com/archives/C0103DEJ82C/p1593763163110000

@aaclan-ebi checked the code and confirmed that core still checking the ebi email. So currently no one outside of EBI can log in to the UI. This restriction needs to be removed.

**Comment by aaclan-ebi** [comment]
Changes were released to production last 15th July.
https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#15-july-2020
