### ISSUE TITLE
Archive meta/data to EBI databases in a manner specified by the wranglers

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#21]
Since we are no longer going to add data to the DataStore:
[Design document](https://docs.google.com/document/d/1h3eP3eYF1BBJLq09o6OZAxUmUnZotcXuBgGvcAGojtY/edit)

**Comment by MightyAx** [comment]
Mapping Document: [Mapping HCA Data to EBI Archive](https://docs.google.com/document/d/1DvF0S9rL0IxnMdsi9P3qUVRt-IOT25KWqjwwIU7C9_s)

**Comment by justincc** [comment]
Closed as duplicates https://app.zenhub.com/workspaces/ingest-dev-5cfe1cb26482e537cf35e8d1/issues/ebi-ait/hca-ebi-user-value/1
