### ISSUE TITLE
Unpublish project 15.0.0 schema

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-dev-team#217]
We recently rolled back the project 15.0.0 schema in develop to version 14.1.0 to be consistent with the rest of the environments.

The 15.0.0 was not published to any other environments only develop.

This ticket is to delete https://schema.dev.archive.data.humancellatlas.org/type/project/15.0.0/project so that it is not used for validation.

@aaclan-ebi said this should be relatively simple to do by deleting from the s3 bucket.

**Comment by aaclan-ebi** [comment]
Removed the project v15.0.0 json file from the bucket and removed the schema entry in the ingest database.

The latest schemas endpoint now returns 14.1.0 https://api.ingest.dev.archive.data.humancellatlas.org/schemas/search/latestSchemas?size=200

**Comment by aaclan-ebi** [comment]
Notes on Manual Steps for Unpublishing schemas:
1. Remove the schema from the schema bucket `schema.dev.archive.data.humancellatlas.org`
2. Delete the schema entry from Ingest database 
```
db.schema.deleteOne({"highLevelEntity": "type", "domainEntity": "project", "schemaVersion": "15.0.0"});
```

**Comment by aaclan-ebi** [comment]
Hi @mshadbolt,

Would you be able to update the test spreadsheet in dev? The integration test is failing due to project metadata errors.

 ```
* should match pattern "^[D|E|S]RP[0-9]+$" at .insdc_project_accessions[0]
* should match pattern "^PRJ[E|N|D][a-zA-Z][0-9]+$" at .insdc_study_accessions[0]
```

Thanks!

**Comment by mshadbolt** [comment]
Hi Alegria, I think I fixed it, I believe it was just the SS2 spreadsheet that had the issue, are you able to check?

**Comment by aaclan-ebi** [comment]
Thanks @mshadbolt ! Ingest Integration test in dev is now passing! :)

**Comment by lauraclarke** [comment]
@aaclan-ebi Can this now be closed?

**Comment by aaclan-ebi** [comment]
yup, closing now.
