### ISSUE TITLE
ontology.staging.data.humancellatlas.org OLS server maintenance and updates

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-dev-team#220]
<http://ontology.staging.data.humancellatlas.org/> is needed to be updated regularly to the latest versions of ontologies used by the HCA. <https://github.com/HumanCellAtlas/ontology> 

The SPOT team needs a dev as a point of contact to coordinate updates. They can provide more information on the update process.

**Comment by lauraclarke** [comment]
Can we use the main OLS server?

**Comment by rays22** [comment]
Would you like me to ask them or our devs about that?

**Comment by lauraclarke** [comment]
@rolando-ebi @aaclan-ebi @rdgoite can you remember why we decided to use our own OLS instance rather than using the main OLS release directly?

**Comment by aaclan-ebi** [comment]
Did some digging and got this statement from Simon Jupp: https://humancellatlas.slack.com/archives/C49TW3RV5/p1574847551245100?thread_ts=1574845997.244900&cid=C49TW3RV5

**Comment by lauraclarke** [comment]
Thanks @aaclan-ebi I think we have crossed wires here

This isn't about the HCA application ontology

But instead as why we host our own version of OLS http://ontology.staging.data.humancellatlas.org/index
rather than using https://www.ebi.ac.uk/ols/index

**Comment by rolando-ebi** [comment]
IIRC, this was because the HCA ontology development required frequent integration with our systems and so need to be released at a different cadence to the main OLS

**Comment by lauraclarke** [comment]
Is that still the case though?

Does it need more work than configuration changes for us to point to the main version of OLS?

**Comment by lauraclarke** [comment]
@clairerye It looks like we might be able to move straight to standard OLS branch, it would be good to understand when that could be scheduled so we know if we need to coordinate the updates of http://ontology.staging.data.humancellatlas.org/ in the meantime or not
