### ISSUE TITLE
testing of the updated hca-util

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-dev-team#235]
The hca-util has been updated to include the s3 to s3 transfer #82 to allow the one tool to be used to create user upload areas and also transfer data files from those upload areas to ingest upload area. 
This new functionality, alongside the previous functionality should be tested to check it works as expected and to check the documentation is correct or update as necessary.
Documentation:
https://github.com/ebi-ait/hca-documentation/wiki/How-to-administrate-upload-areas-using-hca-util
https://github.com/ebi-ait/hca-documentation/wiki/How-to-upload-data-to-an-upload-area-using-hca-util
Suggested test flow:
 - [x] update pypi package
 - [x] Create an upload area (as a wrangler)
 - [x] Upload test data into the upload area (as a contributor)
 - [x] Create a test submission in ingest in order to create the ingest upload area - is this correct?
 - [x] Transfer test data from the contributor upload area to the ingest upload area
 - [x] Check the transfer was completed.
Please log any errors here and update the documentation as required.

**Comment by clairerye** [comment]
@prabh-t is working bug #233, then this testing can start

**Comment by ami-day** [comment]
I'm closing this issue now as is it complete
