### ISSUE TITLE
Set Expiration Policy on ingest backups

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#241]
Expire all backups after a certain timeframe:
- [x] Set Expiration policy of 90 days on any file created in the was bucket ingest-db-backup

Allow some backups to persist if selected by the operations team:
- [x] Modify the [ingest-backup code](https://github.com/ebi-ait/ingest-kube-deployment/tree/master/infra/helm-charts/mongo/charts/ingestbackup) to tag new backups with `"auto-delete": "true"`
- [x] Have the expiration policy only apply to files with the tag `"auto-delete": "true"`

**Comment by aaclan-ebi** [comment]
Moving back to product backlog for now.

**Comment by lauraclarke** [comment]
@prabh-t do you have a concept of how much time this would take? I am trying to decide when we might be able to complete it?

**Comment by MightyAx** [comment]
@prabh-t Happy to chat if my above notes don't make sense.

**Comment by prabh-t** [comment]
@lauraclarke I am not hundred percent sure how the backups currently work, but if they are stored in an S3 bucket then it might be just a configuration that is needed in the S3 management console to add an expiration policy to delete any file that is older than 90 days. However, from @MightyAx 's comment it seems we also want to be able to not allow certain backups to expire. I am not sure how we go about doing this if backup is an automated process that runs every night.

**Comment by lauraclarke** [comment]
So I think automatically saving backups is a nice to have rather than an essential feature. 

Do you know how to setup backup expiration in the current system? This will impact the data retraction SOP as if we have automatically expiration of backups, we can explain this in the SOP rather than having to specifically going to find backups that need deletion. 

There are likely other non-automated alternatives like creating dumps/doing a specific backup for versions we want to save, leaving this automated process to just do things on a schedule, but this is a feature request we should give to Claire so it can be prioritized

**Comment by prabh-t** [comment]
Yes, I am setting up the backup expiration policy in S3 with the rule "delete after 90 days"? This will apply to all previous backups. Can you confirm I can go ahead and enable this?

**Comment by lauraclarke** [comment]
Please post on the Operations channel to see if anyone has any comment but if no one objects, I would do it tomorrow?

I can't see why this is a problem

**Comment by prabh-t** [comment]
Lifecycle rule now set up in S3 - transition backup objects to Intelligent-Tiering after 0 day i.e. default storage class is Intelligent-Tiering (incurring less cost than Standard storage class), then expire (permanently delete) backup objects after 90 days.

**Comment by lauraclarke** [comment]
fantastic, are there any semi-regular checks we need to put in place for this to check backups are happening and ones which are too old are getting deleted? say monthly review or something?

**Comment by prabh-t** [comment]
Yes, i think it makes sense for this to be the responsibility of the dev on ops to carry out at some point during a sprint, so the check happens at least every fortnight. The backup document is [here](https://github.com/ebi-ait/ingest-kube-deployment/tree/master/infra/helm-charts/mongo/charts/ingestbackup).

**Comment by MightyAx** [comment]
@prabh-t What's the way to exempt a backup from this rule?
I definitely think it would be a good idea to keep one of the backups from before the project purge (approx July 11th 2020)

**Comment by lauraclarke** [comment]
Is it possible to take adhoc copies rather than automating it?

**Comment by MightyAx** [comment]
@lauraclarke Sure, but I think that what @prabh-t is saying above is that if I change the storage class of a file I can keep it in place. Just checking for the exact procedure.

**Comment by lauraclarke** [comment]
If by changing the storage class of a file you make it cost more money that might not be the best approach though? Is there a way not to make the storage cost more but move/copy it to somewhere it doesn't get auto-deleted?

Also, July 11th is more than 90days since have we already lost that opportunity?

**Comment by prabh-t** [comment]
@MightyAx the procedure to persist any backup that want to keep after the 90 days is implemented as you describe in the ticket. So the user will have to manually change the default `"auto-delete": "true"` tag to `"auto-delete": "false"`.
@laura the policy is in place already, but I do not see files older than 90 days deleted yet. It may be first deleted 90 days from when the lifecycle rule is set up.

**Comment by prabh-t** [comment]
deploying this change/relaunching the backup cron is blocked because of missing details about the role_arn and slack_webhook. These are not in aws secrets.

**Comment by lauraclarke** [comment]
@prabh-t do we need a task to cleanup most of the backups that are older than when the flag was switched on? Say keep the one from July 10th 2020, 

@MightyAx are there any others pre this flag being switched on which should be preserved?

**Comment by MightyAx** [comment]
I've marked a July 11th update as `auto-delete: false`.
There's no other backup I think we should be keeping.

Thanks @prabh-t!

**Comment by prabh-t** [comment]
Thanks @MightyAx. @lauraclarke I have commented on the new ticket. I have manually cleared the older files for now, which would normally have happened after redeployment of the changes I've made to add the "auto-delete: true" tag to backup files.

**Comment by lauraclarke** [comment]
Can this be moved to done? is anything else needed?

**Comment by prabh-t** [comment]
The update to the backup script haven't been deployed yet (because of some missing info), so new backups will not be marked with "auto-delete: true" and will not be automatically cleared. 
Again need more time to change the deployment script to use different set of parameters.

**Comment by clairerye** [comment]
Moved to product dev https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/229
