### ISSUE TITLE
Manual cleanup of upload areas for deleted submissions

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#242]
Review upload area's in the org-hca-data-archive-upload-prod s3 bucket.

Ensure any upload area that exists for a deleted submission is removed.

**Comment by rdgoite** [comment]
Here's the list of open upload areas (i.e. existent in the prod bucket) that are **not** linked to any submission in the database:

```
be85bea2-e829-43ba-a4e5-35def4a826ea
dae7e367-35e4-46ef-87dc-87abb4eda0a9
c120d5fe-f4ee-433d-b176-e1e0905c8f5f
85196817-5785-40a3-b1d7-dd6980611bd2
b8a76a08-c9e9-4c30-9bef-43cbb3b51287
961412fc-eb29-4c35-a070-e4b24182d7a8
4a6fdc43-24e3-444f-8858-53c652190e4d
53f376be-5905-4067-8b06-6a4cc6756e2d
d2395f7a-4a35-4fd7-a54c-dd361e62295a
e897a3e8-b9fa-42c7-9762-3b7ecd9a862a
93bb5fd4-a332-4bf7-a22c-aed632d0de1b
7fe5ba5c-146c-4798-b680-3ac85fd46a17
3f1da893-12a3-4dab-9b4f-054683f66654
09fe4380-6440-4550-a8b6-88ef12d2b964
c1b9b409-3999-41db-968b-59b7b253cac0
23a9bb75-6005-4fc0-a6a2-cb15ba8b1381
fd57059f-2656-4e2a-8d5f-c5ec03d68922
fd1c9837-96bf-407d-be77-ecfd01b364bd
4d889301-241f-49f0-a165-4e33d20cd7e5
```

I'm not sure how to further verify that they are safe to delete, however. If anyone wants to inspect the contents of each of these, please let me know. Otherwise, I'll proceed with the deletion.

**Comment by lauraclarke** [comment]
@rdgoite did you produce a list of what files are in these directories?

**Comment by ESapenaVentura** [comment]
List of all the files by folder UUID

[https://app.zenhub.com/files/232300832/18f42ace-f422-44cf-9f1a-87305442d9bd/download](https://app.zenhub.com/files/232300832/18f42ace-f422-44cf-9f1a-87305442d9bd/download)

**Comment by lauraclarke** [comment]
@mshadbolt @ami-day @rays22 could you quickly eyeball the list and give the message a thumbs up if you aren't concerned by the cleanup

**Comment by ami-day** [comment]
> @mshadbolt @ami-day @rays22 could you quickly eyeball the list and give the message a thumbs up if you aren't concerned by the cleanup
> 
> no meticulous checking is needed, literally just a scan to see if you recognise anything and it triggers alarm bells to if it has or hasn’t already been ingested. If you don't recognise anything or anything you recognise is also somewhere all, we are all good

These are all ok with me.

**Comment by rolando-ebi** [comment]
Thanks guys.

Since there are no upload areas we want to keep, I'm going to delete all of the upload areas by the end of day today

**Comment by rolando-ebi** [comment]
Complete
