### ISSUE TITLE
Clean up EC2

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-dev-team#246]
The EC2 recently ran out of space. 

Particularly we need to figure out whether we need to keep the large amount of data in the `/data` folder

Some may be ok to delete if we have another copy elsewhere whereas some will need to be moved to s3 storage.

**Comment by lauraclarke** [comment]
I have a question, is this an EBI hosted EC2 bucket so we can delete the CZI ones with impunity?

**Comment by mshadbolt** [comment]
yes this belongs to EBI, but it is more like a virtual machine than a bucket. I believe we just took a carbon copy of the old CZI managed one which is why we ended up with the czi and ucsc folders in there.

I don't see why we can't delete things. pshah used to manage certain things from the ec2, so might be worth checking what is in there.

**Comment by MightyAx** [comment]
I've removed all files in `/home/alexie`

**Comment by rdgoite** [comment]
If we're sure that the directories named after people from outside EBI have not been touched by anyone else, then that means we still have an exact copy of the files under the CZI AWS instance. Those should be safe to delete.

**Comment by mshadbolt** [comment]
I thought the czi aws instance didn't exist anymore and that's why we transitioned to using ours?

**Comment by rdgoite** [comment]
@MightyAx can you confirm if that's the case here. If so, then yeah, we might need some other way to back up the data.

**Comment by aaclan-ebi** [comment]
I'll cleanup my directory.

**Comment by aaclan-ebi** [comment]
I think it's safe to delete the other user areas, they might not be even aware that it's copied to our instance.

**Comment by MightyAx** [comment]
> we still have an exact copy of the files under the CZI AWS instance.
I can confirm that this EC2 is an exact copt of the HCA wrangling EC2, which is why it contains files from people who don't work at EBI, which are safe to delete.

**Comment by ESapenaVentura** [comment]
`/data/` areas that we should consider clean-up:

```
138.885GB	/data/zperova-fetal-heart-10x-staging-0
135.31GB	/data/mshadbolt-LaurentiSpleenBMHSPCs-staging-0
13.6106GB	/data/pnejad-peer-staging-0
1.48239GB	/data/marcus_test
0.0532112GB	/data/cvillarreal-tabulamuris-staging-1
612.014GB	/data/cvillarreal-Levitin-Tcell-0
27.5538GB	/data/zperova-fetal-heart-iss-staging-0/ISS_h_heart_04/main_files
27.5539GB	/data/zperova-fetal-heart-iss-staging-0/ISS_h_heart_04
18.0412GB	/data/zperova-fetal-heart-iss-staging-0/ISS_h_heart_02/main_files
18.0413GB	/data/zperova-fetal-heart-iss-staging-0/ISS_h_heart_02
14.7614GB	/data/zperova-fetal-heart-iss-staging-0/ISS_h_heart_03/main_files
14.7616GB	/data/zperova-fetal-heart-iss-staging-0/ISS_h_heart_03
10.4967GB	/data/zperova-fetal-heart-iss-staging-0/ISS_h_heart_01/main_files
10.4968GB	/data/zperova-fetal-heart-iss-staging-0/ISS_h_heart_01
101.197GB	/data/zperova-fetal-heart-iss-staging-0
98.8111GB	/data/rstefancsik-HumanHematopoieticProfiling-staging-0
```

There are many others but I deemed non-important areas < 7000 bytes

**Comment by lauraclarke** [comment]
I think the 600GB T cell one is https://data.humancellatlas.org/explore/projects/4a95101c-9ffc-4f30-a809-f04518a23803 so that can be deleted asap and gives us a lot of the space back

We need to check with @zperova if the iss data is anywhere else

**Comment by rolando-ebi** [comment]
I need a definitive answer to the following questions before I can proceed:

- Which folders can be deleted 
- Which folders can be backed up, if any
- For the folders that should be backed up, where should they go

**Comment by rays22** [comment]
I have deleted
```
99G	/data/rstefancsik-HumanHematopoieticProfiling-staging-0
20K	/data/rstefancsik-park-thymus-staging-0
136G	/data/mshadbolt-LaurentiSpleenBMHSPCs-staging-0
```
from the wrangler EC2 instance to free up space.

Backup copies of the deleted files exist elsewhere.

**Comment by rolando-ebi** [comment]
Thanks Ray

After a quick meeting, we decided to backup all of  `/data` to s3://hca-contributor-data, and subsequently wipe it

**Comment by aaclan-ebi** [comment]
I believe this was accomplished in the 2 sprints ago. Closing now.
