### ISSUE TITLE
Restore HCA DCP spreadsheets in the EBI HCA Ingest

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#25]
**Acceptance Criteria**
* [ ] Wranglers can download spreadsheets that were submitted to the HCA DCP Ingest installation.

Among other things, this will mean copying the persistent volume hosting these from HCA AWS -> EBI AWS

**Comment by justincc** [comment]
**Acceptance Criteria**
* [ ] Wranglers can download spreadsheets for historical submissions just as they can in the HCA DCP Ingest installation.

Among other things, this will mean copying the persistent volume hosting these from HCA AWS -> EBI AWS

**Comment by rolando-ebi** [comment]
The spreadsheet download functionality works, just need to restore the stored spreadsheets from the DCP ingest so it works on restored submissions

**Comment by zperova** [comment]
As of today, I have not been able to download a spreadsheet from the new UI for a couple of submissions.
