### ISSUE TITLE
[BUG] Can't delete some submissions

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-dev-team#257]
Sometimes when I try to delete a submission, the ui tells me I can't
The error message I get is:
"An error has occurred while deleting the submission w/UUID 78e26beb-0f5f-4171-ad53-84f858560fa6 (Distinct microbial and immune niches of the human colon)"

Specifically the submissions and projects I need to delete are:
https://api.ingest.archive.data.humancellatlas.org/projects/5f2be73a4f36d156a8bddba0
https://api.ingest.archive.data.humancellatlas.org/projects/5f2be5e04f36d156a8bdbc4a
https://api.ingest.archive.data.humancellatlas.org/projects/5f2bd4f84f36d156a8bd9ce8

tagging @clairerye for prioritisation

**Comment by mshadbolt** [comment]
adding another project because I noticed another mistake and couldn't delete again
https://api.ingest.archive.data.humancellatlas.org/projects/5f2be8b54f36d156a8bdfaf3

**Comment by rdgoite** [comment]
Here's the error report for the UI:

```
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 409,
  "statusText": "OK",
  "url": "https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/5f2be5d64f36d156a8bdbc48",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/5f2be5d64f36d156a8bdbc48: 409 OK",
  "error": {
    "url": "https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/5f2be5d64f36d156a8bdbc48",
    "exceptionMessage": "Cannot save entity 5f2be5e04f36d156a8bdbc55 with version 536 to collection biomaterial. Has it been modified meanwhile?"
  }
}
```

No errors were reported in the Core logs.

**Comment by rdgoite** [comment]
All these projects have now been deleted. What I did was basically to repeteadly attempt to delete the submission until it succeeded. There's a bug related to this in #273.

**Comment by aaclan-ebi** [comment]
This was accomplished 2 sprints ago. Closing now.
