### ISSUE TITLE
Set up ingest integration tests in prod

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#258]
Acceptance:
- [x] Integration test cleans up all entities created as part of test (submissions, metadata, etc)
- [ ] All integration tests submit to a specific project UUID so that if the integration test cleanup routine fails, the submissions linked to the project are easy to identify and manually remove them.

**Comment by aaclan-ebi** [comment]
> All integration tests submit to a specific project UUID so that if the integration test cleanup routine fails, the submissions linked to the project are easy to identify and manually remove them.

We can just use the project name /short name to easily search the projects from integration tests. 
Ideally we want to avoid tests to refer to existing data.

All test projects will have projects with name: 'SS2 1 Cell Integration Test', '10x 1 Run Integration Test'.

I'll remove the filtering out of test projects in the UI to surface any undeleted test projects and view test submissions.

**Comment by MightyAx** [comment]
Good point Alegria.
If all integration tests are created with an obvious project, that'll be perfect.
I remember that the old integration tests had 4 submissions, 2 with a project, and 2 without.

**Comment by aaclan-ebi** [comment]
@MightyAx There will only be 2 test submissions now. (I've disabled the secondary submission which is no longer needed for DCP2) Both will have project with name 'SS2 1 Cell Integration Test'.

Changes:
https://github.com/ebi-ait/ingest-integration-tests/compare/42ba4a9..5763f8b

I removed the daily schedule. This can just be triggered manually.

**Comment by aaclan-ebi** [comment]
Actually it may no longer be necessary to remove the daily job. The delete will always happen even in failures unless the test was forcefully cancelled.

I will keep it manually triggered for now as that's what we agreed on.

**Comment by aaclan-ebi** [comment]
Test coverage:
1.  ingest-> upload service integration
2. “big” submission test to test state tracking

We still need to add integration testa for:
1. archiving -> exporting
ebi-ait/hca-ebi-dev-team#189
2. updates
ebi-ait/hca-ebi-dev-team#261
