### ISSUE TITLE
[Core] Exporter Data Model and API endpoints

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#262]
- [x] Data Models
- [ ] Mongo Repositories
- [ ] Endpoints

**Comment by aaclan-ebi** [comment]
https://docs.google.com/document/d/1PG97X_4hDTvZuU4FSH7PZm4QjmpWjKxXgT20iqcXnew/edit

**Comment by MightyAx** [comment]
pushed to `origin/feature/export-job-repository`

**Comment by aaclan-ebi** [comment]
This was promoted to production last 26 Aug https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#26-august-2020
