### ISSUE TITLE
[Exporter] Set ExportJob status when ExportEntities meet criteria

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#267]
- Count entities in ExporterJob
    - That are complete
    - That have no errors
    - That are a unique AssayId
 - If count == exporterJob.context.expected assays
    - then set the state to complete
    - !!!May have to check for locking issues!!!
- If any exporter pod fails, set the exporterJob status to fail

**Comment by aaclan-ebi** [comment]
The exporter changes for this ticket was promoted to production alongside the Core changes last ~ Aug 26

https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#26-august-2020
