### ISSUE TITLE
Unsafe partial deletions for Projects and Submission Envelopes

### ISSUE THREAD

**Issue by rdgoite** [ebi-ait/hca-ebi-dev-team#273]
There's a problem with the deletion code in the backend where it encounters optimistic locking exceptions at random points (race condition), after already deleting some of the related records. This leaves any Project or Submission in an inconsistent state when it happens where some of their original contents are already deleted, but some aren't. We don't know what the risks are yet if the user eventually decided to export the inconsistent submission anyway thinking the deletion failed without consequence.

This issue was discovered through ticket #257.

**Comment by lauraclarke** [comment]
@rdgoite did you do any work on this yet?

**Comment by rdgoite** [comment]
Yes, I'm currently working on this task.

**Comment by aaclan-ebi** [comment]
I believe this was accomplished in the last sprint/s and has already been released to prod. Closing now.
