### ISSUE TITLE
Giving UCSC folks wrangler privileges in ingest

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-dev-team#274]
This ticket is about giving people who wrangler data in the UCSC team wrangler privileges in the ingest UI

We know there will be at least three accounts

- [ ] Parisa Nejad
- [ ] William Sullivan
- [ ] Clay Fischer

Once they have created accounts they should be given wrangler privileges. 
There may also be other members of the UCSC team who need to be given privilege but we will find this out on Wednesday

##Questions
Is there any documentation or best practice guidance they need to be pointed to once they have the additional privilege?
Is there a process to find out if they have generated accounts?

**Comment by rolando-ebi** [comment]
Currently blocked by our integration with Elixir. A recent change to our client configuration caused Elixir to reset our oauth scopes, so they're no longer sending us back the ID of elixir users, which we need to register users in our database

**Comment by aaclan-ebi** [comment]
I believe the Elixir AAI config issue was resolved day after. This ticket was accomplished in the 1 sprint ago. Closing now.
