### ISSUE TITLE
Change Ingest UI url

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#277]
Change UI URL that we use - https://ui.ingest.archive.data.humancellatlas.org/ to become https://contribute.data.humancellatlas.org
Subtasks:

- [x] Set up of this new subdomain in route 53
- [x] Set up in the owner of the data.humancellatlas domain
- [x] Elixir callback URLs
- [ ] Redirection for the old URL

**Comment by prabh-t** [comment]
contribute.data.humancellatlas.org is now a zone registered in AWS Route 53. I have asked for permissions to add a record to the HCA AWS DNS configuration that would delegate lookups of .contribute.data.humancellatlas.org domains to the Route 53 nameservers:

```
contribute.data.humancellatlas.org	NS		
ns-561.awsdns-06.net.
ns-406.awsdns-50.com.
ns-1813.awsdns-34.co.uk.
ns-1399.awsdns-46.org.
```

Added the redirect URLs in Elixir AAI client registration and asked that appropriate scopes are set for these.
```
https://dev.contribute.data.humancellatlas.org/aai-callback
https://staging.contribute.data.humancellatlas.org/aai-callback
https://contribute.data.humancellatlas.org/aai-callback
```

**Comment by aaclan-ebi** [comment]
Prod UI was changed to https://contribute.data.humancellatlas.org/ last 26 Aug. Closing now.
