### ISSUE TITLE
Test and File Elixir AAI issues

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#280]
Subtasks:
1. Test different identity providers like EBI, LinkedIn, ORCID etc (Create steps to reproduce the issue)
2. File tickets to Elixir AAI

**Comment by rdgoite** [comment]
I'm not really sure how we want to go about this. If I assigned myself to this issue, my concerns are that 1) I don't have accounts on all third-party services we want to check, but 2) for those which I have, I don't want to use my personal accounts to test for compatibility.

Can we not just communicate with Elixir and have them test their own service for compatibility with any of the services we'd like for them to support?

**Comment by ke4** [comment]
It is all right. I can do this, I have accounts or can create test accounts.
We need to test this asap, so probably it is better if we do it ourself.

**Comment by ke4** [comment]
1. Issue (https://rt.cesnet.cz/rt/Ticket/Display.html?id=732316)
If the user mistype their email address at registration there is no way to fix it

Step to reproduce:

1. Select one of the identity provider. (I selected LinkedIn)
2. Type the required credential for the provider.
3. Click on the `Continue to a page with additional information`
button on the Elixir page
4. Click on the `Register` button on the Elixir page
5. Fill in the required information. Add a non-existing email address
to the `Email` field and submit the form.

From the next page there is a never ending loop if I click on the
`Continue` button.

I tried to close the browser and repeat from step 1., then after step
4 I can not reach the registration form again as it is letting me know
that I already submitted a registration to Elixir.

That is a bit of annoying, because it seems that I won’t be able to
correct this typo, so I will never able to use Elixir with that
account at all.

Elixir's answer:
Dear Karoly,

thank you for your feedback.

Unfortunately, our system currently does not support some kind of "review" of the application. We will try to add such functionality.

The current procedure in such a case, is, to write to this support email. We will reject the application and you can apply again.

Best regards,
Bc. Dominik František Bučík
ELIXIR AAI

**Comment by ke4** [comment]
2. Issue ( https://rt.cesnet.cz/rt/Ticket/Display.html?id=731859)

At registration I got a strange error message for a username: kerdostestlinkedin

**Error message**: Allowed format is lowercase letters and numbers and _ -. Nickname cannot start with _.

The above user name fulfil all the requirements appearing on the screen. It might be too long, but there is no given requirement for length.

I also attached a screenshot from the error.

Step to reproduce:

1. Select one of the identity provider. (I selected LinkedIn)
2. Type the required credential for the provider.
3. Click on the `Continue to a page with additional information` button on the Elixir page
4. Click on the `Register` button on the Elixir page
5. Fill in the required information. Add a longer user name to the `Username` field.

**Elixir's answer:**

Dear Karoly,

thank you for the feedback. Currently, the username cannot be longer than 14 characters. I have modified the message to also state this fact.

Best,
Dominik

I tested it and the maximum length message is there now, but I found other similar issues with user name validation that I sent it to Elixir:

There are some other length validations applied I think, but the error message is not properly states that.
I figured out that they probably have a minimal length validation rule, but no message about it:

![Screenshot 2020-08-26 at 10.59.22.png](https://images.zenhubusercontent.com/5f2957fd448645a503a32777/fa4e9347-646a-4959-a104-a3e5d777b759)


I also noticed some validation bug with perfectly valid user names, at least according the red messages.

![Screenshot 2020-08-26 at 11.03.00.png](https://images.zenhubusercontent.com/5f2957fd448645a503a32777/200046ae-e2c4-48d2-9e01-cca787dfd3c5)

![Screenshot 2020-08-26 at 11.03.43.png](https://images.zenhubusercontent.com/5f2957fd448645a503a32777/73c2d719-8bc6-42d2-8370-06d05de8c285)

**Comment by ke4** [comment]
3. Issue ( https://rt.cesnet.cz/rt/Ticket/Display.html?id=731962)

I tried to register my ORCID ID, but Elixir keep telling me that it has found a similar user in the system.
I would have to prove my identity. When I tried to do it by identity provider and selected Elixir AAI and clicked on ORCID then I got this message:

"Your are signed in with

orcid

Neither original or current identity is registered. Please use registered identity at least in a one step.
 Try again
Continue “

None of the options would help.
`Try again` would start from the beginning. 
`Continue` would go back to identity provider selection.

Step to reproduce:

Prerequisite: your user is already registered with another identity provider in Elixir.

1. Select ORCID as the identity provider.
2. Type the required credential for the provider.
3. Click on the `Continue to a page with additional information` button on the Elixir page
4. Click on the `Register` button on the Elixir page
5. Fill in the required information and submit the form.

**Elixir's answer:**

Dear Karoly,

when you try to register, our system correctly recognizes that a user account which is similar to the registration data provided has been found. Therefore, it offers you to log in with your existing account (in this case LinkedIn). If you log in with something different (ORCID again), you will not get recognized.

You have two options in this case:
1) Log in with your LinkedIn registered account. Then you can connect also the ORCID account to this one and our system will recognize you as the same person (no matter if you log in with LinkedIn, ORCID). You can connect together how many accounts you want (university, Google, etc.)
2) Ignore this message, if the recognized account is not yours.

Best,
Dominik

**Comment by ke4** [comment]
4. Issue (https://rt.cesnet.cz/rt/Ticket/Display.html?id=733022)

When I try to register my google account and Elixir found a similar user after choosing the test identity provider I got this error:

This site can’t be reached

idp4.ebi.ac.uk’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

**Elixir's answer and further correspondence:**

Dear Karoly,

unfortunately, this is not a problem on our side. We do not have any configuration associated with the domain name you have sent us. This seems to be a problem on the side of EBI. Please contact administrators of the service provider and ask them to fix it.

----------

Hi Dominik,

Are you sure that it is not a configuration issue at Elixir?

This is the dialog box I am referring to:

![Screenshot 2020-08-27 at 10.37.32.png](https://images.zenhubusercontent.com/5f2957fd448645a503a32777/2ee82843-65c1-4807-90e8-ca00bba1df2c)

If I select the 2nd option: https://ldp.ebi.ac.uk/ldp/shibboleth, then it works.
But with the 3rd option: https://test.ebi.ac.uk/ldp/shibboleth I got that below mentioned error.

If you think that is not a configuration issue at Elixir, then I am going to raise it with EBI.

Many thanks,

Karoly

**Comment by ke4** [comment]
5. Issue (https://rt.cesnet.cz/rt/Ticket/Display.html?id=733432)

This morning I tried to register with LinkedIn and I got to this page:

![Screenshot 2020-08-27 at 10.49.43.png](https://images.zenhubusercontent.com/5f2957fd448645a503a32777/e5c0410e-f4ba-40cd-85ab-c7894d8dd22a)

Additional information:

I tried to register first with Google but then I changed my mind and went back to the identity provider selection step and selected LinkedIn.

**Comment by ke4** [comment]
6. Issue (https://rt.cesnet.cz/rt/Ticket/Display.html?id=733577)

I tried to login with my LinkedIn account and I got this error message that I on’t really understand + there is a typo in it.

![Screenshot 2020-08-27 at 18.12.44.png](https://images.zenhubusercontent.com/5f2957fd448645a503a32777/3d29b174-2fe0-4b8c-b10e-e6a3fb1ddc14)
