### ISSUE TITLE
Decide modus operandi regarding the user on DSP submissions

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-dev-team#29]
Following the conversation on [slack](https://humancellatlas.slack.com/archives/GAQ2W4CKX/p1579700033001100), I would like for all wranglers and ingest team to discuss the accounts and permissions in regards to users that would like to archive their [meta]data through the DSP.

Key points to discuss:

1. User - Do we give them access to modify their submissions or do we get them to ask us?
   1. If we give them access, we need to set up how to do it
1. Account - Should we set up an official account with a domain for HCA wranglers?

There's a temporal decision now about keeping it in the domain I created (`subs.team-20`) and treating that domain as an HCA wrangler submission, but a final decission has to be made before moving towards more submissions.

**[Document](https://docs.google.com/document/d/1ZOz9OaKdy0B7zWDiQPFCbW79hX0jAtXdFVV7-QNKSoM) for this discussion**

**Comment by justincc** [comment]
Please could you split this into 2 tickets. It seems to me that point 1 is a far flung item and point 2 is a near-term item. They do not appear inextricably linked.

**Comment by justincc** [comment]
Please review and use [this document](https://docs.google.com/document/d/1ZOz9OaKdy0B7zWDiQPFCbW79hX0jAtXdFVV7-QNKSoM) for ongoing discussion.
