### ISSUE TITLE
Update AWS tags and add tags to HCA AWS resources that don't have labels

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-dev-team#295]
The EBI cloud team have let us know that some of our resources are still not tagged and this makes giving us accurate bills difficult.

We need all our services to be tagged by the end of August 28th

There is apparently a method in the AWS console to find the untagged resources, @prabh-t and @ofanobilbao will be shown this method by CD from the cloud team

Tony Burdett has suggested we have two tags, hca-storage and hca-compute as it will help with cost management

By August 31st we need

- [ ] ~~All HCA AWS resources to be tagged either hca-storage or hca-compute~~
- [ ] An update to the SOP about deploying resources in AWS about tagged and checking for non-compliant resources
- [ ] A standing operational task documented (say once a month) to check everything is tagged

**Comment by lauraclarke** [comment]
@prabh-t if you can do this after you have been given instruction great, otherwise please let @rolando-ebi know how to do this check so he can complete it.

**Comment by prabh-t** [comment]
@rolando-ebi if you're looking into this next week (I'm away), many incompliances are being caused by the folllowing:
- the use of "project" instead of "Project" as tag key. Tag key-value pair is case-sensitive. This is the easy one to fix.
- we have a problem with tag propagation (and support) for certain AWS resources that are provisioned via terraform. EBS volumes not being taffed. We do not directly provision those, or EC2 instances. These are created by the autoscaling_group and despite turning tag propagation on, they aren't being tagged. I have briefly read about the possibility of using launch_template instead of launch_configuration with the autoscaling_group which may help, but I haven't tested it. Such a change would require rebuilding the clusters.
- not all upload service resources are being tagged at the moment. 

I can't think of an easy way to apply the two tags Tony suggested. We use higher-level resource abstractions to provision these base resources.

**Comment by rolando-ebi** [comment]
Thanks @prabh-t , yeah it doesn't seem straightforward right now to identify and tag all our resources. Ideally an operation like this should happen in Terraform, where the cloud resources should be tracked and then tags could be trivially applied with a `terraform update` or something like that. For now, I'm considering just manually applying tags, however we'll likely be dealing with the same issue later unless we look into changing our deployment scripts to ensure that cloud resources are tracked. 

A good test would be to attempt building a test ingest+upload environment and check that all resources are appropriately tagged. Would also need to test the adhoc cloud-resources created by upload service (the file-validation fleet spawns large and expensive VMs and likely the most significant cost to track, outside of S3)

**Comment by rolando-ebi** [comment]
Note: upload-service lambdas need to be tagged. See https://github.com/ebi-ait/upload-service/blob/master/terraform/modules/upload-service/checksumming_lambda.tf#L116

**Comment by rolando-ebi** [comment]
Note: Not all HCA AWS resources can be automatically tagged. For example, the volumes defined in AMIs don't have a mechanism for providing tags. We should ask the cloud team whether this is acceptable

**Comment by prabh-t** [comment]
there is no point in tagging resources with `hca-storage` or `hca-compute` as it is not always clear which category a particular resource fits in, and AWS service charges are already classified accordingly in the billing section.

**Comment by lauraclarke** [comment]
@prabh-t can this be considered done and closed?

**Comment by ofanobilbao** [comment]
My understanding from the emails and response from cloud consultants in that we are on a good place. And that now is all about making sure it stays that way. Is that correct? I see that the acceptance criteria in this issue included an SOP and a standing operational task to check compliance on a monthly basis. Are those in place?

**Comment by lauraclarke** [comment]
from what @rolando-ebi said in the operations catch up there is something about tagging the upload service deployment that @aaclan-ebi was doing and a final SOP update before it could be considered done

Does that match your understanding @aaclan-ebi

**Comment by aaclan-ebi** [comment]
I've already applied the changes to the upload service tags. To update the tags, it must be modified in the terraform config, there's already an SOP here how to apply any terraform config changes https://ebi-ait.github.io/hca-ebi-dev-team/Upload-Service.html

**Comment by aaclan-ebi** [comment]
Looks like @prabh-t has some suggestions for my PR about the updates to tagging, I can further look into those , but I would have prioritise the sprint development tasks.

**Comment by lauraclarke** [comment]
@rolando-ebi is this something you can take over for @aaclan-ebi? It would be good to take this finished

**Comment by lauraclarke** [comment]
@aaclan-ebi @prabh-t where is the SOP about this tagging?

It would be good to get this ticket completed?

**Comment by lauraclarke** [comment]
This has been automated so no SOP is needed
