### ISSUE TITLE
[bug] Linking fields not generating in the ui-based spreadsheet generator

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-dev-team#305]
While testing the spreadsheet generator in the ui (#256) I noticed that spreadsheets do not contain linking fields. This appears to be occuring for both linking biomaterials as well as linking protocols between biomaterials.

biomaterial linking example:
* a user needs to be able to specify which donor a specimen comes from which is done by having an `INPUT DONOR ORGANISM` column in the `Specimen from organism` tab

protocol linking example:
* a user needs to be able to specify what dissociation protocol was used to dissociate a specimen into a cell suspension by having a `DISSOCIATION PROTOCOL` column within the `Cell suspension tab`

@ami-day @rdgoite I don't know whether this is a bug in the generator itself or something in the way the ui is requesting the spreadsheet.

**Comment by mshadbolt** [comment]
@rdgoite and I figured out that we need to add the linkSpec to the various typeSpecs and have done that with mixed results.

@rdgoite is working on a fix so that when the specs are merged it recognises that it also needs to merge in the links that are specified.

I need to think a bit about how things need to be linked and if there are any defaults we could incorporate.

**Comment by rdgoite** [comment]
The linking rules have now been deployed to staging. There's still a problem with some of the column names (user friendly) but that's related to one of the problems in #304.
