### ISSUE TITLE
Open discussions with Matt Greene about getting data from Ingest to SCEA

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#31]
Need to involve a wrangler. The actual implementation could be any number or routes (through archives, direct from ingest JSON to SCEA, etc.). This is probably something @justincc needs to own but other devs are welcome (and probably will be required) to take part :)

**Acceptance Criteria**
* [ ] Wrangler/s are nominated for this task as well as dev/s.
* [ ] There is a document exploring possibilities and detailing a decision.

**Comment by justincc** [comment]
This may end up being a duplicate of #34

**Comment by prabh-t** [comment]
An overview meeting happened on 28/01/2020 involving wranglers, Prabhat and Matt. Another one between just Prabhat and Matt is scheduled on 30/01/2020 to go through the tech details and existing code.

**Comment by justincc** [comment]
@prabh-t in discussion with @lauraclarke this morning we can call this done from our end. We will continue to provide support on as needed basis.
