### ISSUE TITLE
Spreadsheet generator: “Required” column names doesn’t seem right in multiple cases

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-dev-team#313]
The column names labelled as "(Required)" do not look quite right to me. However, I would appreciate if another wrangler can check this. It is possible that it is identifying "required" fields based on what **used** to be required, and there have been updates since then meaning they are no longer required.

**Acceptance critera:**

- [ ] Check the "Required" columns and identify where the problem lies

- [ ] Implement changes to the code to solve this

- [ ] Update the unit tests to reflect any changes

**Comment by mshadbolt** [comment]
Can @ami-day give an example/s of where you think the required columns are incorrect?

**Comment by ami-day** [comment]
E.g. Ethnicity (Required) in donor_organism tab. But there's more (to be investigated).

**Update:** we decided we would check how crucial/wide-spread this problem is, and if it's not super crucial/won't overwhelm the user, we'll go ahead and deploy what we have working for testing in the UI.

**Comment by mshadbolt** [comment]
I think my latest changes to the ingest-client have fixed this but it would be awesome if you could double check to see if you think that it is fixed. At writing the changes are in the dev environment.

**Comment by mshadbolt** [comment]
I am pretty sure this is fixed but we can reopen if we find it is still an issue
