### ISSUE TITLE
Spreadsheet generator: missing expected tabs

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-dev-team#314]
Some tabs are now missing in the spreadsheet even though they are specified as a TypeSpec to include. For example, the tabs relating to these TypeSpecs are missing:

`TypeSpec("cell_suspension", IncludeAllModules(), False, LinkSpec(["specimen_from_organism"], ["dissociation_protocol"])),`
'TypeSpec("library_preparation_protocol", IncludeAllModules(), False, None)'

This was not a problem before merge requests were accepted yesterday, so making a comparison in the code before and after the merge should help to resolve the source of the problem.

**Acceptance criteria:**

- [ ] Update the code to solve this problem

- [ ] Run the unit test which tests the expected tab names and check these are correct

- [ ] Run the 'generate' unit test to check the tabs are indeed all present in the test spreadsheet

**Comment by mshadbolt** [comment]
I am using the latest code from master and it seems to work for me, are you sure it isn't because these tabs aren't included in the `test_spreadsheet_spec` object in `test_spreadsheet_generator.py` : `test_user_friendly_names` & `test_generate`?

**Comment by ami-day** [comment]
They are included, but it was because of the "Donor organism - Familial re..." error causing the test generate function to not work as it should. I am marking this as resolved: I will keep "Donor organism - Familial re..." in the expected tab names list in the unit test until the problem causing the "Donor organism - Familial re..." tab has been resolved.
