### ISSUE TITLE
AWS s3 bucket permission issues

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-dev-team#319]
We have been sent this warning by CD from the cloud team

Bucket names 							Signals
hca-ingest-upload							RED
org-hca-data-archive-upload-prod 				YELLOW
schema.dev.archive.data.humancellatlas.org 	YELLOW
schema.archive.data.humancellatlas.org 		YELLOW

Alert Criteria
Yellow: The bucket ACL allows List access for "Everyone" or "Any Authenticated AWS User".
Yellow: A bucket policy allows any kind of open access.
Yellow: Bucket policy has statements that grant public access. The “Block public and cross-account access to buckets that have public policies” setting is turned on and has restricted access to only authorized users of that account until public statements are removed.
Yellow: Trusted Advisor does not have permission to check the policy, or the policy could not be evaluated for other reasons.
Red: The bucket ACL allows Upload/Delete access for "Everyone" or "Any Authenticated AWS User".

Not sure what the next step or expectations here is

**Comment by lauraclarke** [comment]
@clairerye @prabh-t @aaclan-ebi @rolando-ebi FYI

**Comment by lauraclarke** [comment]
@prabh-t @aaclan-ebi I think this was resolved

Can this ticket be closed

**Comment by aaclan-ebi** [comment]
The following buckets are fixed by @prabh-t .

```
hca-ingest-upload RED
org-hca-data-archive-upload-prod YELLOW
```

But I think the following buckets aren't fixed yet:
```
schema.dev.archive.data.humancellatlas.org YELLOW
schema.archive.data.humancellatlas.org YELLOW
```

**Comment by lauraclarke** [comment]
@rolando-ebi do you know how to resolve this?

**Comment by prabh-t** [comment]
I have spoken to C.D. and he's not worried about the YELLOW - they are only advisory. The two concerned buckets need to have some kind of access so they can be read and served via http.

**Comment by prabh-t** [comment]
@lauraclarke I have spoken to C.D. and he's not worried about the YELLOW - they are only advisory. The remaining two concerned buckets need to have some kind of access so they can be read from and served via http and that's what the current permissions allow. I am closing the ticket.
