### ISSUE TITLE
Assess the extent to which the HCA CLI tool requires the rest of the DCP to function

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#32]
We need to know this so that we can assess whether we can keep using this, need to fork a tool and rip bits out or do something else entirely

**Acceptance Criteria**
* [x] There is a written doc (either in the ticket here or in a Google doc) which summarizes how tightly the HCA tool is bound to the rest of the DCP 
* [x] There are written pro/con options as to how we can allow wranglers to upload to EBI storage (e.g. fork and rip out bits of the HCA tool, do direct upload to S3 instead).

**Comment by rolando-ebi** [comment]
The HCA CLI tool wraps CLI tools written by the DSS, upload-service, now-defunct query service etc.

Looking at the recent removal of the query service from the tool (see https://github.com/HumanCellAtlas/dcp-cli/commit/700234d2ac05165faf5c7817d6dac8513c115337), this looks to be as simple as removing references to sub-CLIs from the main CLI

Replacing the current upload functionality should be as simple as having the tool reference our own upload-service swagger API URL.

If we implement our own kind of upload-service that uses s3, then it should still be simple assuming we make a swagger API for our new kind of upload service
