### ISSUE TITLE
[Exporter] Write DCP2 exports to project "sub-directories"

### ISSUE THREAD

**Issue by rolando-ebi** [ebi-ait/hca-ebi-dev-team#322]
Raaid has proposed a change to the data-exchange format for new datasets: 

Rather than exporting all of our metadata, data, links, and descriptors to `/metadata`, `/data`, `/links`, and `/descriptors` respectively, we should instead export to a prefix determined by the project being exported.

e.g

Instead of exporting, for example, a `donor_organism` to `gs://staging-bucket/prod/metadata/donor_organism/<uuid>_<version>.json`, we should export to `gs://staging-bucket/prod/<project-uuid>/metadata/donor_organism/<uuid>_<version>.json`

The benefits of this are:

- It allows the TDR team to selectively import projects; we just tell them the project UUID and they know where to find all related metadata/data in the staging bucket.
- It allows us to straightforwardly wipe all data for a project if needs be

**Acceptance criteria:**
- The staging bucket prefix for exports must be changed from `<env>` to `<env>/<project-uuid>`

**Comment by lauraclarke** [comment]
Great, @MightyAx @prabh-t @rdgoite @ke4 which of you have time to make this change?

**Comment by rolando-ebi** [comment]
Disclaimer: this hasn't yet been agreed in the wider DCP2 MVP spec

**Comment by lauraclarke** [comment]
Ah, is this something that will need doing post MVP data release? In which case I guess @clairerye needs to prioritize it with everything else

**Comment by clairerye** [comment]
Thanks @rolando-ebi. Just to clarify, I was hoping to do this asap once it has been agreed by the wider DCP as it will give us more options with regards to future exports. 
I think however is free on dev next can work on it, but I think @prabh-t had expressed an interest on working on the exporter since the KT session.

**Comment by lauraclarke** [comment]
Might be worth raising it for approval in case once the spec gets approved there are changes

@rolando-ebi has the proposal already been added to https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg/edit#heading=h.aee8p3q0sp0m and flagged to UCSC for approval?

**Comment by rolando-ebi** [comment]
@lauraclarke the proposal hasn't been added yet

**Comment by rolando-ebi** [comment]
@lauraclarke @clairerye the proposed change is already compliant with the existing spec. No DCP2 MVP spec changes need to be made for this ticket (the ingest-exporter documentation should be updated though). I recommend beginning work on this as soon as possible

**Comment by clairerye** [comment]
moving to new repo
