### ISSUE TITLE
[File Archiver] Use AWS CLI to speed up file download and checksum file after download

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#323]
@ESapenaVentura reported that during file archiving, the files can be truncated after being downloaded from s3. 
slack: https://embl-ebi-ait.slack.com/archives/CSDN3M2P5/p1600174803097000

Dev notes: 
The checksum information can be passed on the file upload plan from the metadata archiver
The file archiver can refer to the checksum info every after file download

**Comment by lauraclarke** [comment]
The outstanding action here is @aaclan-ebi to update the archiving SOP to ensure people use the newest version of the script which uses the AWS CLI for downloads
