### ISSUE TITLE
Create a temporary alternative path for receiving data from submitters

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#33]
The DCP Query Service is currently down. This has stopped the HCA CLI tool from working. Although the query service will probably be restored shortly, this is out of our control and we do not want to rely on it. Therefore, we need an alternative way of receiving data from submitters. This will probably be an S3 bucket and instructions on how to upload the files.

**Acceptance Criteria**
* [x] We have a facility for temporarily receiving files.
* [x] There are instructions on how to use this facility (creating these collaboratively between development and wrangling).
* [x] Marion is satisfied that her submitter can use this process.
* [ ] This temporarily facility is documented (insert Google doc link here).

**Comment by rolando-ebi** [comment]
**Steps**

- Install aws-cli. See https://docs.aws.amazon.com/cli/latest/userguide/install-bundle.html#install-bundle-other
- Change directory to the files location
- Run `aws s3 cp ./ s3://hca-ingest-upload/uploads --recursive --no-sign-request`

**Comment by mshadbolt** [comment]
Can confirm that it worked for me.
I also used
```
C02YV4HKLVDL:test_ingest_upload mshadbolt$ aws s3 ls s3://hca-ingest-upload/Forrest-10xBiasAssessment/ --no-sign-request
2020-01-24 15:18:21          0 
2020-01-24 15:35:13         12 hello_world.txt
```
to list bucket contents and
```
C02YV4HKLVDL:test_ingest_upload mshadbolt$ aws s3 rm s3://hca-ingest-upload/Forrest-10xBiasAssessment/hello_world.txt --no-sign-request
delete: s3://hca-ingest-upload/Forrest-10xBiasAssessment/hello_world.txt
```
To remove file that I uploaded as a test.

This was a tiny trivial text file but hopefully will scale okay with larger fastq files.

I will write some instructions up to share with the contributor in case CLI still not working next week.

**Comment by rolando-ebi** [comment]
Disabled deletes and downloads on the s3 bucket

**Comment by mshadbolt** [comment]
As far as a public location that I could share with contributors about how to use this way, would @justincc be ok with me creating a `docs` folder within the `ebi-ait/hca-ebi-dev-team` repo and putting a markdown in there outlining the process?

**Comment by justincc** [comment]
Let's avoid that since any tickets opened against the documentation would get intermixed with all the ingest-dev management tickets. Could we create an hca-docs repo? Does it need to be in the repo itself or could it be in its associated wiki?

**Comment by mshadbolt** [comment]
We could do the wiki, main requirement is that it just has to be openly accessible to any potential contributor. I think a docs repo sounds like a reasonable solution.

**Comment by justincc** [comment]
Sounds good to me. You will create it?

**Comment by mshadbolt** [comment]
Yep I can start setting it up and others can add if there are other documentation things we want to capture

**Comment by mshadbolt** [comment]
I put together a guide doc here: https://github.com/ebi-ait/hca-documentation/wiki/How-to-upload-data-to-the-ingest-upload-area

**Comment by mshadbolt** [comment]
The contributor I provided these instructions to could not upload to the bucket, this is the error she got:
```
aws s3 ls s3://hca-ingest-upload/Forrest-10xBiasAssessment  --no-sign-request

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

aws s3 cp ./ s3://hca-ingest-upload/Forrest-10xBiasAssessment --recursive --no-sign-request
 
upload failed: ./BG22_1.fq.gz to s3://hca-ingest-upload/Forrest-10xBiasAssessment/BG22_1.fq.gz An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Anonymous users cannot initiate multipart uploads.  Please authenticate.

```

When I tried last time it worked but now when I try the following it doesn't

```
(base) C02YV4HKLVDL:Desktop mshadbolt$ aws s3 cp test.txt s3://hca-ingest-upload/Forrest-10xBiasAssessment --no-sign-request
upload failed: ./test.txt to s3://hca-ingest-upload/Forrest-10xBiasAssessment An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```

**Comment by mshadbolt** [comment]
The contributor tried again and got the same error I reported yesterday
```
upload failed: ./BG1-AK2004_S4_L001_R1_001.trim.fastq.gz to s3://hca-ingest-upload/Forrest-10xBiasAssessment/BG1-AK2004_S4_L001_R1_001.trim.fastq.gz An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Anonymous users cannot initiate multipart uploads.  Please authenticate.
```

**Comment by mshadbolt** [comment]
Updating this ticket with what was discussed on slack:
@prabh-t figured out that to allow large uploads to the bucket, users have to be authenticated. The devs determined that it would be best to provide temporary access keys that will be tracked and deactivated once the contributor has finished uploading data.

I was provided with two keys and used one for myself for testing and provided one to the contributor.

I updated the documentation about how to configure these keys to allow large file uploads.
