### ISSUE TITLE
Knowledge transfer and documentation/specification for the Terra Exporter

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-dev-team#335]
This ticket is to track the knowledge transfer and creation of documentation for the terra exporter https://github.com/ebi-ait/ingest-exporter by @rolando-ebi

The goals of this ticket are to ensure other members of the @ebi-ait/hca-dev team understand the state tracker and have enough documentation to use and maintain the state tracker after Rolando has left the team

## Acceptance criteria

 - [ ] Link to Document/file to describe the function and design principles of the exporter and review by other members of @ebi-ait/hca-dev team
 - [ ] Knowledge transfer (or agreement such a meeting isn't needed) so at least two other members of the @ebi-ait/hca-dev understand the exporter 

If there isn't already a document, the AIT HCA ingest folder may be a good location https://drive.google.com/drive/u/1/folders/137ztd4LRMzWBRDdccBCNSricfq_vmp7L

**Comment by rolando-ebi** [comment]
Exporter design doc: https://docs.google.com/document/d/15zxIHub2erKGWW7uGmep7ZjqsTNcI3gn5oDQmMB7Eic/edit?ts=5f71fda7#

**Comment by rolando-ebi** [comment]
For KT meetings, we've had
- one with Alexie
- one with Prabhat and Rodrey
- one with Prabhat, Alexie, and Alegria (supervised and assisted Alegria doing the KT)
- one with Alegria and Karoly (supervised and assisted Alegria doing the KT)
