### ISSUE TITLE
Fix generation of file descriptor metadata in the exporter

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#338]
Fix the validation errors:

https://ebi.enterprise.slack.com/files/WLLT62VLP/F01B1QGAK29/screenshot_2020-09-22_at_10.07.11.png

**Comment by aaclan-ebi** [comment]
@ESapenaVentura , fyi

**Comment by ESapenaVentura** [comment]
Things that the exporter is not generating up to specs:

- Timestamps are being generated with 3 decimals **FOR ALL FILES**. This is not up to spec, as they should be generated with 6 decimales
   - Also, decimals are being ignored if they have all trailing `0`s (e.g. `2020-08-06T11:33:16Z`
- For `file_descriptor`s, the `schema_type` field is not being filled.

That's all I can remember for now, I'm doing a scrutiny of the DCP2 mvp specs just in case I find something else
