### ISSUE TITLE
Help Matt Greene produce MAGE-TAB for 13 DSS datasets not in SCEA

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#34]
As part of the forthcoming HCA release we need to get 13 of the DSS datasets not yet analyzed in the Single Cell Expression Atlas in there. This means working with Matt Greene to use an existing script produced by Simon Jupp to do this. Anticipate that Matt Greene will lead the work but we need to be aware of how things are working as well. For future datasets this script or something like it will need to be adapted to work either from ENA or directly from ingest mongodb/upload.

**Acceptance Criteria**
* [ ] The 13 DSS datasets are analyzed in SCEA.

**Comment by justincc** [comment]
Waiting for the release to be announced

**Comment by justincc** [comment]
Recording the fact that @prabh-t and @zperova are talking about this.

**Comment by zperova** [comment]
Meeting with SCEA curators and Matt is scheduled for Jan 28

**Comment by justincc** [comment]
@prabh-t in discussion with @lauraclarke this morning we can call this done from our end. We will continue to provide support on as needed basis.

**Comment by lauraclarke** [comment]
@prabh-t an extension to this, @javfg and Ami have done a lot of work in this space. We should arrange a catch-up and think about steps to integrate this with ingest proper
