### ISSUE TITLE
Knowledge transfer and documentation on Spreadsheet Generation

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#340]
@ami-day, fyi

Everyone's free to join the KT.

**Comment by ami-day** [comment]
I suggested we set this up for everyone since others in the team were asking about the spreadsheet generator code, not just me! but I'd like to go through again as still finding it a bit complex to get my head around.

**Comment by ami-day** [comment]
would you mind, @rolando-ebi ?

**Comment by lauraclarke** [comment]
Given the level of knowledge within the team and outside the team will be quite different, it might be better of Rolando conducts a knowledge transfer within the team and then if possible someone else runs on for other people with Rolando in attendance to pick up gaps from the other person

**Comment by rolando-ebi** [comment]
There a KT meeting for this a while back, attended by Prabhat and Rodrey I believe.

@rdgoite given you have worked on the codebase (UI + backend) for some time and made changes since I last looked, I think it would be a good idea for you to give this meeting, similar to how Alegria hosted an KT for the DCP2 exporter. I can assist with details on the call.

**Comment by ami-day** [comment]
> There a KT meeting for this a while back, attended by Prabhat and Rodrey I believe.
> 
> @rdgoite given you have worked on the codebase (UI + backend) for some time and made changes since I last looked, I think it would be a good idea for you to give this meeting, similar to how Alegria hosted an KT for the DCP2 exporter. I can assist with details on the call.

This sounds good. I will also work on some diagrams based on my knowledge of the code so far. It would be good to all discuss together since a few of us worked on different components of it.

**Comment by lauraclarke** [comment]
@aaclan-ebi did the outcome of this KT meeting get written up anywhere?
