### ISSUE TITLE
Remove Ingest Deployments from DCP AWS Account

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#348]

**Comment by prabh-t** [comment]
- [ ] bring down all envs (dev, integration, staging, prod) via `terraform destroy`
- [ ] make sure any remaining resources not managed by terraform are also removed
- [ ] e.g. s3 buckets, secrets, certs, dns records

**Comment by aaclan-ebi** [comment]
After a chat with @lauraclarke , it's not a priority to do this as the account will be shutdown eventually.

**Comment by aaclan-ebi** [comment]
Reopening. We still have the schema deployments in the DCP AWS account. We'd have to move those to the EBI AWS account.

The minimum work needed is to copy the bucket which contains the json schema files. I believe we only need that and then we could recreate the deployments after.

**Comment by lauraclarke** [comment]
Is URL redirection also needed?

**Comment by aaclan-ebi** [comment]
@lauraclarke it looks like we already have a copy of dev and prod schema deployments in our EBI AWS account.
The schema versions are all there as well.

 https://schema.dev.archive.data.humancellatlas.org/i
 https://schema.archive.data.humancellatlas.org/i

 I think Javier has set up these before. 

Do we want to set up a staging environment as well?

I believe we should be able to just reuse the url. I need to do some research on how this can be done. I'm still uncertain if there's a way to transfer the domain/hosted zone to EBI AWS rather than removing & recreating it.

**Comment by lauraclarke** [comment]
So I want to make sure that schema.humancellatlas.org continues to function? What is needed to make that work? 

As far as the other environments go, I don't know how/where the other environments are used so if we need to maintain them or not

**Comment by aaclan-ebi** [comment]
This ticket needs to be addressed before 1 Jan 2021

**Comment by aaclan-ebi** [comment]
I'll focus on finishing this task by 22nd Dec.

**Comment by aaclan-ebi** [comment]
Unfortunately, this needs to wait for the update to the new name servers (registered in EBI AWS account) for schema.humancellatlas.org. And this might happen next year.

It should be alright. I will follow up after Christmas holidays and once Sanger has done the update, we should be able to quickly update the configuration of the dev and prod schema instances (previously set up by Javier) in EBI AWS account to use the same url.

Would also be good to confirm with the Hannes and Trevor about the data.humancellatlas.org domain setup by  next year.
http://contribute.data.humancellatlas.org/ is still configured in the CZI’s DCP AWS account , under data.humancellatlas.org hosted zone. It seems that the data portal/browser is also still using that hosted zone.

**Comment by lauraclarke** [comment]
I have sent you a form to fill in, please list me as the owner and let me know if you don't know what to answer for any questions, Happy to find 10 minutes to go this together if needed

**Comment by aaclan-ebi** [comment]
The prod schema url https://schema.humancellatlas.org/i should now be pointing to our instance.

![schema-humancellatalas-org.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/9c5bcce3-674f-4b04-b87b-f673029a670d)

**Comment by aaclan-ebi** [comment]
I've observed that currently https://schema.dev.archive.data.humancellatlas.org/ contains some schemas with non existent schema urls (http://schema.dev.data.humancellatlas.org/*). I've thought of fixing this by replacing the schema contents and changing the dev url to schema.dev.archive.data.humancellatlas.org (which is being used in ingest dev env) to dev.schema.humancellatlas.org however this is not possible because we have the regex pattern validation for `describedBy`

```
"describedBy": {
"description": "The URL reference to the schema.",
"type": "string",
"pattern": "^(http|https)://schema.(.*?)humancellatlas.org/type/biomaterial/(([0-9]{1,}.[0-9]{1,}.[0-9]{1,})|([a-zA-Z]*?))/donor_organism"
}
```
I could have pointed all the dev schemas to use schema.dev.archive.data.humancellatlas.org but decided to use the prod schema urls (schema.humancellatlas.org) in our dev environment for now.

**Comment by aaclan-ebi** [comment]
I'm going to retire https://schema.dev.archive.data.humancellatlas.org/ for now. Will make sure first that it's not reference by any ingest components.

**Comment by aaclan-ebi** [comment]
Applied the minor changes needed to proceed with this. https://github.com/ebi-ait/ingest-kube-deployment/commit/009e08bfdacaf09f1dc6d96b0399b8e4aae7df45

I will now remove https://schema.dev.archive.data.humancellatlas.org/ instance.
