### ISSUE TITLE
Cost reduction in AWS

### ISSUE THREAD

**Issue by prabh-t** [ebi-ait/hca-ebi-dev-team#352]
Implement the measures listed in [Cost reduction in AWS - plan and tracking costs](https://docs.google.com/document/d/1RTtpY3QxGBNcUnvRKA9hH9nJGeSX0t1KmI9k0k2pdHU/edit)

- [x] Change S3 Storage Class
- [x]  Set up expiration rule
- [x] Delete unused buckets
~~- [ ] Shrink Wrangler EBS volume~~

**Comment by prabh-t** [comment]
For the last item, an attempt was made to shrink the EBS but that didn't work so I reverted to the volume snapshot taken before the shrink.

**Comment by lauraclarke** [comment]
Has this been completed? can it be moved to done?

**Comment by prabh-t** [comment]
No. 2 attempts to shrink the ebs have failed so far. After copying over the current 4TB volume to a 400GB, the ec2 won't start. We need more time to look into this. Amazon doesn't officially support shrinking of root volumes. But there are some ways around it which I have tried. The last option would be to create a new ec2 with the right size volume, install the software/tools on it again. 
The current volume continues to be the single most expensive cloud resource we are paying for at 400$/mo.

**Comment by lauraclarke** [comment]
@prabh-t what is the current status here, can this be moved to DONE

**Comment by prabh-t** [comment]
Created new ticket for the last item in the list above and marking this one as done.
https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-dev-team/377
