### ISSUE TITLE
Cleanup old Mongodb backups

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-dev-team#355]
https://github.com/ebi-ait/hca-ebi-dev-team/issues/241 has defined a 90 day expiration policy on mongodb backups.

It seems like backups created before this flag was set aren't being cleaned up which makes sense

It would be good to get rid of any backups we don't need

@MightyAx has set the July 11th 2020 backup to be retained, this should not be deleted.

All other backups created before August 19th should be cleaned up

- [x] mongodb backups in ingest-db-backup created on or before August 19th (excluding July 11th 2020) have been deleted

**Comment by prabh-t** [comment]
actually this will happen once we have redeploy the backup cronjob on the cluster. so files older than 90 days will get cleared up except for the one that have been marked as retained (auto-delete: false). anyway I have deleted old files manually for now.
