### ISSUE TITLE
Investigate 100k Elixir requests

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#358]
Email from Elixir AAI:

> We have noticed a lot of requests coming in from some amazon IPs and blocked them.
> Please check your service configuration, currently, it is generating 100k requests per day on the JWKs endpoint. I have allowed the IPs again, but this needs to be fixed.
>

Majority of the auth requests is coming from the UI when it does the:

1. Polling from UI pages every 5 seconds~ and it doesn't stop when there's an auth error 

```
5 seconds on submissions
4 seconds on my-projects
10 seconds on submissions list
```

The ticket already created and being worked on by @jacobwindsor : ebi-ait/dcp-ingest-central#99

2.  Several requests to different endpoints to get data

- In the submission dashboard, there's a request to get a project for every submission envelope  ( GET `/submissionEnvelopes/ID/relatedProjects`)

   This could be improved if the submission can have the project information when it's being retrieved.

    I won't create a ticket for this as this may no longer be necessary as we are planning to move away from making submissions visible to the users.

- In the process graph view, in the submission details page > process tab, for every process, the protocols, input biomaterials, derived biomaterials and derived files are being requested separately. 

    This could be improved if the submission can have all the linking information from the process endpoint.

    ebi-ait/dcp-ingest-central#100

3. Most of the GET requests don't require a token, but we're passing it for every requests
We could identify and configure to only pass tokens for the secured endpoints

4. Cache account info
Could cache and invalidate only upon logout. Should there be changes done to the account, the user should log in again.

5. Implement websockets instead of doing polling

**Comment by rdgoite** [comment]
This is most likely with the way we are verifying tokens. Every request (I think not just the authenticated ones) that gets sent to the core invokes the Elixir AAI endpoint to verify the token.

While this by itself is a problem, I think the UI has a very aggressive logic of staying up to date by using a polling strategy. This is multiplied by the fact that each refresh of the page can potentially span several back and forth with the Core. Even if we've solved the problem with Elixir, the traffic from the UI would still keep on hammering the backend.

The ideal scenario here would be for updates to be pushed rather than pulled.

**Comment by aaclan-ebi** [comment]
Thanks @rdgoite . 

@jacobwindsor did recently suggest using web sockets. https://embl-ebi-ait.slack.com/archives/C016R78CDV1/p1606308198280400?thread_ts=1606307538.280300&cid=C016R78CDV1

This also has been thought of  before just never got a chance to actually implement it. 

I think the polling refactoring to use datasources would help once we decided to implement the web sockets.

**Comment by jacobwindsor** [comment]
Hi @rdgoite, thanks for the input, and @aaclan-ebi for writing all this down.

Yes, refactoring to make the polling happen in one place will mean the WebSockets can also easily be implemented in one place. I'm hiding the implementation of keeping data sources up-to-date from the components that actually use them. Basically, just use a data source in a component and it will emit the latest data - for now with polling but hopefully with web sockets at some point.

**Comment by lauraclarke** [comment]
@aaclan-ebi as this has moved to resolution in the development cycle is this ticket needed anymore?

**Comment by jacobwindsor** [comment]
@lauraclarke This needs QA as there's a lot of things the refactor touches. I have made a checklist of things to check in the PR: https://github.com/ebi-ait/ingest-ui/pull/75

I will go through this list with @mshadbolt

**Comment by aaclan-ebi** [comment]
We can track the QA in that ticket. Closing this ticket now.
