### ISSUE TITLE
S3 upload area size report failing

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-dev-team#360]
*** This email may not be who they appear to be. For further information please visit the TSC intranet's cyber safety page. *** 

Here is a summary of your space usage on the WranglerTools EC2 (/home) and the attached file system (/data):
28G	/home
4.5G	/home/aday
323M	/home/alegria
172K	/home/alexie
21G	/home/eventura
1.2G	/home/mshadbolt
631M	/home/rstefancsik
541M	/home/ubuntu
659G	/data

S3 hca-util-upload-area summary

Top 5 upload areas

Error: Couldn't retrieve summary

Not sure where this is running so why this failed

**Comment by lauraclarke** [comment]
There are also questions to be asked about if this is the best approach and if the two different emails sent right now to devs and wranglers is the best approach?

**Comment by clairerye** [comment]
Not clear that we want to do anything with this so closing for now
