### ISSUE TITLE
Investigate slowness in file validation

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#364]
Wranglers have been reporting that there's a slowdown in file validation. We don't have a data to compare with but would be nice to learn what's happening between when a file is uploaded until when it starts validating and if there's a bottleneck there.

https://embl-ebi-ait.slack.com/archives/C014HMTV0FN/p1606929824184300

**Comment by aaclan-ebi** [comment]
I think this has a low priority now, as there's no urgent need to export/ingest any datasets atm.

**Comment by clairerye** [comment]
Closing for now, if this issue occurs again we can put a ticket in the development board.
