### ISSUE TITLE
Security vulnerability on HCA AWS resources

### ISSUE THREAD

**Issue by prabh-t** [ebi-ait/hca-ebi-dev-team#367]
The vulnerabilities below were reported by the cloud consultants. We need to assess each and determine if they are intended, if not, find out how to fix them.

**Comment by prabh-t** [comment]
Hi HCA team,

I hope I am mailing to correct group. We recently ran Security Scan on our AWS infrastructure on Security Hub and found some critical findings on HCA resources that might pose serious security threat. Please check the below scan findings and act as necessary,

1. S3.2 S3 buckets should prohibit public read access

    Description:
        This AWS control checks whether your S3 buckets allow public read access by evaluating the Block Public Access settings, the bucket policy, and the bucket access control list (ACL).

    Affected:
    - arn:aws:s3:::schema.dev.archive.data.humancellatlas.org
    - arn:aws:s3:::schema.archive.data.humancellatlas.org

    Remediation:
    - https://docs.aws.amazon.com/console/securityhub/S3.2/remediation

2. RDS.2 RDS DB Instances should prohibit public access, determined by the PubliclyAccessible configuration

    Description:
        This AWS control checks whether RDS instances are publicly accessible by evaluating the publiclyAccessible field in the instance configuration item.

    Affected:
    - arn:aws:rds:us-east-1:871979166454:db:upload-cluster-prod-0
    - arn:aws:rds:us-east-1:871979166454:db:upload-cluster-dev-0
    - arn:aws:rds:us-east-1:871979166454:db:upload-cluster-staging-0

    Remediation:
    - https://docs.aws.amazon.com/console/securityhub/RDS.2/remediation

Please check the above resources and let us know once it has been resolved. In some edge case if it is intended to be used in that way, please let us know so that we can suppress the finding from scan result. We will share the less severe findings afterwards once these has been dealt with.

Thanks,
Sammy
Cloud Consultant Team

**Comment by prabh-t** [comment]
Hi Sammy

Thank you for your email raising these alerts.
We need to investigate further on our end, what I can say for now,

1. these buckets have public access as their contents are served via cloudfront.
2. the 2 publicly accessible rds instances are non-prod DBs which are permitted to allow local client to connect to them directly.

In both cases, there may be alternative configuration possible which we will look into.

Regards
Prabhat

**Comment by prabh-t** [comment]
Also, some s3 buckets are deliberately public,
I’ve only skimmed the problem but this might be useful: https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/78#issuecomment-667943002

Alexie Staffer

**Comment by prabh-t** [comment]
Hi Prabhat,

Thanks for looking into it. Following are my suggestions,

1. I can suggest looking into this article for restricting s3 access to cloudfront.
2. Have you considered running DBs in VPC and have an instance as a bastion server to connect with them.

My suggestions are based on industry best practices and without any knowledge on your application. I strongly recommend to check AWS Well-Architected Framework service and review your workload.

Regards,
Sammy

**Comment by prabh-t** [comment]
Hi HCA Team,

Adding to what we shared previously, there are some high security issues in your resources that you need to verify.

    S3.6 S3 permissions granted to other AWS accounts in bucket policies should be restricted

    Description: This control checks whether the S3 bucket policy allows sensitive bucket-level or object-level actions from a principal in another AWS account. The control fails if any of the following actions are allowed in the S3 bucket policy for a principal in another AWS account: s3:DeleteBucketPolicy, s3:PutBucketAcl, s3:PutBucketPolicy, s3:PutObjectAcl, and s3:PutEncryptionConfiguration.
    Affected Resource:
        arn:aws:s3:::hca-ncbi-cloud-data-r
        arn:aws:s3:::hca-ncbi-cloud-data-eventura 
        arn:aws:s3:::hca-ncbi-cloud-data
    Remediation: https://docs.aws.amazon.com/console/securityhub/S3.6/remediation

    4.1 Ensure no security groups allow ingress from 0.0.0.0/0 to port 22
        Description: Security groups provide stateful filtering of ingress/egress network traffic to AWS resources. It is recommended that no security group allows unrestricted ingress access to port 22.
        Affected Resource: 
                                                               i.      hca-wrangler-tools-ec2 - sg-088999e2c00b4c299 (inbound-ssh-from-anywhere)
                                                             ii.      ingest-eks-prod -  sg-0c6aca9495b9a697d (ingest-eks-node-prod)   (Only security groups of Production is enlisted, similar for non-prod)
        Remediation:
                                                               i.      https://docs.aws.amazon.com/console/securityhub/standards-cis-4.1/remediation

Again as previously stated, please check the above resources and let us know once it has been resolved. In some edge case if it is intended to be used in that way, please let us know so that we can suppress the finding from scan result.

Thanks,
Sammy

**Comment by aaclan-ebi** [comment]
I've blocked all public access for the following buckets:

schema.archive.data.humancellatlas.org
schema.dev.archive.data.humancellatlas.org

I see that there are bucket policies for the following buckets, i think it should be safe to also block public access to these:
arn:aws:s3:::hca-ncbi-cloud-data-r
arn:aws:s3:::hca-ncbi-cloud-data-eventura
arn:aws:s3:::hca-ncbi-cloud-data

@ESapenaVentura @rays22 Please confirm if you are the owner of these buckets, I've blocked public access to these buckets, please let me know if you see any issues.

**Comment by rays22** [comment]
Yes, these are our buckets to receive data from NCBI cloud services.

**Comment by amnonkhen** [comment]
@aaclan-ebi I see you worked on this issue in the past.
Is there anything left to do here?

**Comment by aaclan-ebi** [comment]
- [ ] [S3.2 S3 buckets should prohibit public read access](https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-dev-team/367#issuecomment-745275988) -- This is done last [5th Jan](https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-dev-team/367#issuecomment-754814436)

```
arn:aws:s3:::schema.dev.archive.data.humancellatlas.org
arn:aws:s3:::schema.archive.data.humancellatlas.org
```

- [ ] [RDS.2 RDS DB Instances should prohibit public access, determined by the PubliclyAccessible configuration](https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-dev-team/367#issuecomment-745275988)
```
arn:aws:rds:us-east-1:871979166454:db:upload-cluster-prod-0
arn:aws:rds:us-east-1:871979166454:db:upload-cluster-dev-0
arn:aws:rds:us-east-1:871979166454:db:upload-cluster-staging-0
```

- [ ] [S3.6 S3 permissions granted to other AWS accounts in bucket policies should be restricted](https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-dev-team/367#issuecomment-748167675) -- This is done last [5th Jan](https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-dev-team/367#issuecomment-754814436)

```
arn:aws:s3:::hca-ncbi-cloud-data-r
arn:aws:s3:::hca-ncbi-cloud-data-eventura
arn:aws:s3:::hca-ncbi-cloud-data
```

- [ ] [4.1 Ensure no security groups allow ingress from 0.0.0.0/0 to port 22](https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-dev-team/367#issuecomment-748167675)

```
hca-wrangler-tools-ec2 - sg-088999e2c00b4c299 (inbound-ssh-from-anywhere)
ingest-eks-prod - sg-0c6aca9495b9a697d (ingest-eks-node-prod) (Only security groups of Production is enlisted, similar for non-prod)
```

**Comment by clairerye** [comment]
closing this as Alegria has made tickets for the remaining tasks
