### ISSUE TITLE
Investigate further Elixir AAI to assess complexity of using as an Ingest auth solution

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#37]
**Acceptance Criteria**
* [x] We have some idea of how complex (how many points or engineering days) it would take to incorporate Elixir AAI as our authentication solution. Timebox is 1 day.
* [x] This investigation is written up in [the main ingest auth doc](https://docs.google.com/document/d/1KVYX4zI81P4UoB4eAysUUr5GcktGFhcGbRYJ92bjJ-g/edit#)

**Comment by aaclan-ebi** [comment]
Added information on how to integrate with Elixir AAI in the main document https://docs.google.com/document/d/1KVYX4zI81P4UoB4eAysUUr5GcktGFhcGbRYJ92bjJ-g/edit#heading=h.3qpg1jk4hz06

**Comment by aaclan-ebi** [comment]
I believe investigation is enough to provide feasibility of integration.I think the registration for scopes to our test client can be a prerequisite before we start the implementation.
