### ISSUE TITLE
Fix ingest issues due to DCP1 accounts retirement

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#370]
1. (Done) Use hca-util in integration tests
   - DCP1 hca cli no longer works because DSS API is not accessible
2. (Done) Configure new service accounts in Ingest components
   Components which uses GCP service accounts:
      - Ingest Integration tests (done)
      - Upload service (incomplete)
      - Archiver (verify)
3. (Done) Recreate AMI's

**Comment by aaclan-ebi** [comment]
Looks like there's a conflict between the integration test's boto3 version (from awscli) and hca-util's boto3 version. I'm going to look into fixing it first.

**Comment by aaclan-ebi** [comment]
I'm seeing the following error when running hca-util
```
output: An exception of type ClientError occurred in command create.
Detail: An error occurred (MalformedPolicy) when calling the PutBucketPolicy operation: Normalized policy document exceeds the maximum allowed size of 20480 bytes
, error:
```

**Comment by aaclan-ebi** [comment]
I've finished the changes in the integration tests and upon testing my changes I  found another issue on the upload service. It looks like our instance of the upload service is using AMI's from the old DCP AWS account. Those are deleted and now the state of our compute environments in AWS are invalid. I found a documentation on how to create these AMI in the upload service repo https://github.com/ebi-ait/upload-service/tree/master/amis.

This upload service issue is affecting file validation. I will try to work on this tomorrow.

**Comment by aaclan-ebi** [comment]
The missing AMI was successfully recreated in our EBI AWS account (will document the steps in the ticket) and the upload service configuration was updated to point to this. File validation should now be working. 

However, my local testing of the integration test changes is still not passing. It seems that there is a problem in setting the content type in the hca-util. Ingest is not being notified and file validation is not being triggered if the content type `dcp-type=data` is not set. I will take a look tomorrow. Copying @prabh-t if ever you have any ideas, Thanks!

**Comment by aaclan-ebi** [comment]
I've debugged this and I'm pretty sure `dcp-type=data` is being set in the content type and we're passing it in boto3's  s3 [copy](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.copy) function. However it seems that the problem is happening in the actual transfer or maybe the underlying boto3 codebase. Will investigate more...

**Comment by aaclan-ebi** [comment]
Decided to use the same fastq file for `SRR3562314_2.fastq.gz` for the integration test. I am still unsure why the original `SRR3562314_2.fastq.gz` is not being assigned with a content type. Will investigate further if this happens again in the future. My local testing is now passing. Will push changes to dev.

**Comment by ESapenaVentura** [comment]
@aaclan-ebi is the assignment of a content-type being done when moving data to the ingest-upload areas or when moving data to the first bucket?

I've had my fair share of issues trying to upload data that was uploaded with my scripts to ingest buckets, and I think it was because the content type is set up when you first upload files with the hca-util to an hca-util area

The fastq file that is working, how did it get to the bucket? was it uploaded with the hca-util?

**Comment by aaclan-ebi** [comment]
The upload area `3125f4a0-dda1-40c6-ab69-d27f795f08e1` in hca-util was set up long time ago, i couldn't remember how i transferred the 2 test files there. It's strange because only the first file is being set with the correct content type. I was looking at the hca-util. It looks like it adds the content-type `dcp-type=data`  upon uploading and also adds the content type upon copying/syncing to ingest upload area if it's not yet there.

**Comment by aaclan-ebi** [comment]
By the way, @ESapenaVentura, do you know where i can get a smaller set of paired fastq files? I'm currently using 2 same fastq files atm in our integration tests (since we dont do paired fastq validation in Ingest yet). The size is 800MB each. I worry it will accumulate since we don't auto cleanup upload areas when we delete submissions yet. (I might set this up soon once i get a chance) It would be nice to get a smaller valid set of fastq files.

**Comment by ESapenaVentura** [comment]
you can actually generate them, they will be valid as long as they comply with the format 

you can create them with this little script, just make sure you get the name right https://github.com/ebi-ait/hca-ebi-wrangler-central/blob/master/src/get_dummy_fastq.py

**Comment by aaclan-ebi** [comment]
Cool! I'll use that! thanks @ESapenaVentura !

**Comment by aaclan-ebi** [comment]
All fixes were merged and promoted to all environments and Ingest integration tests are passing now.
