### ISSUE TITLE
hca-util has MalformedPolicy error 

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#372]
```
output: An exception of type ClientError occurred in command create.
Detail: An error occurred (MalformedPolicy) when calling the PutBucketPolicy operation: Normalized policy document exceeds the maximum allowed size of 20480 bytes
, error:
```

slack thread: https://embl-ebi-ait.slack.com/archives/C014HMTV0FN/p1610386477142000

**Comment by aaclan-ebi** [comment]
@prabh-t is now looking into this.

**Comment by clairerye** [comment]
@ami-day will test this when its ready

**Comment by prabh-t** [comment]
@ami-day v0.2.13 of the tool is ready for testing.

**Comment by ami-day** [comment]
@prabh-t @clairerye I tested the hca-util create argument and upload areas are now created without the error message. Is there anything else I should test? I'm not sure exactly how to test the policy limit without individually creating hundreds of new upload areas then deleting them again. Is that necessary?

**Comment by clairerye** [comment]
Thanks @ami-day! No need to try and test the policy limit! If you could (and I guess you will be doing this for the archiving) just check that the normal functions such as the sync command work as expected that would be brilliant.

**Comment by ami-day** [comment]
ok, sounds good. I think we could just test each available type of command as there aren't many. If we type hca-util --help it will show the available options so I don't think we need to document this.

**Comment by ami-day** [comment]
Ok @clairerye and @prabh-t all of the options (upload,sync,delete) work so I am closing this ticket. Is it worth moving the ticket about enabling the use of wildcards and selection of individual files to development now this test is done? or is that for another sprint?
