### ISSUE TITLE
Shrink Wrangler EBS volume

### ISSUE THREAD

**Issue by prabh-t** [ebi-ait/hca-ebi-dev-team#377]
The current volume continues to be the single most expensive cloud resource we incur at 400$/mo. We now have EFS setup and mounted on the EC2 so we do not need a super large EBS.

Two previous attempts to shrink the ebs have failed so far. After copying over the current 4TB volume to a 400GB, the ec2 won't start. We need more time to look into this. Amazon doesn't officially support shrinking of root volumes. But there are some ways around it which I have tried. The last option would be to create a new ec2 with the right size volume, install all the software/tools on it again, add users, and then delete the old ec2 and volume.

Ref: https://www.falexandrou.com/2018/02/14/downsizing-root-ebs-volume/

This ticket is the last item from [#352](https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-dev-team/352) as part of the AWS cost reduction measures.

[Cost reduction in AWS - plan and tracking costs](https://docs.google.com/document/d/1RTtpY3QxGBNcUnvRKA9hH9nJGeSX0t1KmI9k0k2pdHU/edit)

**Comment by clairerye** [comment]
I think we should leave this for now and come back to it if we are concerned about the regular cloud costs
