### ISSUE TITLE
Fix project linking in prod

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#382]
Fixes issue from a db migration on this ticket https://github.com/ebi-ait/dcp-ingest-central/issues/90
see comment: https://github.com/ebi-ait/dcp-ingest-central/issues/90#issuecomment-775337675

**Comment by aaclan-ebi** [comment]
This is blocking https://github.com/ebi-ait/dcp-ingest-central/issues/219

I've got a script to fix the issue which I plan to run on monday.

**Comment by aaclan-ebi** [comment]
Planning to run this against prod DB on Tues after the DCP4 (March release) cutoff

**Comment by aaclan-ebi** [comment]
The migration script was run in prod last week. It took 2 days to run. For simplicity, I ran this in my local machine and by port-forwarding to mongo prod server. This should be safe as the script can just run and stopped anytime. We should think of a better way to run data operations/migrations like this this next time.

**Comment by lauraclarke** [comment]
How likely do you think we will have to have to this again?

**Comment by aaclan-ebi** [comment]
I believe it's very likely. We might need this to run the migration scripts for every major schema release. Migrations can also be necessary as we develop new features. The data will grow larger and migrations will take longer so we need a better way to run scripts like this.

**Comment by lauraclarke** [comment]
great, sounds like something that needs to be captured from a requirements perspective on the product dev board can you work with @clairerye to make sure this happens, obviously if you have already done that, fantastic, don't need to repeat

**Comment by aaclan-ebi** [comment]
No, I haven't done it yet. Will create a ticket. Thanks!
