### ISSUE TITLE
HCAO 1.0.21 Release

### ISSUE THREAD

**Issue by zoependlington** [ebi-ait/hca-ebi-dev-team#387]
The [HCA Ontology release 1.0.20](https://github.com/ebi-ait/ontology/releases/tag/1.0.20) is out and and needs to be picked up. Tag should also be available automatically on Quay.io.

Could the OLS instance/EBI environment be reloaded and the validator cache cleared please?

Thank you!

**Comment by aaclan-ebi** [comment]
@zoependlington could you put the new version for March release in this ticket once it's ready? Looks like we'll just wait for that one before we redeploy our OLS instance to pick up the new values.

**Comment by zoependlington** [comment]
@aaclan-ebi Sure! We'll be releasing this afternoon so I'll comment with the updated links when it's done. Thanks!

**Comment by aaclan-ebi** [comment]
Thanks, @zoependlington !

**Comment by zoependlington** [comment]
@aaclan-ebi The new release is available here: https://github.com/ebi-ait/ontology/releases/tag/1.0.21 

Thanks!

**Comment by aaclan-ebi** [comment]
Thanks @zoependlington , i've deployed it in our [dev](https://ontology.dev.archive.data.humancellatlas.org/index) and [staging](https://ontology.dev.archive.data.humancellatlas.org/index) instance. Will promote tomorrow to [prod](https://ontology.archive.data.humancellatlas.org/index)

**Comment by aaclan-ebi** [comment]
Deployed to prod, our integration tests are passing.

Thanks again @zoependlington !
