### ISSUE TITLE
Use ingest gitlab runner instead of custom docker image for deployment pipelines

### ISSUE THREAD

**Issue by prabh-t** [ebi-ait/hca-ebi-dev-team#39]
The `ingest-kube-deployment` project in Gitlab currently uses a custom built docker image with user (prabhat's) credentials from a private registry.

We now have an ingest gitlab runner configured with an IAM role/running in the EBI AWS acc. We need to install the required tools for deployment in the same runner and use it for deployment instead of the docker image.

Acceptance criteria
[ ] use ingest gitlab runner instead of custom docker image for deployment pipelines

**Comment by prabh-t** [comment]
We now have our GitLab runner set up and deployment pipeline is using it.
Documented [here](https://docs.google.com/document/d/1_aeMhnqX5hb6hwZeutTY_moBBKrMkpIoCAETJIemc7M/edit).

**Comment by aaclan-ebi** [comment]
Moving to done!
