### ISSUE TITLE
Investigate why AllelicExpressionPatterns submission is stuck in exporting

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#392]
https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1614766615077100?thread_ts=1614287134.026300&cid=C9XD6L0AD

project: AllelicExpressionPatterns
project uuid: ccef38d7-aa92-4010-9621-c4c7b1182647

https://contribute.data.humancellatlas.org/projects/detail?uuid=ccef38d7-aa92-4010-9621-c4c7b1182647

**Comment by aaclan-ebi** [comment]
Looks like this got resolved on its own. It might have been retried when the exporter was redeployed yesterday/today. The submission state is now Exported.

**Comment by lauraclarke** [comment]
Can this ticket be moved to Done?

**Comment by aaclan-ebi** [comment]
Yup, Paris resolved her comment in the data tracker as well.
