### ISSUE TITLE
Delete project that has been replaced with new project

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-dev-team#393]
A project was recently exported but then needed 100s of changes that weren't feasible in the UI. 

The original project needs to be deleted in ingest and in the staging area.

Project to be deleted: `9963d872-3ec0-4a89-9f28-ca5ffe2182d3`

Acceptance criteria:
- [x] ensure the new project exported correctly `23587fb3-1a4a-4f58-ad74-cc9a4cb4c254`
- [x] `9963d872-3ec0-4a89-9f28-ca5ffe2182d3` project, submission and data files deleted from staging area
- [x] `9963d872-3ec0-4a89-9f28-ca5ffe2182d3` project, submission and data files deleted from ingest

tagging @aaclan-ebi and @clairerye

**Comment by mshadbolt** [comment]
I think I should have probably tagged @amnonkhen as he is the developer on Operations. Do you have capacity to take on this task as an ops priority? Or if I got it wrong and someone else is the ops dev please tag them here. Thanks.

**Comment by aaclan-ebi** [comment]
Removed files by running:

```
gsutil -m rm -r gs://broad-dsp-monster-hca-prod-ebi-storage/prod/9963d872-3ec0-4a89-9f28-ca5ffe2182d3
```

Output:

```
...
Removing gs://broad-dsp-monster-hca-prod-ebi-storage/prod/9963d872-3ec0-4a89-9f28-ca5ffe2182d3/metadata/specimen_from_organism/8ca18090-3f25-42b5-813e-f6d2d84664d4_2021-02-23T18:48:19.295000Z.json#1614108370200298...
Removing gs://broad-dsp-monster-hca-prod-ebi-storage/prod/9963d872-3ec0-4a89-9f28-ca5ffe2182d3/metadata/specimen_from_organism/a522a580-6050-4406-9c73-1f2d0ce66c05_2021-02-23T18:48:19.315000Z.json#1614108928148518...
Removing gs://broad-dsp-monster-hca-prod-ebi-storage/prod/9963d872-3ec0-4a89-9f28-ca5ffe2182d3/metadata/specimen_from_organism/cafa789f-0ce8-4150-8a22-f4c05c406ab7_2021-02-23T18:48:19.324000Z.json#1614108851904020...
Removing gs://broad-dsp-monster-hca-prod-ebi-storage/prod/9963d872-3ec0-4a89-9f28-ca5ffe2182d3/metadata/specimen_from_organism/d91241e7-20ff-47a3-bbac-2c07dd5582cf_2021-02-23T18:48:19.265000Z.json#1614108101615041...
Removing gs://broad-dsp-monster-hca-prod-ebi-storage/prod/9963d872-3ec0-4a89-9f28-ca5ffe2182d3/metadata/specimen_from_organism/cb0314d2-6dea-498f-8e0a-62f1cbee46a2_2021-02-23T18:48:19.305000Z.json#1614108958635130...
/ [14.8k/14.8k objects] 100% Done 122.81 objects/s ETA 00:00:00
Operation completed over 14.8k objects.
```
