### ISSUE TITLE
Is it possible to retrigger schema validation in the ingest system

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-dev-team#400]
Goal: We want to rerun schema validation on existing and already exported projects in ingest to capture new errors based on extra schema validation added to the schema

This does not need to be automated, just possible to manually trigger

@yusra-haider can you investigate how this might work and what if any changes are needed to ingest to make it possible and then we can decide if we want to do it or not

#acceptance criteria

- [ ] the steps needed to revalidate is established
- [ ] decision made if this should be done when the new checks from Enrique/Ami are defined. No is a legitimate decision. Need to understand why

**Comment by MightyAx** [comment]
Specifically JSON Schema, not graph validator
Is it possible to trigger manually? How?

**Comment by lauraclarke** [comment]
@MightyAx just remembered, the issue caused by the error in the file_format field also meant that file_validation didn't happen

Understanding if we know if file validation happened and if it didn't can be trigger it would also be good see here for a bit more information about the specific validation error which lead to this ticket https://github.com/ebi-ait/dcp-ingest-central/issues/266

**Comment by lauraclarke** [comment]
closing as it has been decided it would be better to leave this now and instead do this investigation alongside a schema change which would prompt revalidation as it is likely some sort of migration strategy would also be needed which might change how we want to do the validation
