### ISSUE TITLE
Ensure no security groups allow ingress from 0.0.0.0/0 to port 22

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#402]
*Overview*

        4.1 Ensure no security groups allow ingress from 0.0.0.0/0 to port 22
        
        Description: Security groups provide stateful filtering of ingress/egress network traffic to AWS resources. It is recommended that no security group allows unrestricted ingress access to port 22.
        
        Affected Resource:
        
        hca-wrangler-tools-ec2 - sg-088999e2c00b4c299 (inbound-ssh-from-anywhere)
        ingest-eks-prod - sg-0c6aca9495b9a697d (ingest-eks-node-prod) (Only security groups of Production is enlisted, similar for non-prod)
        
        Remediation: https://docs.aws.amazon.com/console/securityhub/standards-cis-4.1/remediation

*Issue Classification*
Other, Security Vulnerability

*Additional references*
https://github.com/ebi-ait/hca-ebi-dev-team/issues/367

**Comment by jacobwindsor** [comment]
We cannot do this on hca-wrangler-tools-ec2 since we need to SSH into it from any location. A workaround is to require every person to use the EBI VPN for logging into the EC2 instance and we only allow requests from the EBI IPs. @clairerye

**Comment by jacobwindsor** [comment]
I have removed port 22 access for ingest-eks-staging and ingest-eks-prod. ingest-eks-dev did not allow it anyway

**Comment by clairerye** [comment]
I don't think I understand what is going on here. Maybe we can have a quick chat, if I need to be aware of whats going on :)

**Comment by clairerye** [comment]
Thanks @jacobwindsor! Yep, makes sense, if we don't need to do anything, even better!

**Comment by jacobwindsor** [comment]
I will mark this as done then. We can revisit this if we decide we want to tighten security on the EC2 instance
