### ISSUE TITLE
Limit access of Terra staging area to Ingest Google group

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#405]
I'm adding a ticket since ideally we shouldn't be using the ingest exporter service account in the SOP to access the staging area 

SOP: https://ebi-ait.github.io/hca-ebi-dev-team/admin_setup/Setting-up-access-to-Terra-staging-area.html

@ESapenaVentura has started the conversation on this before. I'm not sure what's the update on it. 

I think we have access to EBI's GCP account and we can create a google group by ourselves. We can create our own group and add devs and wranglers there and ask Raaid to grant Terra staging buckets access for that group.

**Comment by mshadbolt** [comment]
Enrique previously emailed Raaid and I believe the access has been set up to work from the [ingest google group](https://groups.google.com/a/data.humancellatlas.org/g/ingest-team)

I updated that documentation to reflect that anyone added to that group should get access

I assumed that the group has read access only but not 100% sure on that.

**Comment by clairerye** [comment]
I understand this is done, so closing
