### ISSUE TITLE
Investigate dev and staging integration tests are failing

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#408]
There's an error in starting validation batch jobs which seems to be only happening in dev and staging env. https://console.aws.amazon.com/batch/v2/home?region=us-east-1#jobs/detail/adef89c0-0304-4661-9930-81f98c5d3dbe

```
CannotPullContainerError: Error response from daemon: pull access denied for provide_through_set_flag, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by aaclan-ebi** [comment]
Forgot to say that dev and staging environments are actually broken as well. And this is blocking product development.

**Comment by MightyAx** [comment]
I don't understand how this is an operations task, (dev and staging are product development environments)
I also don't know how to fix it
@aaclan-ebi?
