### ISSUE TITLE
[Client] Refactor Out Exporter Logic

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#41]
- Fork ingest client repository to ebi-ait organisation.
- Remove Exporting Logic from ingest-client.
- Remove references to DataStore API from ingest-client.

**Comment by aaclan-ebi** [comment]
This can be done later and not part of archiving epic.

**Comment by MightyAx** [comment]
true... ish
The exporter still needs an ingest-client for staging service, ingest-api ect.
The duplication of module names might get a bit weird.

Not doing the work is technical debt, but it's not urgent.

**Comment by MightyAx** [comment]
This branch might be useful for anyone looking at this work.
https://github.com/ebi-ait/ingest-client/tree/feature/remove-dss-exporter
