### ISSUE TITLE
UCSC Project 455f file not recognised [Staging]

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-dev-team#412]
https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/306

^see above issue

Product UUID: 58d8b65f-9a4e-455f-8053-35bdf4065773
Submission UUID: fbf442d4-b74b-4196-95c7-1a81d424bfc4
File UUID: e7397962-9868-4682-9436-dfced927237d
Slack Notification: https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1618872729138200

**Comment by aaclan-ebi** [comment]
Aww, there's actually no need to create this issue since Alexie already created the issue. I was just advising to file issues going forward. We can close this now.
