### ISSUE TITLE
HCAO Release 1.0.25

### ISSUE THREAD

**Issue by zoependlington** [ebi-ait/hca-ebi-dev-team#422]
The [HCA Ontology release 1.0.25](https://github.com/ebi-ait/ontology/releases/tag/1.0.25) is out and and needs to be picked up. Tag should also be available automatically on Quay.io.

Could the OLS instance/EBI environment be reloaded and the validator cache cleared please?

Thank you!

Tagging @pnejad and @paolaroncaglia to keep in the loop.

**Comment by amnonkhen** [comment]
@yusra-haider see [the SOP](https://ebi-ait.github.io/hca-ebi-dev-team/operations_tasks/HCAO-release.html)

**Comment by yusra-haider** [comment]
updating OLS on dev env to `1.0.25`:

```
kubectl get deployment ontology -o yaml | grep image
 - image: quay.io/ebi-ait/ontology:1.0.25
        imagePullPolicy: Always
```

redeployed validator on ingest:

```
kubectl get deployment ingest-validator -o yaml | grep image
        image: quay.io/ebi-ait/ingest-validator:dev-b85afbc3-28-04-2021.1619630866
        imagePullPolicy: Always

make deploy-app-ingest-validator image=quay.io/ebi-ait/ingest-validator:dev-b85afbc3-28-04-2021.1619630866
```

**Comment by yusra-haider** [comment]
updating OLS on staging env to `1.0.25`

```
kubectl get deployment ontology -o yaml | grep image
      - image: quay.io/ebi-ait/ontology:1.0.25
        imagePullPolicy: Always
```

redeployed validator on staging ingest:

```
kubectl get deployment ingest-validator -o yaml | grep image
        image: quay.io/ebi-ait/ingest-validator:staging-3351ef15-05-05-2021.1620199634
        imagePullPolicy: Always

make deploy-app-ingest-validator image=quay.io/ebi-ait/ingest-validator:staging-3351ef15-05-05-2021.1620199634
```

**Comment by yusra-haider** [comment]
Running the integration tests via gitlab for dev and staging.

**Comment by yusra-haider** [comment]
integration tests passed on `dev`

**Comment by yusra-haider** [comment]
integration tests passed on `staging`

**Comment by yusra-haider** [comment]
updating OLS on prod env to 1.0.25

```
kubectl get deployment ontology -o yaml | grep image
      - image: quay.io/ebi-ait/ontology:1.0.25
        imagePullPolicy: Always
```


redeployed validator on prod ingest:

```
make deploy-app-ingest-validator image=quay.io/ebi-ait/ingest-validator:prod-3351ef15-05-05-2021.1620218156

kubectl get deployment ingest-validator -o yaml | grep image
        image: quay.io/ebi-ait/ingest-validator:prod-3351ef15-05-05-2021.1620218156
        imagePullPolicy: Always
```

**Comment by yusra-haider** [comment]
Running the integration tests via gitlab for prod

**Comment by yusra-haider** [comment]
integration tests passed on prod

**Comment by yusra-haider** [comment]
PR for ingest kube changes raised here: https://github.com/ebi-ait/ingest-kube-deployment/pull/24
