### ISSUE TITLE
Download PRJEB38269 fastq files

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#432]
currently downloading files to /nfs/production/hca/alegria/PRJEB38269/

I will upload to 727238ba-76c0-4bd5-a5e2-18561f549e6d hca-util upload area once downloading is finished

FYI @ami-day

**Comment by aaclan-ebi** [comment]
I'm now uploading this to hca-util upload area 1268551e-f2d0-43eb-9511-968e46901e72 which ami originally used for this dataset : ebi-ait/hca-ebi-wrangler-central/issues#265

**Comment by Wkt8** [comment]
@aaclan-ebi is this now complete? Can it be moved to Finished?

**Comment by aaclan-ebi** [comment]
yup the files are in this hca-util upload area : `s3://hca-util-upload-area/1268551e-f2d0-43eb-9511-968e46901e72/`
