### ISSUE TITLE
Ontology base image version upgrade

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#434]
We've had issues before where there are some endpoints in the HCA Ontology service https://ontology.archive.data.humancellatlas.org/index  wouldn't return same result as the https://www.ebi.ac.uk/ols/index. According to the SPOT team, this might be because we are using an outdated ontology base image version.

From meeting with David Osumi and James(?) from SPOT team, they've given the following instructions before on how to do this:

1. Fork https://github.com/EBISPOT/ontotools-docker/tree/master/config 
2. Copy config from https://github.com/ebi-ait/ontology/tree/master/ols
3. These 2 files:obo-config.yaml ols-config.yaml -- change the two files 
4. change `ontology_purl: ` to point to URL pointing GitHub raw OWL file.

**Comment by ami-day** [comment]
@Wkt8 to check with @aaclan-ebi about the status of this

**Comment by Wkt8** [comment]
Karoly is organizing a meeting to discuss what to do on this + give more details.

**Comment by ESapenaVentura** [comment]
@gabsie @amnonkhen

**Comment by ofanobilbao** [comment]
@amnonkhen ?

**Comment by ofanobilbao** [comment]
I will make the call and close this ticket, as we have repeatedly asked if this was still required without an answer, so I am assuming we don't need it anymore
