### ISSUE TITLE
Make sure fastq files will be available in the archives for Peng's additional data

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#435]
The current bam conversion issue where a bam file cannot be converted back to fastq files should have already been fixed in the fastq_utils latest version.  See https://github.com/nunofonseca/fastq_utils/issues/12 for reference.

**Comment by aaclan-ebi** [comment]
Noting here the location of the valid 10x files I could use for testing, thanks @ESapenaVentura for providing me this !
```
s3://hca-util-upload-area/ee4af2bf-bb84-489c-8e84-a54fab986844/WSSS_THYst9384954_S1_L001_I1_001.fastq.gz
s3://hca-util-upload-area/ee4af2bf-bb84-489c-8e84-a54fab986844/WSSS_THYst9384954_S1_L001_R1_001.fastq.gz
s3://hca-util-upload-area/ee4af2bf-bb84-489c-8e84-a54fab986844/WSSS_THYst9384954_S1_L001_R2_001.fastq.gz
```

**Comment by aaclan-ebi** [comment]
Noting the error, I'm getting if i try to use the latest version 0.25 

```
Doing bam conversion for WSSS_THYst9384954_S1_L001_R1_001.fastq.gz WSSS_THYst9384954_S1_L001_R2_001.fastq.gz WSSS_THYst9384954_S1_L001_I1_001.fastq.gz

/app/fastq/bin/fastq2bam: line 13: /dev/stderr: No such device or address

An error occured:  Error: Command failed: /app/fastq/bin/fastq2bam -s 10xV1 -b 60f199fe9da4927ad0bfd0aa.bam -1 WSSS_THYst9384954_S1_L001_R1_001.fastq.gz -2 WSSS_THYst9384954_S1_L001_R2_001.fastq.gz -3 WSSS_THYst9384954_S1_L001_I1_001.fastq.gz
/app/fastq/bin/fastq2bam: line 13: /dev/stderr: No such device or address

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:321:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:321:20)
    at Pipe.<anonymous> (net.js:668:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/app/fastq/bin/fastq2bam -s 10xV1 -b 60f199fe9da4927ad0bfd0aa.bam -1 WSSS_THYst9384954_S1_L001_R1_001.fastq.gz -2 WSSS_THYst9384954_S1_L001_R2_001.fastq.gz -3 WSSS_THYst9384954_S1_L001_I1_001.fastq.gz'
}
Finished
```

**Comment by aaclan-ebi** [comment]
The fastq2bam script is here:https://github.com/nunofonseca/fastq_utils/blob/master/sh/fastq2bam

**Comment by aaclan-ebi** [comment]
Current task: Verify if bam files which are being produced by 0.23 can be converted back to fastq files

**Comment by aaclan-ebi** [comment]
There were issues in building the latest bin files and them in the ingest-file-archiver env. (Todo: note the errors here)

Using conda to download the latest fastq_utils bin files , we also found uncertainty that the bam file is being properly converted back to fastq files (Todo: will add details later) The conda bin file also don't work properly in the ingest-file-archiver env.

Due to this roadblocks in trying to verify if the current or latest bam converter works, we decided to just try submitting the 10x fastq files directly to ENA. See ebi-ait/hca-ebi-wrangler-central#163 for details on this. I will continue to track the work on that in this ticket.

**Comment by aaclan-ebi** [comment]
There were issues in building the latest bin files and them in the ingest-file-archiver env. (Todo: note the errors here)

Using conda to download the latest fastq_utils bin files, we also found uncertainty that the bam file is being properly converted back to fastq files (Todo: will add details later) The conda bin file also doesn't work properly in the ingest-file-archiver env.

Due to these roadblocks in trying to verify if the current or latest bam converter works, we decided to just try submitting the 10x fastq files directly to ENA. See ebi-ait/hca-ebi-wrangler-central#163 for details on this. I will continue to track the work on that in this ticket.

**Comment by ESapenaVentura** [comment]
- [ ] Clean up fastq files after successful submission

**Comment by aaclan-ebi** [comment]
**Updates:**

Testing in dev env (Alegria):
- [ ] 27/07 prep test submission with 10x files https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=6fbcce27-f1ee-4606-a0b4-319f1d13b118
- [ ] 28/07 submit  everything except sequencing run via DSP
- [ ] 28/07 upload test files to ftp upload area using DSP webin creds
- [ ] 27/07 (1st round of testing)it worked
- [ ] 28/07 2nd round because i made adjustments) submit sequencing run using the changes here  https://github.com/ebi-ait/ingest-archiver/pull/40 (WIP because it might need adjustments when tested with  ENA

Run in the prod env- after I finish testing in ENA dev env
- [ ] 28/07 Enrique to modify the sequencing experiments reference to sample alias and study alias  in the new submission per haseeb’s advice: https://submission.ebi.ac.uk/api/submissions/435fac8d-79fa-4c50-966e-3142c1da9df5
- [ ]  28/07 Enrique submit DSP and get sequencing experiment accession
- [ ] 28/07 Upload files to ftp upload area using DSP webin creds (1.17TB transferred in 13 hours)
- [ ] 28/07 md5 checksumming (54/58 files checksummed)
- [ ] 28/07 Alegria run script from 1.d - get run accessions in prod - failed to submit all
- [ ] **28/07 It only submitted 1 sequencing run ERR6383724 for experiment ERX6004813 , ingest manifest id: 60f2a4a6d5d575160aafb78f Either there is a problem with the script or multiple sequencing runs in one submission is not supported. Need to confirm this with ENA. (will continue when I’m back)**
- [ ] Fix the issue, Rerun script excluding the submitted sequencing run 

Please note that the due for this dataset has been extended to 6weeks.

**Comment by ESapenaVentura** [comment]
I have re-run the script:

The issue is that, every time you run "post_files", it will only post the first run. I don't know why is this, but I tried:

- [ ] re-running the script. Ran into the same issue
- [ ] Splitting the jobs by posting same `submission.xml` and different run xmls. Didn't work.
- [x] Completely splitting the job (sample code below, please use this as an indication of how I regenerated the submission.xml every time but let's make it prettier in the PR!)
```
        r = []
        result_xml_tree = []
        for mani in manifest_ids:
            files = ena_api.create_xml_files([mani], '/Users/enrique/HumanCellAtlas/ingest-archiver/ena/md5-EmbryonicHindlimb.txt')
            r.append(requests.post(os.environ.get('ENA_API_URL'), files=files,
                              auth=(os.environ.get('ENA_USER'), os.environ.get('ENA_PASSWORD'))))
            result = load_xml_from_string(r[-1].text)
            result_xml_tree.append(ET.ElementTree(result))
```

And only the last one worked. I generated the 18 runs, so once I upload the mapping to arrayExpress and update ingest this should be done!

**Comment by aaclan-ebi** [comment]
This ticket is to track archiving of Peng's additional data. Enrique confirmed this is done. Marking this done.

@ESapenaVentura I'll create a new ticket for updating the file metadata with the. new run accessions.
