### ISSUE TITLE
Delete incorrect submissions for EmbryonicHindlimb

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#436]
https://contribute.data.humancellatlas.org/submissions/detail?uuid=aa561fa2-c914-49e0-a118-eb4be69c4c45&project=b176d756-62d8-4933-83a4-8b026380262f

https://contribute.data.humancellatlas.org/submissions/detail?uuid=293b4493-7fd5-4fc1-a667-a0d574c78957&project=b176d756-62d8-4933-83a4-8b026380262f

**Comment by ke4** [comment]
https://contribute.data.humancellatlas.org/submissions/detail?uuid=aa561fa2-c914-49e0-a118-eb4be69c4c45&project=b176d756-62d8-4933-83a4-8b026380262f has been deleted successfully

**Comment by ke4** [comment]
https://contribute.data.humancellatlas.org/submissions/detail?uuid=293b4493-7fd5-4fc1-a667-a0d574c78957&project=b176d756-62d8-4933-83a4-8b026380262f has been deleted successfully

**Comment by aaclan-ebi** [comment]
Reasons why there were 2 unsubmitted submissions for EmbryonicHindlimb that needed to be deleted:
1. 1st submission has no ontology values.
2. 2nd submission has wrong linking.
