### ISSUE TITLE
Investigate delete submission issue 

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#450]
reported by Rachel

**Comment by yusra-haider** [comment]
tried deleting the dat submission against this project: https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=00a7f9e8-dd3a-4018-89ed-919a9e78d50c&tab=project and it was deleted successfully

**Comment by ESapenaVentura** [comment]
When finishing operation tasks please move to done, not closed!
