### ISSUE TITLE
Submit additional sequencing runs for project S-SUBS10

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#464]
Dataset: https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/573
Project in Ingest: https://contribute.data.humancellatlas.org/projects/detail?uuid=fc55bd4a-8694-4a28-9a35-59a685bda323&tab=upload
Submission: https://contribute.data.humancellatlas.org/submissions/detail?uuid=76283647-9b00-4651-9224-18a4db2b7b29&project=fc55bd4a-8694-4a28-9a35-59a685bda323

cc @ESapenaVentura

**Comment by aaclan-ebi** [comment]
The sequencing runs are submitted. We got 2 sequencing run accessions for our files: https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/61bb5a3ea356274470d321b7/files

**Comment by aaclan-ebi** [comment]
Sequencing experiment: ERX7324371, ERX7324372
Sequencing runs: ERR7782111, ERR7782112

Let's keep an eye for the new sequencing experiments and sequencing runs to appear in the ENA browser:
https://www.ebi.ac.uk/ena/browser/view/PRJEB38994?show=reads

**Comment by ESapenaVentura** [comment]
Let's check in 48 hours :) @ipediez can you check on wednesday? The task would be:
- Go to https://www.ebi.ac.uk/ena/browser/view/PRJEB38994?show=reads
- Ensure that runs ERR7782111 and ERR7782112 are in the table

If they are not, let me know and I can quickly check in!

**Comment by ipediez** [comment]
I just checked them and the runs are not available for now @ESapenaVentura. I will check it again PM

**Comment by aaclan-ebi** [comment]
I checked today and the files aren't available yet. I also noticed that the existing files appearing in the ENA browser are bam files. It seems that we haven't submitted the fastq files yet for this dataset. @ESapenaVentura do we need to fix the bam files for this dataset and add this project to ticket ebi-ait/hca-ebi-wrangler-central#250. 

In the meantime, I'll file a ticket to ENA to ask about the 2 additional sequencing runs which are still missing.

**Comment by aaclan-ebi** [comment]
I've verified that they are in the ENA webin/submission portal but not in the browser yet (32 files displayed instead of 34).

![Screenshot 2022-01-05 at 11.36.25.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/2632df40-1e97-4833-8eeb-f5d2b131ee71)

![Screenshot 2022-01-05 at 11.38.17.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/e92b77df-0231-48b8-a65e-56264d7bef70)

**Comment by aaclan-ebi** [comment]
![Screenshot 2022-01-05 at 11.46.53.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/a5095aa1-728e-443d-8ea9-bdacf40a2e7d)

**Comment by gabsie** [comment]
enquired about the missing file in the ENA browser.

**Comment by ipediez** [comment]
@aaclan-ebi is waiting for a response, she'll try other means of communication, maybe via slack

**Comment by prabh-t** [comment]
Enrique - to be handed over to the dev on ops for this sprint.

**Comment by ESapenaVentura** [comment]
We'll wait a bit on their backlog

**Comment by Wkt8** [comment]
Both runs are there with the relevant fastq files! This ticket can be closed.
