### ISSUE TITLE
Incorrect linking in ingest, preventing submission

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-dev-team#471]
I am getting errors in ingest after running the ingest graph validator. Specifically, many of the linkings are not appearing, although they are present in the spreadsheet. An error message is returned following graph validation "entity does not have linkings with any other entity". When I check this in the spreadsheet, it is not the case.

An example submission: https://contribute.data.humancellatlas.org/submissions/detail?uuid=00aa7a76-ccb1-4c18-a997-a241f484a003

@jacobwindsor believes this is an issue with import, as opposed to the graph validator.

If we do not fix this, we won't be able to submit new datasets for the Feb release.

**Comment by aaclan-ebi** [comment]
I moved this to ops board to track the fixing of the data/submission. I believe that bug that affected this submission was already fixed, https://github.com/ebi-ait/ingest-client/commit/289a33379dcc3c036b6e755d49988fded5b99073.

**Comment by Wkt8** [comment]
Ami has submitted the project for this, so this ticket could be closed if it's only for this submission.
