### ISSUE TITLE
Stuck submissions due to 1 submission failure

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#472]
Blocking submission
https://contribute.data.humancellatlas.org/submissions/detail?uuid=50d64edf-6fbe-48ea-89aa-80f3543dd077

exporter error:
```
===============================================ingest-exporter-c64895b4d-qxl26 logs
    result = func(*args, **kwargs)
  File "/app/exporter/terra/terra_exporter.py", line 42, in export
    self._wait_for_data_transfer_to_complete(export_job_id, success, transfer_job_spec)
  File "/app/exporter/terra/terra_exporter.py", line 70, in _wait_for_data_transfer_to_complete
    max_wait_time_sec)
  File "/app/exporter/terra/terra_export_job.py", line 118, in wait_for_data_transfer_to_complete
    timeout=max_wait_time_sec
  File "/usr/local/lib/python3.7/site-packages/polling.py", line 120, in poll
    raise TimeoutException(values, last_item)
polling.TimeoutException: (<queue.Queue object at 0x7f1b12d17dd0>, None)
\n\n\n
```

Stuck submissions:
https://contribute.data.humancellatlas.org/submissions/detail?uuid=386f32ec-6356-4db3-9ce0-a7e050957eee&project=e255b1c6-1143-4fa6-83a8-528f15b41038

https://contribute.data.humancellatlas.org/submissions/detail?uuid=045b193e-07ff-4ca2-9dba-6a2cdc0b9688&project=65d7a168-4d62-4bc0-8324-4e742aa62de6

See whole exporter logs: 
https://drive.google.com/drive/u/2/folders/12BBGFobhqbwgZxSot4r74XZAZzTZCtik
(this is a big file, need to download and grep)

**Comment by aaclan-ebi** [comment]
This is going to block all new submissions.

**Comment by aaclan-ebi** [comment]
I tried to fix the blocking submission last night, I'll list the steps here and discuss them with @ke4 tomorrow 

All 3 submissions have now finished exporting.

**Comment by aaclan-ebi** [comment]
@amnonkhen there's also an underlying issue with the current design of the exporter that if one submission is stuck or had failed, it will block other submissions. We should discuss how to avoid this in the future.

**Comment by ofanobilbao** [comment]
Moving ticket to done. Issue can be addressed in a separate new ticket
