### ISSUE TITLE
Update GCP service account key for prod Terra bucket access

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#478]
https://embl-ebi-ait.slack.com/archives/C01360XN04S/p1646834360690409

Tasks:
1. Update secret in aws
2.  Redeploy secrets
3. Redeploy exporter in prod

**Comment by aaclan-ebi** [comment]
For SOP:
1. Go to ingest-kube-deployment local repository
```
cd ingest-kube-deployment
```
1. Initialise environment vars config
```
source config/environment_prod
```
1. Go to apps
```
cd apps
```
1. Redeploy secrets 
```
make deploy-secrets
```
sample output:
```
/Library/Developer/CommandLineTools/usr/bin/make set-context
kubectx ingest-eks-prod
Switched to context "ingest-eks-prod".
kubens prod-environment
Context "ingest-eks-prod" modified.
Active namespace is "prod-environment".
./scripts/deploy_secrets
Release "secrets" has been upgraded. Happy Helming!
NAME: secrets
LAST DEPLOYED: Thu Mar 10 16:08:22 2022
NAMESPACE: prod-environment
STATUS: deployed
REVISION: 20
TEST SUITE: None
NOTES:
Ingest secrets powered by helm charts
```
1. Restart exporter.
```
kubectl rollout restart deployment ingest-exporter
```
sample output:
```
deployment.apps/ingest-exporter restarted
```

**Comment by Wkt8** [comment]
Secrets appear to be working in production - which fixed a submission which was stuck in re-exporting.

**Comment by amnonkhen** [comment]
sop in onboarding: https://ebi-ait.github.io/hca-ebi-dev-team/operations_tasks/update-exporter-gcp-creds.html
