### ISSUE TITLE
User login using Elixir account 

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#48]
Acceptance criteria
* [x] User can log in via Elixir account (could use Google account)
* [x] Only users with ebi email domain can use Ingest UI EBI deployment
* [ ] We are checking that the token came from Elixir

Could Implement UI integration using `oidc-client-js` library (suggested in the Elixir AAI documentation)

Elixir AAI OIDC documentation https://docs.google.com/document/d/1vOyW4dLVozy7oQvINYxHheVaLvwNsvvghbiKTLg7RbY/edit

Ingest Authentication at EBI
https://docs.google.com/document/d/1KVYX4zI81P4UoB4eAysUUr5GcktGFhcGbRYJ92bjJ-g/edit#

**Comment by aaclan-ebi** [comment]
PR ready. But holding off merging to master til core changes are in placed.

**Comment by aaclan-ebi** [comment]
Merged to master branch and has been deployed to DEV for testing.

**Comment by aaclan-ebi** [comment]
The Ingest UI AAI client account currently needed to be configured with redirect urls for dev and staging. Email was already sent to the aai-contact@elixir-europe.org.

**Comment by aaclan-ebi** [comment]
Redirect URI's are now configured. User login now works in dev but not yet passing token to Ingest Core.
Change was deployed only to dev to get tokens for testing changes for Ingest Core. The user wouldn't be able to create submissions atm in dev env.

**Comment by justincc** [comment]
Branch is in staging waiting for QA with wranglers and code review.
