### ISSUE TITLE
Delete test submissions in prod

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#484]

**Comment by ESapenaVentura** [comment]
Deleted the current test submissions but they will keep appearing (integration tests don't get deleted)

We need to look further into how to avoid this in the future

**Comment by jacobwindsor** [comment]
This is a dev task really. The integration test submissions dont get deleted if the integration test fails (which happens way too often)

**Comment by jacobwindsor** [comment]
Created this ticket https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/754
