### ISSUE TITLE
Update Archiving SOP

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#485]
Update the SOP based on the steps done for archiving AdultLungElo dataset ebi-ait/hca-ebi-wrangler-central#724 https://docs.google.com/document/d/1jSO4ZvoVlmvuJRJgZ87P1NWMUEzJR7RSn25RNze949g/edit#

**Comment by ESapenaVentura** [comment]
Wranglers to take a look

**Comment by Wkt8** [comment]
@jacobwindsor to check if the steps are already in the SOP, and if they are, to close the ticket

**Comment by jacobwindsor** [comment]
@Wkt8 looks like alegria merged her PR so I think this is done
