### ISSUE TITLE
Integrate Elixir AAI with Ingest

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#49]
This ticket is to track implementation tasks needed for Elixir AAI integration. Too small to be an epic so just creating dependencies among tickets.

https://docs.google.com/document/d/1KVYX4zI81P4UoB4eAysUUr5GcktGFhcGbRYJ92bjJ-g/edit#

**Comment by justincc** [comment]
Requested production AAI use from Steven Newhouse as EBI Elixir Technical Coordinator
