### ISSUE TITLE
HCA Ontology release 1.0.38

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-dev-team#490]
The HCA Ontology release 1.0.38 is out and and needs to be picked up. Tag should also be available automatically on Quay.io.

Could the OLS instance/EBI environment be reloaded and the validator cache cleared please?
SOP on how to do this [here](https://ebi-ait.github.io/hca-ebi-dev-team/operations_tasks/HCAO-release.html)
Thank you!

**Comment by amnonkhen** [comment]
1.0.38 is corrupt as well.
I installed it on dev, but could not [find HP:0000118](https://ontology.dev.archive.data.humancellatlas.org/search?q=HP%3A0000118&groupField=iri&exact=on&start=0&ontology=hcao).
Inspecting the code, I found that the OLS app does not load the [hpo_slim.owl](https://github.com/ebi-ait/ontology/blob/1.0.38/src/ontology/Makefile#L128) file. It tries to [load a file called hp_slim.owl]([url](https://github.com/ebi-ait/ontology/blob/1.0.38/ols/ols-config.yaml#L78)) instead. I notified Nico and David on slack.

**Comment by idazucchi** [comment]
Amnon is talking to Nico so that a new release will be prepared soon to fix the error
