### ISSUE TITLE
HCA Ontology Release 1.0.42

### ISSUE THREAD

**Issue by zoependlington** [ebi-ait/hca-ebi-dev-team#499]
The [HCA Ontology release 1.0.42](https://github.com/ebi-ait/ontology/releases/tag/1.0.42) is out and and needs to be picked up. Tag should also be available automatically on Quay.io.

Could the OLS instance/EBI environment be reloaded and the validator cache cleared please?

Thank you!

Tagging @pnejad, @rachadele @willrockout, @ESapenaVentura, @Wkt8, @idazucchi and @bvarner-ebi to keep in the loop.

**Comment by idazucchi** [comment]
@amnonkhen and @ESapenaVentura to take a look today

**Comment by amnonkhen** [comment]
Validation for v1.0.42:

- [ ] BFO_0000023 is under EFO
- [ ] BFO_0000023 is no longer under HCAO
- [ ] BFO_0000023 has more than 6 child terms

How can this be automated and added to the release process?

**Comment by ESapenaVentura** [comment]
Done! However, there were a couple of weird things:
- Had to change TF to v1.2.0 for dev deployment (@amnonkhen is investigating on this)
- had to change kubernete's config, for all the users (prod, staging, dev), the apiVersion from `client.authentication.k8s.io/v1alpha1` to `client.authentication.k8s.io/v1beta1`

**Comment by amnonkhen** [comment]
@ESapenaVentura deployed hcao 42 in all envs.
