### ISSUE TITLE
Ingest API using Elixir JWTs for authentication

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#51]
Ingest Core is already able to verify JWT tokens but there will be some minor changes to inspect token and whitelist email domain. 

Acceptance Criteria:
[] Only users with EBI account can create submissions and access secured endpoints
[] Unauthorised API calls should return 403 errors

**Comment by aaclan-ebi** [comment]
Changes are  in PR: https://github.com/ebi-ait/ingest-core/pull/4/files
The branch image is currently deployed in dev: https://ui.ingest.dev.archive.data.humancellatlas.org/home

**Comment by justincc** [comment]
See #48 for status

**Comment by aaclan-ebi** [comment]
Merged to master.
