### ISSUE TITLE
new ingest data issue: graph validation errors

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-dev-team#527]
*Overview*
I am seeing invalid graphs for two datasets (HumanCellLandscape and humanFoveaAndPeripheralRetinaAtlas) , but can't find any entities when I filter for "causes invalid graph". All entities appear to be linked.

*Project UUID*
1fac187b-1c3f-41c4-b6b6-6a9a8c0489d1
30dc3964-1135-4b56-b393-ce2dcbc6e379

*Issue Classification*
- [ *] data/metadata error

Ingest submission links:
[](https://contribute.data.humancellatlas.org/submissions/detail?uuid=783bdc02-10b7-4e4f-95d0-5b6be773d616
)
[](https://contribute.data.humancellatlas.org/submissions/detail?uuid=e43d967a-99b1-427b-9264-40dc0bd720f1)

*Additional references*
*Environment*
Browser

**Comment by ESapenaVentura** [comment]
This should be resolved :)
