### ISSUE TITLE
Upgrade to Helm 3

### ISSUE THREAD

**Issue by rdgoite** [ebi-ait/hca-ebi-dev-team#53]
Helm 3 has been officially released not to long ago and it operates quite differently from Helm 2, which is what we have now. We should consider switching now before it becomes harder when the versions start to diverge more significantly.

I'm not sure for how long the community will keep supporting Helm 2, but Helm 3 is now by default the installation package for Helm on packaging utilities like Homebrew.

**Comment by justincc** [comment]
They say that [from the most part Helm 2 charts should work with Helm 3](https://github.com/helm/helm/releases/tag/v3.0.0).

**Comment by justincc** [comment]
@prabh-t says last security fixes for Helm 2 will be May 2020

**Comment by aaclan-ebi** [comment]
I encountered the following error when redeploying some apps:

```
-wait --install
Error: UPGRADE FAILED: failed to replace object: Service "ingest-core-service" is invalid: spec.clusterIP: Invalid value: "": field is immutable
make: *** [deploy-app-ingest-core] Error 1
```

Looks like this is a current issue https://github.com/helm/helm/issues/7956#issuecomment-620749552 i downgraded my helm to 3.2.0 as a workaround
