### ISSUE TITLE
Create s3 bucket for storing modified loom files for March release

### ISSUE THREAD

**Issue by zperova** [ebi-ait/hca-ebi-dev-team#54]
**Description**

As a HCA wrangler who needs to modify metadata in the loom files from the HCA Data Browser and hand them over to the Broad team for processing, I need a secure location with write and read credentials for uploading, storing and working with the loom files. This s3 bucket will also be the location for the cell-type annotation experts to upload their annotations after the loom files have been processed with the Broad pipeline. 

This bucket will only be in use for the March release. 
@zperova is responsible to let @justincc know when this bucket is no longer needed and can be deleted.

**Acceptance criteria**

- [x] s3 bucket for March release has been created with write and read credentials for the EBI and Broad teams and for cell-type annotation experts.

**Comment by lauraclarke** [comment]
@justincc not sure how you want us to raise this but this is an urgent request that needs to be fulfilled ideally today, certainly by the end of Monday

**Comment by zperova** [comment]
s3 bucket created. Closing this issue.

**Comment by prabh-t** [comment]
More info in this repo:
https://github.com/ebi-ait/hca-ebi-dev-team/tree/master/scripts/march-release-loom-files
As @zperova said, the bucket is created and the one organ datasets have been copied over.
