### ISSUE TITLE
Add all wranglers to subs.team-2 domain

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-dev-team#57]
Add all the wranglers to the DSP domain that we are planning to use for submissions through the DSP, in order to give them permissions to submit through there. 

Please provide with your `userReference` or aap username by your name below:
- [x] Enrique: usr-a5be9e57-3d70-4a0c-b823-22b3688e21da , `enrique`
- [x] Marion: usr-c18a3b0f-ad87-4d2b-a77a-7904deec2f5f, `mshadbolt`
- [x] Ray: usr-cd8a2974-094b-4a2a-8e92-028c9b56e77d , `rays22`
- [x] Zina: usr-b47e8931-6839-419f-9c59-fb73277e81f6, `4a9c27044f2dad69741f98cc49135c0f8c7e5338`
- [x] @ami-day:  `d01e687b74cf536b6bf11ca50ccbd40f4d349b3a`

Detailed instructions on how to retrieve your `userReference` [here](https://github.com/HumanCellAtlas/hca-data-wrangling/issues/408)

Please one of @ebi-ait/hca-dev give us access to the domain!

**Comment by aaclan-ebi** [comment]
@ESapenaVentura @mshadbolt @rays22 @zperova @ami-day, I prefer using your AAP username? If you could provide it please. Thanks!

**Comment by ESapenaVentura** [comment]
Username: enrique

**Comment by mshadbolt** [comment]
I think I am already in that domain

**Comment by aaclan-ebi** [comment]
@ami-day  There's a link on how to create a local account from here: https://aai.ebi.ac.uk/home.  I think you can also use an elixir account, however I haven't tried adding an elixir user to a domain yet...

**Comment by aaclan-ebi** [comment]
Looks like Ami got assigned with an AAP username automatically when she logged in using her Elixir account `d01e687b74cf536b6bf11ca50ccbd40f4d349b3a`. I added that in the domain.

**Comment by aaclan-ebi** [comment]
@ESapenaVentura I added you as manager of that domain. You should be able to add users now as well.

**Comment by zperova** [comment]
i have logged using Elixir identity as well

**Comment by aaclan-ebi** [comment]
@zperova, a username should have been generated for you if you logged in using your Elixir account. Could you check that username by following this link: https://aai.ebi.ac.uk/useraccounts  ?

**Comment by aaclan-ebi** [comment]
oh I didn't see you already updated the ticket with your username. Adding it now to the domain...

**Comment by aaclan-ebi** [comment]
All listed users above are added to the domain. Marking ticket done. Please reopen if there are more people to be added.
