### ISSUE TITLE
Investigate the work required to change the archiver script to take metadata and data from ingest/upload

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#6]
Rather than the datastore.

**Acceptance criteria**
* [ ] We can point estimate the work.

**Comment by MightyAx** [comment]
As a learning task I fixed up the unit tests, this work is complete by [ingest-archiver#1](https://github.com/ebi-ait/ingest-archiver/pull/1)

Estimation work still due
