### ISSUE TITLE
Agree with the wrangler team on the structure of archive metadata

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#64]
Now that the wranglers have made submissions directly to the DSP they can show us how to make our automatic metadata archiver code conform to their best practice. This will mean an ingest developer sitting down with a wrangler (probably Enrique) to come to a common understanding of how the metadata needs to be structured in the archives.

**Acceptance criteria**
* [ ] We agree on the specification in [this doc](https://docs.google.com/document/d/1DvF0S9rL0IxnMdsi9P3qUVRt-IOT25KWqjwwIU7C9_s/edit#).

**Comment by MightyAx** [comment]
Current mapping document from Ingest Archiver, for review with wranglers:
[Mapping HCA Data to EBI Archive](https://docs.google.com/document/d/1DvF0S9rL0IxnMdsi9P3qUVRt-IOT25KWqjwwIU7C9_s)

**Comment by MightyAx** [comment]
We've had the meeting, and gained clarity with the wranglers.
Waiting for Enrique to comment on the Metadata Changes required.

**Comment by MightyAx** [comment]
Enrique's comments are in the  document: 
[Mapping HCA Data to EBI Archive](https://docs.google.com/document/d/1DvF0S9rL0IxnMdsi9P3qUVRt-IOT25KWqjwwIU7C9_s)
