### ISSUE TITLE
[BUG] Spreadsheets are throwing an error when imported

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-dev-team#72]
**Description of the issue**:
When uploading a metadata spreadsheet to the new ingest UI (ui.ingest.archive.humancellatlas.org), the importer throws an error: `'>' not supported between instances of 'NoneType' and 'int'`.

When trying to `dry_run` the importer I noticed that the it threw a more specific error: 
```
  File "/usr/local/lib/python3.7/site-packages/ingest/importer/conversion/data_converter.py", line 48, in convert
    return int(data)
ValueError: invalid literal for int() with base 10: '9606.0'
```

It seems that an integer (checked in the spreadsheet) is being passed as a float. This value corresponds to `biomaterial_core.ncbi_taxon_id` field.

**How to replicate the bug**:
Try to upload any metadata spreadsheet to ingest. So far I've tried 3 different spreadsheets and the 3 of them were throwing the same error on import.

**Impact of the bug**: High
**Why**: Wranglers need to be able to upload spreadsheets to ingest for metadata validation before proceeding to archiving.

**Comment by MightyAx** [comment]
Already deployed to staging
[Client](https://github.com/ebi-ait/ingest-client/commit/d1dfa751a7175041d5c93e3e9dded4b72cb8cdd2)
[Broker](https://github.com/ebi-ait/ingest-broker/commit/969bf78895f7adfeb72583cf70715067beb37b41)
