### ISSUE TITLE
Plan for transferring EBI HCA wrangler data to EBI storage

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#8]
**Acceptance criteria**
* [x] We know where the wrangler data is and how big it is
* [x] We have enough EBI storage to retain it
* [x] We know how to perform the transfer

**What we know**
See https://github.com/HumanCellAtlas/hca-data-wrangling/issues/399 for an enumeration of data.

Discussions begins [here](https://humancellatlas.slack.com/archives/GAQ2W4CKX/p1578560112013300). Will summarize below as necessary.

"Basically when we are interacting with a contributor, we create an s3 bucket then they upload all the files that they want to submit to that bucket. Then when it comes to submission we transfer those files to the s3 bucket provided by ingest." - Marion

**Other details**
* The EBI storage will probably be our own AWS S3/EC2 in the short term, though let's not take this for granted just yet.
* The wranglers set up their individual S3 buckets (really upload staging areas) using the scripts [here](https://github.com/HumanCellAtlas/upload-service/tree/master/scripts).

**What we need**
* An absolute minimum of about 25TB of storage for the existing wrangler-held data. But for safety and ongoing operations ideally quadruple that to 100TB
* [An m5.xlarge instance for wrangler operations](https://humancellatlas.slack.com/archives/GAQ2W4CKX/p1578575004051700) (pre-ingest validation, transferring data to ingest upload areas, etc.) 

**Open Questions**
1. How are the wranglers setting up and managing their S3 buckets?
1. What is the size of the EC2 instance?

**Comment by mshadbolt** [comment]
@justincc the full spreadsheet with breakdown of size per bucket and whether we would like to retain is mostly filled out here: https://docs.google.com/spreadsheets/d/12GPVxdqGEnd26OyOq-BEtIGJw9rE_ApiTmb2zfB3vtw/edit?ts=5e175e53#gid=0

It seems like the ~20TB estimate is about right
