### ISSUE TITLE
[DCP CLI] Support s3 to s3 transfer

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#80]
Configuration to allow the DCP HCA CLI to support file transfer from s3 to s3.

**Comment by aaclan-ebi** [comment]
This should now work in staging when s3 -> s3 is triggered from ec2 instance

But if triggered from local machine, the following error occurs:
```
17:48 $ hca upload files s3://org-hca-data-archive-upload-staging/aaaaaaaa-bbbb-cccc-dddd-bf849029f4dc/
Traceback (most recent call last):
  File "/usr/local/bin/hca", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/hca/cli.py", line 136, in main
    result = parsed_args.entry_point(parsed_args)
  File "/usr/local/lib/python2.7/site-packages/hca/upload/cli/upload_command.py", line 53, in __init__
    self._load_file_paths_from_upload_path(args, upload_path)
  File "/usr/local/lib/python2.7/site-packages/hca/upload/cli/upload_command.py", line 87, in _load_file_paths_from_upload_path
    s3_file_paths, s3_file_size_sum = self._retrieve_files_list_and_size_sum_tuple_from_s3_path(upload_path)
  File "/usr/local/lib/python2.7/site-packages/hca/upload/cli/upload_command.py", line 108, in _retrieve_files_list_and_size_sum_tuple_from_s3_path
    for page in page_iterator:
  File "/usr/local/lib/python2.7/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied```

**Comment by aaclan-ebi** [comment]
Looks like this functionality is intended to be only ran from the Wranglers EC2 instance. The code for the lambda function for requesting credentials is attaching a stricter policy for specific bucket https://github.com/ebi-ait/upload-service/blob/master/upload/common/upload_area.py#L103-L109

This should work now. S3 to S3 transfer should work in staging now.

Steps:
1. Login to Wranglers ec2 instance
```
ssh <username>@tool.archive.data.humancellatlas.org
```

1. Create an upload area outside submission by running script: https://github.com/ebi-ait/upload-service/blob/master/scripts/create_upload_area.py

```
python create_upload_area.py --api-key 'insert-api-key' --dataset-name alegria_test5 --environment staging  --data-dir-path /home/<username>/data
```

Note: hca-util can be used  to create an upload area but that needs changes to configuration in Upload Service deployment

2. Use HCA CLI (DCP) to upload files to the upload area created from step 1.

3. Create a submission and get the upload area from "Data" tab in the UI. 
```
hca upload select <submission-upload-area>
hca upload files <s3-bucket-from-step1>
```

Expected Behaviour:
All files should be copied FROM  step1 s3 location TO step 3 s3 location

**Comment by aaclan-ebi** [comment]
Configured this to source from s3 bucket: "arn:aws:s3:::hca-wrangler-backup"

The upload service code needs changing to configure session policy to multiple buckets:
https://github.com/ebi-ait/upload-service/blob/master/upload/common/upload_area.py#L95-L125

Currently I'm only modifying the dcp/upload/staging/secrets. staging_bucket_arn to configure the source bucket.

https://github.com/ebi-ait/upload-service/blob/master/upload/common/upload_area.py#L95-L125

**Comment by aaclan-ebi** [comment]
This is only deployed in staging env for wranglers to test.

**Comment by aaclan-ebi** [comment]
Created ticket #88 to allow multiple source s3 bucket locations.

**Comment by aaclan-ebi** [comment]
Hi @ESapenaVentura , It should be possible now to move any files from `hca-wrangler-backup` s3 bucket to submission upload areas. Could you verify? Thanks!

**Comment by ESapenaVentura** [comment]
Verified right now!

**Comment by aaclan-ebi** [comment]
Update: In Prod, it's possible to do copy files from `hca-ingest-upload` to the submission upload areas now.

**Comment by aaclan-ebi** [comment]
This was used in Rasa's dataset submission in prod. Marking this done.

**Comment by aaclan-ebi** [comment]
Need to confirm what the source buckets should be for dev & staging , putting back to in progress.
I think i'll set all env to source from `hca-ingest-upload` for consistency. A separate ticket is filed to allow multiple source configuration https://app.zenhub.com/workspaces/ingest-dev-5cfe1cb26482e537cf35e8d1/issues/ebi-ait/hca-ebi-dev-team/88 

This should also be supported in the hca-util (Hinxton cli)

**Comment by aaclan-ebi** [comment]
Need to confirm what the source buckets should be for dev & staging. A separate ticket is filed to allow multiple source configuration
