### ISSUE TITLE
[Hinxton CLI] Support s3 to s3 file transfer

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#82]

**Comment by clairerye** [comment]
Moving to done and closing, but move back if you I have misunderstood.

**Comment by aaclan-ebi** [comment]
released last 29 July to PyPI https://github.com/ebi-ait/hca-util/blob/212d23cec32c601fba6c6cbe7ab5b2b1c6fddb3a/RELEASE.md#29-july-2020-v0210
