### ISSUE TITLE
[Archiver] Set DSP Project ReleaseDate

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#84]
As a contributor I want updates to release dates in the UI to be reflected in DSP.
Ingest Core now support release date properties on Projects.
### Acceptance criteria:
- [ ] Map this to the release date field for the submission in DSP.

**Comment by MightyAx** [comment]
Prior to ingest storing this information the following options were considered:
- Set a DSP Project Release Date Manually before submission.
- Have provide a "releaseDate" option in archiver to do the above automatically

**Comment by MightyAx** [comment]
Planning Poker: 1-3

**Comment by aaclan-ebi** [comment]
https://docs.google.com/document/d/1yXTelUt-CvlI7-Jkh7K_NCPIBfhRXMvjT4wRkyxpIN0/edit#heading=h.22wplbfnv37s

**Comment by aaclan-ebi** [comment]
What would happen if release date in the project is not set?

**Comment by aaclan-ebi** [comment]
@rdgoite / @ESapenaVentura  it would be nice to update the mapping document with the agreed changes for the release date. https://docs.google.com/document/d/1DvF0S9rL0IxnMdsi9P3qUVRt-IOT25KWqjwwIU7C9_s/edit#

This would be helpful for future reference.
