### ISSUE TITLE
Track, assess and if possible reduce S3 and RDS costs

### ISSUE THREAD

**Issue by justincc** [ebi-ait/hca-ebi-dev-team#89]
From Tony Wildish's e-mail on 2020-03-05, we need to assess our S3 and RDS costs, and whether we can reduce them.

**Draft alternatives for reducing RDS costs**
1) Tell the cloud consultants that these are essential costs. Probably not a viable option at this time.

2) Shutdown different upload services when not used (and if at all possible automate spinup/shutdown). Cons: even more engineering time. Pros: perhaps not as much re-engineering of the upload service itself.

3) Re-engineer upload service to use a single instance. Cons: engineering time, devops time to automate provision outside of the upload service. Still 200 USD p/m

4) Host postgres on our own EC2 instance. Cons: as for 2) above plus infrastructure to do backups. Pros: Maybe cheaper? (not sure, haven't done the calculations). 

**Draft alternatives for reducing S3 costs**
This is where we probably need some way of automatically auditing what we are storing.

**Comment by rolando-ebi** [comment]
Investigating Aurora Serverless for reducing RDS costs

**Comment by justincc** [comment]
Completed to current satisfaction
