### ISSUE TITLE
Elixir authn provider breaks when ran on GCP tokens

### ISSUE THREAD

**Issue by rolando-ebi** [ebi-ait/hca-ebi-dev-team#92]
When the Elixir authn provider authenticate()'s a GCP JWT, a RuntimeException is thrown that breaks the execution of the authentication filter chain. Ideally, we should `return false` when the `supports()` method on the Elixir provider is called on a GCP JWT. Or, we can catch and log any unexpected exception and `return null`, as per the documentation.

Acceptance criteria:
- The core's authentication filter chain doesn't break when `ElixirAaiAuthenticationProvider.authenticate()` is called on a GCP JWT token
- The `GoogleServiceJwtAuthenticationProvider.authenticate()` method can also break the chain if called with an Elixir JWT token, ideally fix this class as well

**Comment by aaclan-ebi** [comment]
Should be fixed in the version released last 26th May
https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#26-may-2020
