### ISSUE TITLE
[Archiver] Record results in Core

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#97]
Archiver should write the results of an Archive Submission back to Ingest Core:
Entities:
- DSP entity links
- Archive Accessions
- Converted Entity JSON

Submissions:
- Validation Results
- Processing Status

**Comment by aaclan-ebi** [comment]
Is the updating of metadata json with accessions in scope here?

**Comment by MightyAx** [comment]
I think so, does that drastically change the implementation concerns?

**Comment by aaclan-ebi** [comment]
I'm not sure yet. Depends on the design. I see the complexity in our archiver code being very schema-aware. It is already schema-aware now anyway.

**Comment by aaclan-ebi** [comment]
We should also add the effort of updating the accessions of already archived datasets.

**Comment by aaclan-ebi** [comment]
we need to collect all the accessions we have so far, currently ongoing: https://embl-ebi-ait.slack.com/archives/C012DG6R1EV/p1589457229005000

**Comment by lauraclarke** [comment]
> I'm not sure yet. Depends on the design. I see the complexity in our archiver code being very schema-aware. It is already schema-aware now anyway.

Can the code which will reinsert accessions to our metadata schema be isolated from the non-schema dependent code?

**Comment by MightyAx** [comment]
The current / intended scope for this ticket is for Archiver to record accessions against MetaDataDocuments in ingest-core. 

A good requirement to add to the ticket might be:
**The ability to add the accessions to ingest projects for data previously archived.**
Explicitly calling out that we should support our manual datasets

Since as of this ticket archiver will be a manual process, I think the work to update those previously archived projects is another task.

**Comment by MightyAx** [comment]
### Implementation Idea
Using the [new core functionality](https://app.zenhub.com/workspace/o/ebi-ait/hca-ebi-dev-team/issues/96): 
1. When Archiver generates and submits metadata to DSP:
- Archiver should write back the DSP entity link and content to ingest MetaDataDocuments.
**Planning Poker: 3**

2. When archiver is used to complete a submission:
- Archiver should store accessions against the relevant ingest MetaDataDocuments
**Planning Poker: 3**

3. A new Archiver "query" mode that if run on a project that contains a submission that is open in DSP will copy the DSP validation issues into ingest, and set the processing status in ingest accordingly
**Planning Poker: 5**

3. A new archiver "linking" mode that can be used to perform the above operations on ingest projects that have already been archived: Allowing them to be updated with the above entity links, accessions, and any other benefits of "Automatically Archived" projects.
**Planning poker: 5**

**Comment by aaclan-ebi** [comment]
This is captured in #147 
PR: https://github.com/ebi-ait/ingest-core/pull/21
